%% S3 bucket addressing helpers for smithy.beam.test.s3restxml#S3RestXmlService (generated).
%% DO NOT EDIT -- generated by smithy-beam codegen.
-module(s3_endpoint).
-export([resolve_bucket_url/3, region_host/1]).
-type client_config() :: #{binary() => term()}.

-spec region_host(client_config()) -> binary().
region_host(Config) ->
    BaseUrl = maps:get(base_url, Config, <<>>),
    {_Scheme, Authority} = split_base_url(BaseUrl),
    Authority.

-spec resolve_bucket_url(client_config(), binary(), binary()) -> {binary(), binary()}.
resolve_bucket_url(Config, Bucket, Key) ->
    Style = maps:get(s3_addressing_style, Config, virtual_host),
    RegionHost = region_host(Config),
    KeyPath = key_path(Key),
    case Style of
        virtual_host ->
            Host = virtual_host(Config, Bucket, RegionHost),
            {Host, KeyPath};
        path_style ->
            {RegionHost, <<"/", Bucket/binary, KeyPath/binary>>};
        _ ->
            Host = virtual_host(Config, Bucket, RegionHost),
            {Host, KeyPath}
    end.

key_path(<<>>) -> <<>>;
key_path(Key) -> <<"/", Key/binary>>.

virtual_host(Config, Bucket, RegionHost) ->
    case maps:get(s3_use_accelerate, Config, false) of
        true ->
            <<Bucket/binary, ".s3-accelerate.amazonaws.com">>;
        false ->
            Suffix = s3_host_suffix(Config),
            <<Bucket/binary, Suffix/binary, RegionHost/binary>>
    end.

s3_host_suffix(Config) ->
    case maps:get(s3_use_dualstack, Config, false) of
        true -> <<".s3.dualstack.">>;
        false -> <<".s3.">>
    end.

split_base_url(<<>>) ->
    {<<>>, <<>>};
split_base_url(BaseUrl) ->
    case uri_string:parse(binary_to_list(BaseUrl)) of
        #{scheme := Scheme, host := Host} = Parts ->
            PortSuffix =
                case maps:get(port, Parts, undefined) of
                    undefined -> <<>>;
                    Port -> <<":", (integer_to_binary(Port))/binary>>
                end,
            {<<(list_to_binary(Scheme))/binary, "://">>, <<
                (list_to_binary(Host))/binary, PortSuffix/binary
            >>};
        _ ->
            {<<>>, BaseUrl}
    end.
