%% REST JSON 1 codecs for smithy.beam.demo.http#HttpService (generated).
%% DO NOT EDIT -- generated by smithy-beam codegen.
-module(http_service_rest_json_1).
-include("http_service_types.hrl").
-include("runtime_types.hrl").
-export([
    encode_get_name_request/1,
    decode_get_name_response/1
]).

%% @doc Encode HTTP request for smithy.beam.demo.http#GetName.
-spec encode_get_name_request(get_name_input()) -> #http_request{}.
encode_get_name_request(_Input = #get_name_input{name = Name}) ->
    Path = <<"/names/", (uri_encode(to_binary(Name)))/binary>>,
    Query = [],
    Headers = [{<<"Content-Type">>, <<"application/json">>}],
    Body = <<>>,
    #http_request{
        method = <<"GET">>,
        path = Path,
        query = maps:from_list(Query),
        headers = Headers,
        body = Body
    }.

%% @doc Decode HTTP response for smithy.beam.demo.http#GetName.
-spec decode_get_name_response(#http_response{}) -> {'ok', get_name_output()} | {'error', term()}.
decode_get_name_response(#http_response{status = 200, headers = _Headers, body = Body}) ->
    Decoded = decode_json_body(Body),
    {ok, #get_name_output{
        name = maps:get(<<"name">>, Decoded, undefined)
    }};
decode_get_name_response(#http_response{status = Status, headers = RespHeaders, body = Body}) ->
    decode_get_name_response_error(Status, RespHeaders, Body).

%% @doc Error dispatch for smithy.beam.demo.http#GetName.
decode_get_name_response_error(Status, _Hdrs, Body) -> {error, {unknown_error, Status, Body}}.

to_binary(V) when is_binary(V) -> V;
to_binary(V) when is_list(V) -> list_to_binary(V);
to_binary(true) -> <<"true">>;
to_binary(false) -> <<"false">>;
to_binary(V) when is_atom(V) -> atom_to_binary(V, utf8);
to_binary(V) when is_integer(V) -> integer_to_binary(V);
to_binary(V) when is_float(V) -> float_to_binary(V).

uri_encode(Value) -> uri_string:quote(Value).

uri_decode(Value) when is_binary(Value) -> uri_string:unquote(Value);
uri_decode(undefined) -> undefined.

decode_json_body(<<>>) ->
    #{};
decode_json_body(Body) ->
    case jsone:try_decode(Body) of
        {ok, V, _} when is_map(V) -> V;
        _ -> #{}
    end.
