package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.core.BeamProtocolIds;
import io.smithy.beam.core.BeamXmlBindingIndex;
import io.smithy.beam.ir.erlang.ErlAttribute;
import io.smithy.beam.ir.erlang.ErlComment;
import io.smithy.beam.ir.erlang.ErlExportAttribute;
import io.smithy.beam.ir.erlang.ErlFunction;
import io.smithy.beam.ir.erlang.ErlModule;
import io.smithy.beam.ir.erlang.ErlModuleAttribute;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBinding;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.EnumShape;
import software.amazon.smithy.model.shapes.IntEnumShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.StructureShape;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

final class ErlangRestXmlIr {
    private ErlangRestXmlIr() {}

    static String clientCodecFileName(ErlangContext ctx, ServiceShape service) {
        return layout(ctx, service).clientCodecModuleName(BeamProtocolIds.REST_XML) + ".erl";
    }

    static String serverCodecFileName(ErlangContext ctx, ServiceShape service) {
        return layout(ctx, service).serverCodecModuleName(BeamProtocolIds.REST_XML) + ".erl";
    }

    static ErlModule buildClientCodecModule(ErlangContext ctx, ServiceShape service) {
        Model model = ctx.model();
        BeamErlangLayout layout = layout(ctx, service);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        boolean encodeWithConfig = ErlangRestXmlSupport.serviceEncodesWithConfig(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
            exports.add("encode_" + name + "_request/" + (encodeWithConfig ? "2" : "1"));
            exports.add("decode_" + name + "_request/" + (labels.isEmpty() ? "1" : "2"));
            exports.add("decode_" + name + "_response/1");
        }

        Optional<String> serviceNamespace = BeamXmlBindingIndex.xmlNamespaceUri(service);

        List<ErlFunction> functions = clientCodecFunctions(
                model, service, operations, httpIndex, sp, serviceNamespace, encodeWithConfig);

        List<ErlModuleAttribute> attributes = new ArrayList<>();
        attributes.add(new ErlAttribute("include", "\"" + layout.typesHeaderFile() + "\""));
        attributes.add(new ErlAttribute("include", "\"" + layout.runtimeTypesHeaderFile() + "\""));
        if (encodeWithConfig) {
            attributes.add(new ErlAttribute("type", "client_config() :: #{binary() => term()}"));
        }
        attributes.add(ErlExportAttribute.export(exports));

        return new ErlModule(
                layout.clientCodecModuleName(BeamProtocolIds.REST_XML),
                List.of(
                        ErlComment.comment("REST-XML codecs for " + service.getId() + " (generated)."),
                        ErlComment.comment("DO NOT EDIT -- generated by smithy-beam codegen.")),
                attributes,
                functions);
    }

    static ErlModule buildServerCodecModule(ErlangContext ctx, ServiceShape service) {
        Model model = ctx.model();
        BeamErlangLayout layout = layout(ctx, service);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        Set<ShapeId> errorIds = new LinkedHashSet<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
            exports.add("decode_" + name + "_request/" + (labels.isEmpty() ? "1" : "2"));
            exports.add("encode_" + name + "_response/1");
            errorIds.addAll(op.getErrors());
        }
        for (ShapeId errorId : errorIds) {
            StructureShape errShape = model.expectShape(errorId, StructureShape.class);
            exports.add("encode_" + ErlangRestXmlSupport.recordName(sp.toSymbol(errShape)) + "_response/1");
        }

        Optional<String> serviceNamespace = BeamXmlBindingIndex.xmlNamespaceUri(service);

        List<ErlFunction> functions = serverCodecFunctions(
                model, service, operations, httpIndex, sp, serviceNamespace);

        return new ErlModule(
                layout.serverCodecModuleName(BeamProtocolIds.REST_XML),
                List.of(
                        ErlComment.comment("Server REST-XML codecs for " + service.getId() + " (generated)."),
                        ErlComment.comment("DO NOT EDIT -- generated by smithy-beam codegen.")),
                List.of(
                        new ErlAttribute("include", "\"" + layout.typesHeaderFile() + "\""),
                        new ErlAttribute("include", "\"" + layout.runtimeTypesHeaderFile() + "\""),
                        ErlExportAttribute.export(exports)),
                functions);
    }

    static void emitClientCodecModule(ErlangContext ctx, ServiceShape service) {
        ErlModule module = buildClientCodecModule(ctx, service);
        ErlangCodecEmission.writeModule(ctx, clientCodecFileName(ctx, service), module);
    }

    static void emitServerCodecModule(ErlangContext ctx, ServiceShape service) {
        ErlangCodecEmission.emitRuntimeHelpersIfNeeded(ctx, service, true);
        ErlModule module = buildServerCodecModule(ctx, service);
        ErlangCodecEmission.writeModule(ctx, serverCodecFileName(ctx, service), module);
    }

    private static BeamErlangLayout layout(ErlangContext ctx, ServiceShape service) {
        return new BeamErlangLayout(ctx.settings(), service.getId().getNamespace(), service);
    }

    static ErlFunction encodeRequest(
            Model model,
            ServiceShape service,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp,
            boolean encodeWithConfig) {
        return ErlangRestXmlOperationIr.buildEncodeRequest(
                model, service, op, httpIndex, sp, encodeWithConfig);
    }

    static ErlFunction decodeRequest(
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {
        return ErlangRestXmlOperationIr.buildDecodeRequest(model, op, httpIndex, sp);
    }

    static List<ErlFunction> decodeResponse(
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {
        return ErlangRestXmlOperationIr.buildDecodeResponse(model, op, httpIndex, sp);
    }

    static ErlFunction encodeResponse(
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {
        return ErlangRestXmlOperationIr.buildEncodeResponse(model, op, httpIndex, sp);
    }

    static List<ErlFunction> enumHelperFunctions(Model model, ServiceShape service, SymbolProvider sp) {
        List<ErlFunction> functions = new ArrayList<>();
        for (EnumShape enumShape : ErlangRestXmlSupport.reachableEnumShapes(model, service)) {
            functions.addAll(ErlangEnumHelperIr.enumDecodeEncode(enumShape, sp));
        }
        for (IntEnumShape intEnumShape : ErlangRestXmlSupport.reachableIntEnumShapes(model, service)) {
            functions.addAll(ErlangEnumHelperIr.intEnumDecodeEncode(intEnumShape, sp));
        }
        return functions;
    }

    static List<ErlFunction> xmlDecodeHelpers() {
        return ErlangXmlCodecIr.restXmlDecodeHelpers();
    }

    static List<ErlFunction> xmlEncodeHelpers() {
        return ErlangXmlCodecIr.restXmlEncodeHelpers();
    }

    static List<ErlFunction> clientCodecFunctions(
            Model model,
            ServiceShape service,
            List<OperationShape> operations,
            HttpBindingIndex httpIndex,
            SymbolProvider sp,
            Optional<String> serviceNamespace,
            boolean encodeWithConfig) {
        List<ErlFunction> functions = new ArrayList<>();
        functions.add(ErlangXmlCodecIr.xmlNamespace(serviceNamespace));
        for (OperationShape op : operations) {
            functions.add(encodeRequest(model, service, op, httpIndex, sp, encodeWithConfig));
            functions.add(decodeRequest(model, op, httpIndex, sp));
            functions.addAll(decodeResponse(model, op, httpIndex, sp));
        }
        functions.addAll(enumHelperFunctions(model, service, sp));
        functions.addAll(xmlEncodeHelpers());
        functions.addAll(xmlDecodeHelpers());
        functions.add(ErlangCodecHelperIr.prefixHeadersToList());
        functions.add(ErlangCodecHelperIr.prefixHeadersFromList());
        functions.add(ErlangCodecHelperIr.generateUuid());
        if (ErlangHttpChecksumEmitter.serviceHasChecksumOperations(model, service)) {
            functions.addAll(ErlangHttpChecksumIr.checksumHelperFunctions());
        }
        if (encodeWithConfig) {
            functions.addAll(ErlangHostLabelIr.buildHostFunctions(model, service, sp));
        }
        return functions;
    }

    static List<ErlFunction> serverCodecFunctions(
            Model model,
            ServiceShape service,
            List<OperationShape> operations,
            HttpBindingIndex httpIndex,
            SymbolProvider sp,
            Optional<String> serviceNamespace) {
        List<ErlFunction> functions = new ArrayList<>();
        functions.add(ErlangXmlCodecIr.xmlNamespace(serviceNamespace));
        Set<ShapeId> emittedErrorEncoders = new LinkedHashSet<>();
        for (OperationShape op : operations) {
            functions.add(decodeRequest(model, op, httpIndex, sp));
            functions.add(encodeResponse(model, op, httpIndex, sp));
            for (ShapeId errorId : op.getErrors()) {
                if (emittedErrorEncoders.add(errorId)) {
                    functions.add(ErlangRestXmlOperationIr.buildErrorResponseEncoder(model, errorId, sp));
                }
            }
        }
        functions.addAll(enumHelperFunctions(model, service, sp));
        functions.addAll(xmlEncodeHelpers());
        functions.addAll(xmlDecodeHelpers());
        return functions;
    }
}
