package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.core.BeamNameUtils;
import software.amazon.smithy.codegen.core.Symbol;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBinding;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.EnumShape;
import software.amazon.smithy.model.shapes.IntEnumShape;
import software.amazon.smithy.model.shapes.ListShape;
import software.amazon.smithy.model.shapes.MapShape;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.StructureShape;
import software.amazon.smithy.model.shapes.TimestampShape;
import software.amazon.smithy.model.shapes.UnionShape;
import software.amazon.smithy.model.traits.EnumValueTrait;
import software.amazon.smithy.model.traits.TimestampFormatTrait;
import software.amazon.smithy.model.traits.HttpErrorTrait;
import software.amazon.smithy.model.traits.HttpTrait;
import software.amazon.smithy.model.traits.JsonNameTrait;
import software.amazon.smithy.model.traits.SparseTrait;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * REST JSON codec scaffolding for Erlang. Emits real encode/decode functions
 * when a REST JSON 1 protocol is selected; keeps codegen-core free of Erlang imports.
 */
public final class ErlangRestJson1Emitter {

    private ErlangRestJson1Emitter() {}

    /** Entry point called from ErlangClientDirectedCodegen#generateService. */
    public static void emitCodecModule(ErlangContext ctx, ServiceShape service) {
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        ErlangRuntimeHelpersEmitter.emitIfNeeded(ctx, service);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
            exports.add("encode_" + name + "_request/1");
            exports.add("decode_" + name + "_request/" + (labels.isEmpty() ? "1" : "2"));
            exports.add("decode_" + name + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(layout.codecModuleFile(), writer -> {
            writer.write("%% REST JSON 1 codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", layout.codecModuleName());
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            writer.write("-export([$L]).", String.join(", ", exports));
            writer.write("");

            for (OperationShape op : operations) {
                emitEncoder(writer, model, service, op, httpIndex, sp);
                emitRequestDecoder(writer, model, op, httpIndex, sp);
                emitDecoder(writer, model, service, op, httpIndex, sp, layout);
            }

            for (OperationShape op : operations) {
                emitErrorDispatch(writer, model, service, op, httpIndex, sp);
            }

            emitEnumHelpers(writer, model, service, sp);
            emitUnionHelpers(writer, model, service, sp);
            emitHelpers(writer);
        });
    }

    /** Entry point called from ErlangServerDirectedCodegen#generateService. */
    public static void emitServerCodecModule(ErlangContext ctx, ServiceShape service) {
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        ErlangRuntimeHelpersEmitter.emitIfNeeded(ctx, service);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        Set<ShapeId> errorIds = new LinkedHashSet<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
            exports.add("decode_" + name + "_request/" + (labels.isEmpty() ? "1" : "2"));
            exports.add("encode_" + name + "_response/1");
            errorIds.addAll(op.getErrors());
        }
        for (ShapeId errorId : errorIds) {
            StructureShape errShape = model.expectShape(errorId, StructureShape.class);
            exports.add("encode_" + recordName(sp.toSymbol(errShape)) + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(layout.serverCodecModuleFile(), writer -> {
            writer.write("%% Server REST JSON 1 codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", layout.serverCodecModuleName());
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            writer.write("-export([$L]).", String.join(", ", exports));
            writer.write("");

            Set<ShapeId> emittedErrorEncoders = new LinkedHashSet<>();
            for (OperationShape op : operations) {
                emitRequestDecoder(writer, model, op, httpIndex, sp);
                emitResponseEncoder(writer, model, op, httpIndex, sp);
                emitErrorResponseEncoders(writer, model, op, sp, emittedErrorEncoders);
            }
            emitEnumHelpers(writer, model, service, sp);
            emitUnionHelpers(writer, model, service, sp);
            emitHelpers(writer);
        });
    }

    /** Emits encode_<op>_request/1 for one operation. */
    private static void emitEncoder(
            ErlangWriter writer,
            Model model,
            ServiceShape service,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
        String inputRecord = recordName(sp.toSymbol(input));
        HttpTrait httpTrait = op.expectTrait(HttpTrait.class);
        String method = httpTrait.getMethod();
        String uriTemplate = httpTrait.getUri().toString();

        List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
        List<HttpBinding> queries = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY);
        List<HttpBinding> queryParams = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY_PARAMS);
        List<HttpBinding> headers = httpIndex.getRequestBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> docMembers = httpIndex.getRequestBindings(op, HttpBinding.Location.DOCUMENT);

        List<String> patternParts = buildPatternParts(labels, queries, queryParams, headers, docMembers, sp, model);
        String pattern = patternParts.isEmpty() ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

        writer.write("%% Encode HTTP request for $L.", op.getId());
        writer.write("encode_$L_request(#$L{$L}) ->", opName, inputRecord, pattern);
        writer.indent();

        String pathExpr = buildPathExpression(uriTemplate, labels, sp, model);
        writer.write("Path = $L,", pathExpr);

        if (queries.isEmpty()) {
            writer.write("Query = [],");
        } else {
            writer.write("Query = lists:filtermap(fun");
            for (HttpBinding qb : queries) {
                String fieldName = BeamNameUtils.toSnakeCase(qb.getMember().getMemberName());
                String paramName = qb.getLocationName();
                writer.write("    (V) when V =/= undefined -> {true, {<<\"$L\">>, encode_query_value(V)}};",
                        paramName);
            }
            writer.write("    (_) -> false");
            writer.write("end, [$L]),",
                    queries.stream()
                            .map(qb -> toBindingVar(
                                    BeamNameUtils.toSnakeCase(qb.getMember().getMemberName())))
                            .collect(Collectors.joining(", ")));
        }

        if (!queryParams.isEmpty()) {
            for (HttpBinding qp : queryParams) {
                String fieldName = BeamNameUtils.toSnakeCase(qp.getMember().getMemberName());
                String bindingVar = toBindingVar(fieldName);
                writer.write("QueryExtra = case $L of", bindingVar);
                writer.indent();
                writer.write("undefined -> [];");
                writer.write("M when is_map(M) ->");
                writer.indent();
                writer.write("[{K, V} || {K, V} <- maps:to_list(M)]");
                writer.dedent();
                writer.dedent();
                writer.write("end,");
                writer.write("Query = Query ++ QueryExtra,");
            }
        }

        if (headers.isEmpty()) {
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"application/json\">>}],");
        } else {
            writer.write("Headers0 = lists:filtermap(fun");
            for (HttpBinding hb : headers) {
                String fieldName = BeamNameUtils.toSnakeCase(hb.getMember().getMemberName());
                String headerName = hb.getLocationName();
                writer.write("    (V) when V =/= undefined -> {true, {<<\"$L\">>, to_binary(V)}};",
                        headerName);
            }
            writer.write("    (_) -> false");
            writer.write("end, [$L]),",
                    headers.stream()
                            .map(hb -> toBindingVar(
                                    BeamNameUtils.toSnakeCase(hb.getMember().getMemberName())))
                            .collect(Collectors.joining(", ")));
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"application/json\">>} | Headers0],");
        }

        if (docMembers.isEmpty() || method.equals("GET") || method.equals("DELETE") || method.equals("HEAD")) {
            writer.write("Body = <<>>,");
        } else {
            writer.write("BodyMap = maps:filter(fun(_, V) -> V =/= undefined end, #{");
            for (int i = 0; i < docMembers.size(); i++) {
                HttpBinding db = docMembers.get(i);
                String fieldName = BeamNameUtils.toSnakeCase(db.getMember().getMemberName());
                String wireKey = jsonKey(db.getMember());
                String comma = i < docMembers.size() - 1 ? "," : "";
                Shape target = model.expectShape(db.getMember().getTarget());
                if (target instanceof EnumShape || target instanceof IntEnumShape) {
                    String helperName = sp.toSymbol(target).getName().replace("()", "");
                    writer.write("    <<\"$L\">> => encode_$L($L)$L",
                            wireKey, helperName, toBindingVar(fieldName), comma);
                } else if (target instanceof UnionShape) {
                    String helperName = sp.toSymbol(target).getName().replace("()", "");
                    writer.write("    <<\"$L\">> => encode_$L($L)$L",
                            wireKey, helperName, toBindingVar(fieldName), comma);
                } else if (target instanceof TimestampShape) {
                    String encodeHelper = timestampEncodeHelper(
                            httpIndex, db.getMember(), HttpBinding.Location.DOCUMENT);
                    writer.write("    <<\"$L\">> => $L($L)$L",
                            wireKey, encodeHelper, toBindingVar(fieldName), comma);
                } else {
                    writer.write("    <<\"$L\">> => $L$L",
                            wireKey, encodeDocumentValue(target, fieldName), comma);
                }
            }
            writer.write("}),");
            writer.write("Body = jsone:encode(BodyMap),");
        }

        writer.write("#http_request{");
        writer.write("    method = <<\"$L\">>,", method);
        writer.write("    path = Path,");
        writer.write("    query = maps:from_list(Query),");
        writer.write("    headers = Headers,");
        writer.write("    body = Body");
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    /** Emits decode_<op>_request for one operation (server-side request parsing). */
    private static void emitRequestDecoder(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
        String inputRecord = recordName(sp.toSymbol(input));

        List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
        List<HttpBinding> queries = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY);
        List<HttpBinding> queryParams = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY_PARAMS);
        List<HttpBinding> headers = httpIndex.getRequestBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> docMembers = httpIndex.getRequestBindings(op, HttpBinding.Location.DOCUMENT);

        writer.write("%% Decode HTTP request for $L.", op.getId());
        if (labels.isEmpty()) {
            writer.write(
                    "decode_$L_request(#http_request{query = Query, headers = Headers, body = Body}) ->",
                    opName);
        } else {
            writer.write(
                    "decode_$L_request(#http_request{query = Query, headers = Headers, body = Body}, LabelMap) ->",
                    opName);
        }
        writer.indent();

        if (!docMembers.isEmpty()) {
            writer.write("Decoded = case Body of");
            writer.indent();
            writer.write("<<>> -> #{};");
            writer.write("_ ->");
            writer.indent();
            writer.write("case jsone:try_decode(Body) of");
            writer.indent();
            writer.write("{ok, Val, _} -> Val;");
            writer.write("{error, _} -> #{}");
            writer.dedent();
            writer.write("end");
            writer.dedent();
            writer.dedent();
            writer.write("end,");
        }

        List<String> recordFields = new ArrayList<>();
        for (HttpBinding lb : labels) {
            String fieldName = BeamNameUtils.toSnakeCase(lb.getMember().getMemberName());
            String memberName = lb.getMember().getMemberName();
            recordFields.add(
                    "    " + fieldName + " = uri_decode(maps:get(<<\"" + memberName + "\">>, LabelMap, undefined))");
        }
        for (HttpBinding qb : queries) {
            String fieldName = BeamNameUtils.toSnakeCase(qb.getMember().getMemberName());
            String paramName = qb.getLocationName();
            recordFields.add(
                    "    " + fieldName + " = decode_query_param(maps:get(<<\"" + paramName + "\">>, Query, undefined))");
        }
        for (HttpBinding qp : queryParams) {
            String fieldName = BeamNameUtils.toSnakeCase(qp.getMember().getMemberName());
            recordFields.add("    " + fieldName + " = maps:from_list(maps:to_list(Query))");
        }
        for (HttpBinding hb : headers) {
            String fieldName = BeamNameUtils.toSnakeCase(hb.getMember().getMemberName());
            String headerName = hb.getLocationName();
            recordFields.add(
                    "    " + fieldName + " = proplists:get_value(<<\"" + headerName + "\">>, Headers, undefined)");
        }
        for (HttpBinding db : docMembers) {
            String fieldName = BeamNameUtils.toSnakeCase(db.getMember().getMemberName());
            String wireKey = jsonKey(db.getMember());
            Shape target = model.expectShape(db.getMember().getTarget());
            if (target instanceof EnumShape || target instanceof IntEnumShape) {
                String helperName = sp.toSymbol(target).getName().replace("()", "");
                recordFields.add("    " + fieldName + " = decode_" + helperName
                        + "(maps:get(<<\"" + wireKey + "\">>, Decoded, undefined))");
            } else if (target instanceof UnionShape) {
                String helperName = sp.toSymbol(target).getName().replace("()", "");
                recordFields.add("    " + fieldName + " = decode_" + helperName
                        + "(maps:get(<<\"" + wireKey + "\">>, Decoded, undefined))");
            } else if (target instanceof TimestampShape) {
                String decodeHelper = timestampDecodeHelper(
                        httpIndex, db.getMember(), HttpBinding.Location.DOCUMENT);
                recordFields.add("    " + fieldName + " = " + decodeHelper
                        + "(maps:get(<<\"" + wireKey + "\">>, Decoded, undefined))");
            } else {
                recordFields.add("    " + documentDecodeAssignment(fieldName, wireKey, target));
            }
        }

        writer.write("#$L{", inputRecord);
        if (!recordFields.isEmpty()) {
            writer.write(String.join(",\n", recordFields));
        }
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    /** Emits encode_<op>_response/1: takes OutputRecord, returns http_response(). */
    private static void emitResponseEncoder(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        StructureShape output = model.expectShape(op.getOutputShape(), StructureShape.class);
        String outputRecord = recordName(sp.toSymbol(output));
        int successCode = httpIndex.getResponseCode(op);

        List<HttpBinding> respHeaders = httpIndex.getResponseBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> respDoc = httpIndex.getResponseBindings(op, HttpBinding.Location.DOCUMENT);
        List<HttpBinding> respPayload = httpIndex.getResponseBindings(op, HttpBinding.Location.PAYLOAD);

        List<String> patternParts = new ArrayList<>();
        for (HttpBinding b : concat(respHeaders, respDoc, respPayload)) {
            String field = BeamNameUtils.toSnakeCase(b.getMember().getMemberName());
            patternParts.add(field + " = " + toBindingVar(field));
        }
        String pattern = patternParts.isEmpty()
                ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

        writer.write("%% Encode HTTP response for $L.", op.getId());
        writer.write("encode_$L_response(#$L{$L}) ->", opName, outputRecord, pattern);
        writer.indent();

        if (respHeaders.isEmpty()) {
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"application/json\">>}],");
        } else {
            writer.write("ExtraHeaders = lists:filtermap(fun");
            for (HttpBinding hb : respHeaders) {
                String headerName = hb.getLocationName();
                writer.write("    (V) when V =/= undefined -> {true, {<<\"$L\">>, to_binary(V)}};",
                        headerName);
            }
            writer.write("    (_) -> false");
            writer.write("end, [$L]),",
                    respHeaders.stream()
                            .map(hb -> toBindingVar(
                                    BeamNameUtils.toSnakeCase(hb.getMember().getMemberName())))
                            .collect(Collectors.joining(", ")));
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"application/json\">>} | ExtraHeaders],");
        }

        if (!respPayload.isEmpty()) {
            HttpBinding pb = respPayload.get(0);
            String fieldName = BeamNameUtils.toSnakeCase(pb.getMember().getMemberName());
            writer.write("Body = $L,", toBindingVar(fieldName));
        } else if (!respDoc.isEmpty()) {
            writer.write("BodyMap = maps:filter(fun(_, V) -> V =/= undefined end, #{");
            for (int i = 0; i < respDoc.size(); i++) {
                HttpBinding db = respDoc.get(i);
                String fieldName = BeamNameUtils.toSnakeCase(db.getMember().getMemberName());
                String wireKey = jsonKey(db.getMember());
                String comma = i < respDoc.size() - 1 ? "," : "";
                Shape target = model.expectShape(db.getMember().getTarget());
                if (target instanceof EnumShape || target instanceof IntEnumShape) {
                    String helperName = sp.toSymbol(target).getName().replace("()", "");
                    writer.write("    <<\"$L\">> => encode_$L($L)$L",
                            wireKey, helperName, toBindingVar(fieldName), comma);
                } else if (target instanceof UnionShape) {
                    String helperName = sp.toSymbol(target).getName().replace("()", "");
                    writer.write("    <<\"$L\">> => encode_$L($L)$L",
                            wireKey, helperName, toBindingVar(fieldName), comma);
                } else if (target instanceof TimestampShape) {
                    String encodeHelper = timestampEncodeHelper(
                            httpIndex, db.getMember(), HttpBinding.Location.DOCUMENT);
                    writer.write("    <<\"$L\">> => $L($L)$L",
                            wireKey, encodeHelper, toBindingVar(fieldName), comma);
                } else {
                    writer.write("    <<\"$L\">> => $L$L", wireKey, toBindingVar(fieldName), comma);
                }
            }
            writer.write("}),");
            writer.write("Body = jsone:encode(BodyMap),");
        } else {
            writer.write("Body = <<>>,");
        }

        writer.write("#http_response{");
        writer.write("    status = $L,", successCode);
        writer.write("    headers = Headers,");
        writer.write("    body = Body");
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    /** Emits encode_<error>_response/1 for each operation error record. */
    private static void emitErrorResponseEncoders(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            SymbolProvider sp,
            Set<ShapeId> emitted) {

        for (ShapeId errorId : op.getErrors()) {
            if (!emitted.add(errorId)) {
                continue;
            }
            StructureShape errShape = model.expectShape(errorId, StructureShape.class);
            String recName = recordName(sp.toSymbol(errShape));
            int status = errShape.hasTrait(HttpErrorTrait.class)
                    ? errShape.expectTrait(HttpErrorTrait.class).getCode()
                    : 500;

            List<String> patternParts = errShape.members().stream()
                    .filter(m -> !m.getMemberName().equals("__beam_error_kind"))
                    .map(m -> {
                        String field = BeamNameUtils.toSnakeCase(m.getMemberName());
                        return field + " = " + toBindingVar(field);
                    })
                    .collect(Collectors.toList());

            String pattern = patternParts.isEmpty()
                    ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

            writer.write("%% Encode HTTP error response for $L.", errorId);
            writer.write("encode_$L_response(#$L{$L}) ->", recName, recName, pattern);
            writer.indent();
            writer.write("BodyMap = #{");
            writer.write("    <<\"__type\">> => <<\"$L\">>", errorId.getName());
            for (MemberShape m : errShape.members()) {
                if (m.getMemberName().equals("__beam_error_kind")) {
                    continue;
                }
                String field = BeamNameUtils.toSnakeCase(m.getMemberName());
                writer.write("    , <<\"$L\">> => $L", m.getMemberName(), toBindingVar(field));
            }
            writer.write("},");
            writer.write("Body = jsone:encode(BodyMap),");
            writer.write("#http_response{");
            writer.write("    status = $L,", status);
            writer.write("    headers = [{<<\"Content-Type\">>, <<\"application/json\">>}],");
            writer.write("    body = Body");
            writer.write("}.");
            writer.dedent();
            writer.write("");
        }
    }

    /** Emits decode_<op>_response/1 for one operation. */
    private static void emitDecoder(
            ErlangWriter writer,
            Model model,
            ServiceShape service,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp,
            BeamErlangLayout layout) {

        String opName = sp.toSymbol(op).getName();
        StructureShape output = model.expectShape(op.getOutputShape(), StructureShape.class);
        String outputRecord = recordName(sp.toSymbol(output));
        int successCode = httpIndex.getResponseCode(op);

        List<HttpBinding> respHeaders = httpIndex.getResponseBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> respDoc = httpIndex.getResponseBindings(op, HttpBinding.Location.DOCUMENT);
        List<HttpBinding> respPayload = httpIndex.getResponseBindings(op, HttpBinding.Location.PAYLOAD);
        List<HttpBinding> respCode = httpIndex.getResponseBindings(op, HttpBinding.Location.RESPONSE_CODE);

        writer.write("%% Decode HTTP response for $L.", op.getId());
        if (!respCode.isEmpty()) {
            writer.write(
                    "decode_$L_response(#http_response{status = HttpStatus, headers = _Headers, body = Body})"
                            + " when HttpStatus >= 200, HttpStatus < 300 ->",
                    opName);
        } else {
            writer.write("decode_$L_response(#http_response{status = $L, headers = _Headers, body = Body}) ->",
                    opName, successCode);
        }
        writer.indent();

        if (!respDoc.isEmpty() || !respPayload.isEmpty()) {
            writer.write("Decoded = case Body of");
            writer.indent();
            writer.write("<<>> -> #{};");
            writer.write("_ ->");
            writer.indent();
            writer.write("case jsone:try_decode(Body) of");
            writer.indent();
            writer.write("{ok, Val, _} -> Val;");
            writer.write("{error, _} -> #{}");
            writer.dedent();
            writer.write("end");
            writer.dedent();
            writer.dedent();
            writer.write("end,");
        }

        for (HttpBinding hb : respHeaders) {
            String fieldName = BeamNameUtils.toSnakeCase(hb.getMember().getMemberName());
            String bindingVar = toBindingVar(fieldName);
            String headerName = hb.getLocationName();
            writer.write("$L = proplists:get_value(<<\"$L\">>, _Headers, undefined),",
                    bindingVar, headerName);
        }

        List<String> recordFields = new ArrayList<>();
        for (HttpBinding hb : respHeaders) {
            String fieldName = BeamNameUtils.toSnakeCase(hb.getMember().getMemberName());
            String bindingVar = toBindingVar(fieldName);
            recordFields.add("    " + fieldName + " = " + bindingVar);
        }
        for (HttpBinding db : respDoc) {
            String fieldName = BeamNameUtils.toSnakeCase(db.getMember().getMemberName());
            String wireKey = jsonKey(db.getMember());
            Shape target = model.expectShape(db.getMember().getTarget());
            if (target instanceof EnumShape || target instanceof IntEnumShape) {
                String helperName = sp.toSymbol(target).getName().replace("()", "");
                recordFields.add("    " + fieldName + " = decode_" + helperName
                        + "(maps:get(<<\"" + wireKey + "\">>, Decoded, undefined))");
            } else if (target instanceof UnionShape) {
                String helperName = sp.toSymbol(target).getName().replace("()", "");
                recordFields.add("    " + fieldName + " = decode_" + helperName
                        + "(maps:get(<<\"" + wireKey + "\">>, Decoded, undefined))");
            } else if (target instanceof TimestampShape) {
                String decodeHelper = timestampDecodeHelper(
                        httpIndex, db.getMember(), HttpBinding.Location.DOCUMENT);
                recordFields.add("    " + fieldName + " = " + decodeHelper
                        + "(maps:get(<<\"" + wireKey + "\">>, Decoded, undefined))");
            } else {
                recordFields.add("    " + documentDecodeAssignment(fieldName, wireKey, target));
            }
        }
        for (HttpBinding pb : respPayload) {
            String fieldName = BeamNameUtils.toSnakeCase(pb.getMember().getMemberName());
            recordFields.add("    " + fieldName + " = Body");
        }
        for (HttpBinding rcb : respCode) {
            String fieldName = BeamNameUtils.toSnakeCase(rcb.getMember().getMemberName());
            recordFields.add("    " + fieldName + " = HttpStatus");
        }
        writer.write("{ok, #$L{", outputRecord);
        if (!recordFields.isEmpty()) {
            writer.write(String.join(",\n", recordFields));
        }
        writer.write("}};");

        writer.dedent();
        writer.write(
                "decode_$L_response(#http_response{status = Status, headers = RespHeaders, body = Body}) ->",
                opName);
        writer.indent();
        writer.write("decode_$L_response_error(Status, RespHeaders, Body).", opName);
        writer.dedent();
        writer.write("");
    }

    private static void emitErrorDispatch(
            ErlangWriter writer,
            Model model,
            ServiceShape service,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        List<ShapeId> errors = new ArrayList<>();
        errors.addAll(op.getErrors());

        writer.write("%% Error dispatch for $L.", op.getId());
        for (ShapeId errorId : errors) {
            StructureShape errShape = model.expectShape(errorId, StructureShape.class);
            String recName = recordName(sp.toSymbol(errShape));
            int httpStatus = errShape.hasTrait(HttpErrorTrait.class)
                    ? errShape.expectTrait(HttpErrorTrait.class).getCode()
                    : -1;
            if (httpStatus <= 0) {
                continue;
            }
            writer.write("decode_$L_response_error($L, _Hdrs, Body) ->", opName, httpStatus);
            writer.indent();
            writer.write("Decoded = decode_json_body(Body),");
            List<String> fields = buildErrorFields(model, errShape, sp);
            writer.write("{error, #$L{$L}};", recName,
                    fields.isEmpty() ? "" : "\n    " + String.join(",\n    ", fields) + "\n");
            writer.dedent();
        }

        boolean hasTypeDiscriminated = errors.stream().anyMatch(e ->
                !model.expectShape(e, StructureShape.class).hasTrait(HttpErrorTrait.class));

        if (hasTypeDiscriminated) {
            writer.write("decode_$L_response_error(Status, _Hdrs, Body) when Status >= 400 ->", opName);
            writer.indent();
            writer.write("Decoded = decode_json_body(Body),");
            writer.write("ErrorType = maps:get(<<\"__type\">>, Decoded, undefined),");
            writer.write("case ErrorType of");
            writer.indent();
            for (ShapeId errorId : errors) {
                StructureShape errShape = model.expectShape(errorId, StructureShape.class);
                if (errShape.hasTrait(HttpErrorTrait.class)) {
                    continue;
                }
                String recName = recordName(sp.toSymbol(errShape));
                String localName = errorId.getName();
                List<String> fields = buildErrorFields(model, errShape, sp);
                writer.write("<<\"$L\">> ->", localName);
                writer.indent();
                writer.write("{error, #$L{$L}};", recName,
                        fields.isEmpty() ? "" : "\n        " + String.join(",\n        ", fields) + "\n    ");
                writer.dedent();
            }
            writer.write("_ ->");
            writer.indent();
            writer.write("{error, {unknown_error, Status, Body}}");
            writer.dedent();
            writer.dedent();
            writer.write("end.");
            writer.dedent();
            writer.write("");
        } else {
            writer.write("decode_$L_response_error(Status, _Hdrs, Body) ->", opName);
            writer.indent();
            writer.write("{error, {unknown_error, Status, Body}}.");
            writer.dedent();
            writer.write("");
        }
    }

    private static List<String> buildErrorFields(Model model, StructureShape errShape, SymbolProvider sp) {
        List<String> fields = new ArrayList<>();
        for (MemberShape member : errShape.members()) {
            if (member.getMemberName().equals("__beam_error_kind")) {
                continue;
            }
            String field = BeamNameUtils.toSnakeCase(member.getMemberName());
            String jsonKey = member.getMemberName();
            fields.add(field + " = maps:get(<<\"" + jsonKey + "\">>, Decoded, undefined)");
        }
        return fields;
    }

    /** Emits private decode_<enum>/1 and encode_<enum>/1 helpers for all reachable enum types. */
    private static void emitEnumHelpers(
            ErlangWriter writer, Model model, ServiceShape service, SymbolProvider sp) {

        Set<ShapeId> emitted = new LinkedHashSet<>();
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);

        for (OperationShape op : ErlangTopDown.containedOperationsSorted(model, service)) {
            for (HttpBinding.Location loc : HttpBinding.Location.values()) {
                for (HttpBinding b : httpIndex.getRequestBindings(op, loc)) {
                    collectEnumTarget(model, b.getMember(), emitted);
                }
                for (HttpBinding b : httpIndex.getResponseBindings(op, loc)) {
                    collectEnumTarget(model, b.getMember(), emitted);
                }
            }
        }

        for (ShapeId enumId : emitted) {
            Shape enumShape = model.expectShape(enumId);
            if (enumShape instanceof EnumShape) {
                emitEnumDecodeEncode(writer, (EnumShape) enumShape, sp);
            } else if (enumShape instanceof IntEnumShape) {
                emitIntEnumDecodeEncode(writer, (IntEnumShape) enumShape, sp);
            }
        }
    }

    private static void collectEnumTarget(Model model, MemberShape member, Set<ShapeId> out) {
        Shape target = model.expectShape(member.getTarget());
        if (target instanceof EnumShape || target instanceof IntEnumShape) {
            out.add(target.getId());
        }
    }

    private static void emitUnionHelpers(
            ErlangWriter writer, Model model, ServiceShape service, SymbolProvider sp) {

        Set<ShapeId> emitted = new LinkedHashSet<>();
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);

        for (OperationShape op : ErlangTopDown.containedOperationsSorted(model, service)) {
            for (HttpBinding.Location loc : HttpBinding.Location.values()) {
                for (HttpBinding b : httpIndex.getRequestBindings(op, loc)) {
                    collectUnionTarget(model, b.getMember(), emitted);
                }
                for (HttpBinding b : httpIndex.getResponseBindings(op, loc)) {
                    collectUnionTarget(model, b.getMember(), emitted);
                }
            }
        }

        for (ShapeId unionId : emitted) {
            UnionShape union = model.expectShape(unionId, UnionShape.class);
            emitUnionDecodeEncode(writer, union, sp);
        }
    }

    private static void collectUnionTarget(Model model, MemberShape member, Set<ShapeId> out) {
        Shape target = model.expectShape(member.getTarget());
        if (target instanceof UnionShape) {
            out.add(target.getId());
        }
    }

    private static void emitUnionDecodeEncode(ErlangWriter writer, UnionShape shape, SymbolProvider sp) {
        String helperName = sp.toSymbol(shape).getName().replace("()", "");
        writer.write("%% Union helpers for $L", shape.getId());
        writer.write("decode_$L(#{} = Map) ->", helperName);
        writer.indent();
        writer.write("case maps:to_list(Map) of");
        writer.indent();
        for (MemberShape m : shape.members()) {
            String wireKey = m.getMemberName();
            String tag = unionTagForMember(sp, m);
            writer.write("[{<<\"$L\">>, V}] -> {$L, V};", wireKey, tag);
        }
        writer.write("[{K, _V}] -> {unknown, K};");
        writer.write("_ -> undefined");
        writer.dedent();
        writer.write("end;");
        writer.dedent();
        writer.write("decode_$L(undefined) -> undefined;", helperName);
        writer.write("decode_$L(null) -> undefined.", helperName);
        writer.write("");

        for (MemberShape m : shape.members()) {
            String wireKey = m.getMemberName();
            String tag = unionTagForMember(sp, m);
            writer.write("encode_$L({$L, V}) -> #{<<\"$L\">> => V};", helperName, tag, wireKey);
        }
        writer.write("encode_$L({unknown, K}) when is_binary(K) -> #{K => null};", helperName);
        writer.write("encode_$L(undefined) -> undefined.", helperName);
        writer.write("");
    }

    private static String unionTagForMember(SymbolProvider sp, MemberShape member) {
        return sp.toSymbol(member).getProperty("unionTag", String.class).orElseThrow();
    }

    private static void emitEnumDecodeEncode(ErlangWriter writer, EnumShape shape, SymbolProvider sp) {
        String helperName = sp.toSymbol(shape).getName().replace("()", "");
        writer.write("%% Enum helpers for $L", shape.getId());
        for (MemberShape m : shape.members()) {
            String wireValue = m.getTrait(EnumValueTrait.class)
                    .flatMap(EnumValueTrait::getStringValue)
                    .orElse(m.getMemberName());
            String atom = enumAtomForMember(sp, shape, m.getMemberName());
            writer.write("decode_$L(<<\"$L\">>) -> $L;", helperName, wireValue, atom);
        }
        writer.write("decode_$L(V) when is_binary(V) -> {unknown, V};", helperName);
        writer.write("decode_$L(null) -> undefined;", helperName);
        writer.write("decode_$L(undefined) -> undefined.", helperName);
        writer.write("");
        for (MemberShape m : shape.members()) {
            String wireValue = m.getTrait(EnumValueTrait.class)
                    .flatMap(EnumValueTrait::getStringValue)
                    .orElse(m.getMemberName());
            String atom = enumAtomForMember(sp, shape, m.getMemberName());
            writer.write("encode_$L($L) -> <<\"$L\">>;", helperName, atom, wireValue);
        }
        writer.write("encode_$L({unknown, V}) when is_binary(V) -> V;", helperName);
        writer.write("encode_$L(undefined) -> undefined.", helperName);
        writer.write("");
    }

    private static void emitIntEnumDecodeEncode(ErlangWriter writer, IntEnumShape shape, SymbolProvider sp) {
        String helperName = sp.toSymbol(shape).getName().replace("()", "");
        writer.write("%% IntEnum helpers for $L", shape.getId());
        for (MemberShape m : shape.members()) {
            int wireValue = m.expectTrait(EnumValueTrait.class).expectIntValue();
            String atom = enumAtomForMember(sp, shape, m.getMemberName());
            writer.write("decode_$L($L) -> $L;", helperName, wireValue, atom);
        }
        writer.write("decode_$L(V) when is_integer(V) -> {unknown, V};", helperName);
        writer.write("decode_$L(null) -> undefined;", helperName);
        writer.write("decode_$L(undefined) -> undefined.", helperName);
        writer.write("");
        for (MemberShape m : shape.members()) {
            int wireValue = m.expectTrait(EnumValueTrait.class).expectIntValue();
            String atom = enumAtomForMember(sp, shape, m.getMemberName());
            writer.write("encode_$L($L) -> $L;", helperName, atom, wireValue);
        }
        writer.write("encode_$L({unknown, V}) when is_integer(V) -> V;", helperName);
        writer.write("encode_$L(undefined) -> undefined.", helperName);
        writer.write("");
    }

    private static String enumAtomForMember(SymbolProvider sp, Shape enumShape, String memberName) {
        @SuppressWarnings("unchecked")
        Map<String, String> byMember = sp.toSymbol(enumShape)
                .getProperty("enumAtomByMember", Map.class)
                .orElseThrow();
        return byMember.get(memberName);
    }

    /** Emits private helper functions used across all codecs. */
    private static void emitHelpers(ErlangWriter writer) {
        writer.write("%% -- Private helpers --");
        writer.write("");
        writer.write("to_binary(V) when is_binary(V) -> V;");
        writer.write("to_binary(V) when is_list(V) -> list_to_binary(V);");
        writer.write("to_binary(V) when is_integer(V) -> integer_to_binary(V);");
        writer.write("to_binary(V) when is_float(V) -> float_to_binary(V);");
        writer.write("to_binary(true) -> <<\"true\">>;");
        writer.write("to_binary(false) -> <<\"false\">>;");
        writer.write("to_binary(V) when is_atom(V) -> atom_to_binary(V, utf8).");
        writer.write("");
        writer.write("encode_query_value(V) when is_boolean(V) ->");
        writer.write("    atom_to_binary(V, utf8);");
        writer.write("encode_query_value(V) when is_integer(V) ->");
        writer.write("    integer_to_binary(V);");
        writer.write("encode_query_value(V) when is_float(V) ->");
        writer.write("    float_to_binary(V);");
        writer.write("encode_query_value(V) when is_binary(V) ->");
        writer.write("    V;");
        writer.write("encode_query_value(V) when is_atom(V) ->");
        writer.write("    atom_to_binary(V, utf8).");
        writer.write("");
        writer.write("uri_encode(Value) ->");
        writer.write("    uri_string:quote(Value).");
        writer.write("");
        writer.write("uri_decode(Value) when is_binary(Value) ->");
        writer.write("    uri_string:unquote(Value);");
        writer.write("uri_decode(undefined) ->");
        writer.write("    undefined.");
        writer.write("");
        writer.write("decode_query_param(undefined) ->");
        writer.write("    undefined;");
        writer.write("decode_query_param(<<\"true\">>) ->");
        writer.write("    true;");
        writer.write("decode_query_param(<<\"false\">>) ->");
        writer.write("    false;");
        writer.write("decode_query_param(V) when is_binary(V) ->");
        writer.write("    V.");
        writer.write("");
        writer.write("decode_json_body(<<>>) -> #{};");
        writer.write("decode_json_body(Body) ->");
        writer.write("    case jsone:try_decode(Body) of");
        writer.write("        {ok, V, _} when is_map(V) -> V;");
        writer.write("        _ -> #{}");
        writer.write("    end.");
        writer.write("");
        writer.write("decode_sparse_list(undefined) -> undefined;");
        writer.write("decode_sparse_list(List) when is_list(List) ->");
        writer.write("    [case V of null -> undefined; _ -> V end || V <- List].");
        writer.write("");
        writer.write("decode_list(undefined) -> undefined;");
        writer.write("decode_list(List) when is_list(List) ->");
        writer.write("    [V || V <- List, V =/= null].");
        writer.write("");
        writer.write("decode_sparse_map(undefined) -> undefined;");
        writer.write("decode_sparse_map(Map) when is_map(Map) ->");
        writer.write("    maps:map(fun(_K, null) -> undefined; (_K, V) -> V end, Map).");
        writer.write("");
        writer.write("encode_sparse_list(undefined) -> null;");
        writer.write("encode_sparse_list(List) when is_list(List) ->");
        writer.write("    [case V of undefined -> null; _ -> V end || V <- List].");
        writer.write("");
        writer.write("encode_sparse_map(undefined) -> null;");
        writer.write("encode_sparse_map(Map) when is_map(Map) ->");
        writer.write("    maps:map(fun(_K, undefined) -> null; (_K, V) -> V end, Map).");
        writer.write("");
        writer.write("%% Timestamp helpers");
        writer.write("%% Erlang timestamp() is {MegaSecs, Secs, MicroSecs}.");
        writer.write("encode_timestamp_epoch_seconds({Mega, Secs, _Micro}) ->");
        writer.write("    Mega * 1000000 + Secs;");
        writer.write("encode_timestamp_epoch_seconds(undefined) -> undefined.");
        writer.write("");
        writer.write("encode_timestamp_date_time({Mega, Secs, _Micro}) ->");
        writer.write("    EpochSecs = Mega * 1000000 + Secs,");
        writer.write("    {{Y, Mo, D}, {H, Mi, S}} = calendar:gregorian_seconds_to_datetime(");
        writer.write("        EpochSecs + 62167219200),");
        writer.write("    iolist_to_binary(io_lib:format(");
        writer.write("        \"~4..0B-~2..0B-~2..0BT~2..0B:~2..0B:~2..0BZ\",");
        writer.write("        [Y, Mo, D, H, Mi, S]));");
        writer.write("encode_timestamp_date_time(undefined) -> undefined.");
        writer.write("");
        writer.write("decode_timestamp_epoch_seconds(null) -> undefined;");
        writer.write("decode_timestamp_epoch_seconds(undefined) -> undefined;");
        writer.write("decode_timestamp_epoch_seconds(V) when is_number(V) ->");
        writer.write("    Mega = V div 1000000,");
        writer.write("    Secs = V rem 1000000,");
        writer.write("    {Mega, Secs, 0}.");
        writer.write("");
        writer.write("decode_timestamp_date_time(null) -> undefined;");
        writer.write("decode_timestamp_date_time(undefined) -> undefined;");
        writer.write("decode_timestamp_date_time(V) when is_binary(V) ->");
        writer.write("    %% Minimal ISO 8601 parse: YYYY-MM-DDTHH:MM:SSZ");
        writer.write("    try");
        writer.write("        <<Y:4/binary, \"-\", Mo:2/binary, \"-\", D:2/binary, \"T\",");
        writer.write("          H:2/binary, \":\", Mi:2/binary, \":\", S:2/binary, _/binary>> = V,");
        writer.write("        Dt = {{binary_to_integer(Y), binary_to_integer(Mo), binary_to_integer(D)},");
        writer.write("              {binary_to_integer(H), binary_to_integer(Mi), binary_to_integer(S)}},");
        writer.write("        GregorianSecs = calendar:datetime_to_gregorian_seconds(Dt),");
        writer.write("        EpochSecs = GregorianSecs - 62167219200,");
        writer.write("        Mega = EpochSecs div 1000000,");
        writer.write("        {Mega, EpochSecs rem 1000000, 0}");
        writer.write("    catch _:_ -> undefined");
        writer.write("    end.");
        writer.write("");
    }

    /** Record tag for #-record{} syntax; symbol names carry a trailing {@code ()} type suffix. */
    private static String recordName(Symbol symbol) {
        return symbol.getName().replace("()", "");
    }

    private static List<String> buildPatternParts(
            List<HttpBinding> labels,
            List<HttpBinding> queries,
            List<HttpBinding> queryParams,
            List<HttpBinding> headers,
            List<HttpBinding> docMembers,
            SymbolProvider sp,
            Model model) {
        List<String> parts = new ArrayList<>();
        for (HttpBinding b : concat(labels, queries, queryParams, headers, docMembers)) {
            String field = BeamNameUtils.toSnakeCase(b.getMember().getMemberName());
            parts.add(field + " = " + toBindingVar(field));
        }
        return parts;
    }

    /** Erlang variable for a snake_case record field (atoms are not variables). */
    private static String toBindingVar(String snakeField) {
        if (snakeField.isEmpty()) {
            return snakeField;
        }
        return Character.toUpperCase(snakeField.charAt(0)) + snakeField.substring(1);
    }

    private static String documentDecodeAssignment(String fieldName, String jsonKey, Shape target) {
        String raw = "maps:get(<<\"" + jsonKey + "\">>, Decoded, undefined)";
        if (target instanceof ListShape) {
            String helper = target.hasTrait(SparseTrait.class) ? "decode_sparse_list" : "decode_list";
            return fieldName + " = " + helper + "(" + raw + ")";
        }
        if (target instanceof MapShape) {
            if (target.hasTrait(SparseTrait.class)) {
                return fieldName + " = decode_sparse_map(" + raw + ")";
            }
            return fieldName + " = " + raw;
        }
        return fieldName + " = " + raw;
    }

    private static String jsonKey(MemberShape member) {
        return member.getTrait(JsonNameTrait.class)
                .map(JsonNameTrait::getValue)
                .orElse(member.getMemberName());
    }

    private static String timestampEncodeHelper(
            HttpBindingIndex httpIndex, MemberShape member, HttpBinding.Location location) {
        TimestampFormatTrait.Format fmt = httpIndex.determineTimestampFormat(
                member, location, TimestampFormatTrait.Format.DATE_TIME);
        return fmt == TimestampFormatTrait.Format.EPOCH_SECONDS
                ? "encode_timestamp_epoch_seconds"
                : "encode_timestamp_date_time";
    }

    private static String timestampDecodeHelper(
            HttpBindingIndex httpIndex, MemberShape member, HttpBinding.Location location) {
        TimestampFormatTrait.Format fmt = httpIndex.determineTimestampFormat(
                member, location, TimestampFormatTrait.Format.DATE_TIME);
        return fmt == TimestampFormatTrait.Format.EPOCH_SECONDS
                ? "decode_timestamp_epoch_seconds"
                : "decode_timestamp_date_time";
    }

    private static String encodeDocumentValue(Shape target, String fieldName) {
        String binding = toBindingVar(fieldName);
        if (target instanceof ListShape && target.hasTrait(SparseTrait.class)) {
            return "encode_sparse_list(" + binding + ")";
        }
        if (target instanceof MapShape && target.hasTrait(SparseTrait.class)) {
            return "encode_sparse_map(" + binding + ")";
        }
        return binding;
    }

    @SafeVarargs
    private static <T> List<T> concat(List<T>... lists) {
        List<T> out = new ArrayList<>();
        for (List<T> l : lists) {
            out.addAll(l);
        }
        return out;
    }

    private static String buildPathExpression(
            String uriTemplate,
            List<HttpBinding> labels,
            SymbolProvider sp,
            Model model) {
        if (labels.isEmpty()) {
            return "<<\"" + uriTemplate + "\">>";
        }
        StringBuilder sb = new StringBuilder("<<");
        int pos = 0;
        while (pos < uriTemplate.length()) {
            int start = uriTemplate.indexOf('{', pos);
            if (start < 0) {
                sb.append("\"").append(uriTemplate.substring(pos)).append("\"");
                break;
            }
            if (start > pos) {
                sb.append("\"").append(uriTemplate, pos, start).append("\", ");
            }
            int end = uriTemplate.indexOf('}', start);
            String labelName = uriTemplate.substring(start + 1, end);
            String fieldName = BeamNameUtils.toSnakeCase(labelName);
            sb.append("(uri_encode(to_binary(").append(toBindingVar(fieldName)).append(")))/binary");
            pos = end + 1;
            if (pos < uriTemplate.length()) {
                sb.append(", ");
            }
        }
        sb.append(">>");
        return sb.toString();
    }
}
