package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamAwsServiceMetadata;
import io.smithy.beam.core.BeamErlangLayout;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.ShapeId;

import java.util.ArrayList;
import java.util.List;

/**
 * Shared AWS JSON RPC codec emitter for Erlang. POST / with X-Amz-Target and JSON body.
 */
final class ErlangAwsJsonRpcEmitter {

    private ErlangAwsJsonRpcEmitter() {}

    static void emitServerCodecModule(
            ErlangContext ctx, ServiceShape service, ShapeId protocol, String contentType, String versionLabel) {
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String serverCodecFile = layout.serverCodecModuleName(protocol) + ".erl";
        String serverCodecModule = layout.serverCodecModuleName(protocol);
        ErlangRuntimeHelpersEmitter.emitIfNeeded(ctx, service);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();
        String eventStreamModule = layout.eventStreamModuleName();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("decode_" + name + "_request/1");
            exports.add("encode_" + name + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(serverCodecFile, writer -> {
            writer.write("%% Server AWS JSON $L codecs for $L (generated).", versionLabel, service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", serverCodecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            ErlangFormat.writeExport(writer, exports);
            writer.write("");

            for (OperationShape op : operations) {
                ErlangAwsJsonIr.writeFunction(writer, ErlangAwsJsonIr.decodeRequest(
                        model, op, httpIndex, sp, eventStreamModule));
                ErlangAwsJsonIr.writeFunction(writer, ErlangAwsJsonIr.encodeResponse(
                        model, op, httpIndex, sp, contentType, eventStreamModule));
            }

            ErlangAwsJsonIr.writeFunctions(writer, ErlangAwsJsonIr.sharedCodecHelpers(model, service, sp));
        });
    }

    static void emitCodecModule(
            ErlangContext ctx, ServiceShape service, ShapeId protocol, String contentType, String versionLabel) {
        BeamAwsServiceMetadata.from(service).orElseThrow();
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String codecFile = layout.clientCodecModuleName(protocol) + ".erl";
        String codecModule = layout.clientCodecModuleName(protocol);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();
        String targetPrefix = service.getId().getName();
        String eventStreamModule = layout.eventStreamModuleName();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("encode_" + name + "_request/1");
            exports.add("decode_" + name + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(codecFile, writer -> {
            writer.write("%% AWS JSON $L codecs for $L (generated).", versionLabel, service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", codecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            ErlangFormat.writeExport(writer, exports);
            writer.write("");

            for (OperationShape op : operations) {
                ErlangAwsJsonIr.writeFunction(writer, ErlangAwsJsonIr.encodeRequest(
                        model, op, httpIndex, sp, targetPrefix, contentType, eventStreamModule));
                ErlangAwsJsonIr.writeFunction(writer, ErlangAwsJsonIr.decodeResponse(
                        model, op, httpIndex, sp, eventStreamModule));
            }

            for (OperationShape op : operations) {
                ErlangAwsJsonIr.writeFunction(writer, ErlangAwsJsonIr.errorDispatch(model, op, sp));
            }

            ErlangAwsJsonIr.writeFunctions(writer, ErlangAwsJsonIr.sharedCodecHelpers(model, service, sp));
        });
    }
}
