package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamAwsQueryFormEncoder;
import io.smithy.beam.core.BeamAwsServiceMetadata;
import io.smithy.beam.core.BeamProtocolIds;
import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.core.BeamNameUtils;
import io.smithy.beam.core.BeamXmlBindingIndex;
import io.smithy.beam.core.BeamXmlDecoder;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.ListShape;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.StructureShape;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

/**
 * AWS Query protocol codec emitter for Erlang clients. POST / with form-urlencoded body.
 */
public final class ErlangAwsQueryEmitter {

    private static final String CONTENT_TYPE = "application/x-www-form-urlencoded";

    private ErlangAwsQueryEmitter() {}

    static void emitCodecModule(ErlangContext ctx, ServiceShape service) {
        emitCodecModule(ctx, service, BeamProtocolIds.AWS_QUERY);
    }

    static void emitCodecModule(ErlangContext ctx, ServiceShape service, ShapeId protocolTraitId) {
        boolean ec2Query = BeamProtocolIds.EC2_QUERY.equals(protocolTraitId);
        BeamAwsServiceMetadata.from(service).orElseThrow();
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String codecFile = layout.clientCodecModuleName(protocolTraitId) + ".erl";
        String codecModule = layout.clientCodecModuleName(protocolTraitId);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("encode_" + name + "_request/1");
            exports.add("decode_" + name + "_response/1");
        }

        Set<StructureShape> inputShapes = new LinkedHashSet<>();
        for (OperationShape op : operations) {
            inputShapes.add(model.expectShape(op.getInputShape(), StructureShape.class));
        }

        ctx.writerDelegator().useFileWriter(codecFile, writer -> {
            writer.write("%% AWS Query codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", codecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            ErlangFormat.writeExport(writer, exports);
            writer.write("");

            for (OperationShape op : operations) {
                ErlangAwsQueryIr.writeFunction(writer, ErlangAwsQueryIr.encodeRequest(
                        model, service, op, httpIndex, sp));
                ErlangAwsQueryIr.writeFunction(writer, ErlangAwsQueryIr.decodeResponse(
                        model, service, op, sp, ec2Query));
            }

            List<StructureShape> flattenInputs = ErlangAwsQueryIr.inputShapes(model, service);
            for (int i = 0; i < flattenInputs.size(); i++) {
                ErlangAwsQueryIr.writeFunction(writer, ErlangAwsQueryIr.flattenInputClause(
                        model, httpIndex, sp, flattenInputs.get(i), ec2Query, i == flattenInputs.size() - 1));
            }

            ErlangAwsQueryIr.writeFunctions(writer, ErlangAwsQueryIr.queryHelpers(ec2Query));
            ErlangAwsQueryIr.writeFunctions(writer, ErlangAwsQueryIr.xmlHelpers(ec2Query));
        });
    }

    static void emitServerCodecModule(ErlangContext ctx, ServiceShape service) {
        emitServerCodecModule(ctx, service, BeamProtocolIds.AWS_QUERY);
    }

    static void emitServerCodecModule(ErlangContext ctx, ServiceShape service, ShapeId protocolTraitId) {
        boolean ec2Query = BeamProtocolIds.EC2_QUERY.equals(protocolTraitId);
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String serverCodecFile = layout.serverCodecModuleName(protocolTraitId) + ".erl";
        String serverCodecModule = layout.serverCodecModuleName(protocolTraitId);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("decode_" + name + "_request/1");
            exports.add("encode_" + name + "_response/1");
        }

        Set<StructureShape> inputShapes = new LinkedHashSet<>();
        for (OperationShape op : operations) {
            inputShapes.add(model.expectShape(op.getInputShape(), StructureShape.class));
        }

        Optional<String> serviceNamespace = BeamXmlBindingIndex.xmlNamespaceUri(service);

        ctx.writerDelegator().useFileWriter(serverCodecFile, writer -> {
            writer.write("%% Server AWS Query codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", serverCodecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            ErlangFormat.writeExport(writer, exports);
            writer.write("");

            emitServiceXmlNamespace(writer, serviceNamespace);

            for (OperationShape op : operations) {
                ErlangAwsQueryIr.writeFunction(writer, ErlangAwsQueryIr.serverDecodeRequest(
                        model, op, sp, ec2Query));
                ErlangAwsQueryIr.writeFunction(writer, ErlangAwsQueryIr.serverEncodeResponse(
                        model, service, op, sp, ec2Query));
            }

            for (StructureShape input : inputShapes) {
                ErlangAwsQueryIr.writeFunction(writer, ErlangAwsQueryIr.parseInputFromForm(
                        model, sp, input, ec2Query));
            }

            ErlangAwsQueryIr.writeFunctions(writer, ErlangAwsQueryIr.serverQueryDecodeHelpers(ec2Query));
            ErlangAwsQueryIr.writeFunctions(writer, ErlangAwsQueryIr.serverXmlEncodeHelpers(ec2Query));
        });
    }

    static void emitServerRequestDecoder(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            SymbolProvider sp,
            boolean ec2Query) {

        String opName = sp.toSymbol(op).getName();
        StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
        String inputRecord = recordName(sp.toSymbol(input));
        String inputType = sp.toSymbol(input).getName();

        writer.write("%% Decode AWS Query server request for $L.", op.getId());
        ErlangFormat.writeSpec(writer, "decode_" + opName + "_request(#http_request{}) -> " + inputType);
        writer.write("decode_$L_request(#http_request{body = Body}) ->", opName);
        writer.indent();
        writer.write("Params = parse_query_params(Body),");
        writer.write("parse_$L_input(Params).", inputRecord);
        writer.dedent();
        writer.write("");
    }

    static void emitServerResponseEncoder(
            ErlangWriter writer,
            Model model,
            ServiceShape service,
            OperationShape op,
            SymbolProvider sp,
            boolean ec2Query) {

        String opName = sp.toSymbol(op).getName();
        StructureShape output = model.expectShape(op.getOutputShape(), StructureShape.class);
        String outputRecord = recordName(sp.toSymbol(output));
        String outputType = sp.toSymbol(output).getName();
        String pattern = inputPattern(sp, output);
        String resultElement = ec2Query
                ? BeamXmlDecoder.ec2QueryResultElementName(op, service)
                : BeamXmlDecoder.queryResultElementName(op, service);
        String responseElement = operationWireName(op, service) + "Response";

        writer.write("%% Encode AWS Query server response for $L.", op.getId());
        ErlangFormat.writeSpec(writer, "encode_" + opName + "_response(" + outputType + ") -> #http_response{}");
        writer.write("encode_$L_response(#$L{$L}) ->", opName, outputRecord, pattern);
        writer.indent();
        writer.write("ResultContent = maps:filter(fun(_, V) -> V =/= undefined end, #{");
        emitOutputMapEntries(writer, model, sp, output);
        writer.write("}),");
        if (ec2Query) {
            writer.write("Body = encode_xml(#{<<\"$L\">> => ResultContent}, xml_namespace()),", resultElement);
        } else {
            writer.write("Body = wrap_aws_query_response(");
            writer.write("    <<\"$L\">>, ResultContent, <<\"$L\">>, xml_namespace()),", resultElement, responseElement);
        }
        writer.write("#http_response{");
        writer.write("    status = 200,");
        writer.write("    headers = [{<<\"Content-Type\">>, <<\"text/xml\">>}],");
        writer.write("    body = Body");
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    static void emitParseInputFromForm(
            ErlangWriter writer,
            Model model,
            SymbolProvider sp,
            StructureShape input,
            boolean ec2Query) {

        String inputRecord = recordName(sp.toSymbol(input));
        List<MemberShape> members = new ArrayList<>(input.members());

        writer.write("parse_$L_input(Params) ->", inputRecord);
        writer.indent();
        writer.write("#$L{", inputRecord);
        for (int i = 0; i < members.size(); i++) {
            MemberShape member = members.get(i);
            String field = memberFieldName(sp, member);
            String wireKey = queryFormKey(member, ec2Query);
            Shape target = model.expectShape(member.getTarget());
            String valueExpr;
            if (target instanceof ListShape) {
                valueExpr = ec2Query
                        ? "form_list_values_ec2(Params, <<\"" + wireKey + "\">>)"
                        : "form_list_values_aws(Params, <<\"" + wireKey + "\">>)";
            } else {
                valueExpr = "form_value(Params, <<\"" + wireKey + "\">>)";
            }
            if (i < members.size() - 1) {
                writer.write("    $L = $L,", field, valueExpr);
            } else {
                writer.write("    $L = $L", field, valueExpr);
            }
        }
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    private static void emitOutputMapEntries(
            ErlangWriter writer,
            Model model,
            SymbolProvider sp,
            StructureShape output) {

        List<MemberShape> members = new ArrayList<>(output.members());
        for (int i = 0; i < members.size(); i++) {
            MemberShape member = members.get(i);
            String field = memberFieldName(sp, member);
            String element = BeamXmlDecoder.memberElementName(member);
            if (i < members.size() - 1) {
                writer.write("    <<\"$L\">> => $L,", element, toBindingVar(field));
            } else {
                writer.write("    <<\"$L\">> => $L", element, toBindingVar(field));
            }
        }
    }

    private static void emitServiceXmlNamespace(ErlangWriter writer, Optional<String> namespaceUri) {
        if (namespaceUri.isPresent()) {
            writer.write("xml_namespace() -> #{uri => <<\"$L\">>}.", namespaceUri.get());
        } else {
            writer.write("xml_namespace() -> #{}.");
        }
        writer.write("");
    }

    private static String operationWireName(OperationShape operation, ServiceShape service) {
        return operation.getId().getName(service);
    }

    static void emitEncoder(
            ErlangWriter writer,
            Model model,
            ServiceShape service,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
        String inputRecord = recordName(sp.toSymbol(input));
        String inputType = sp.toSymbol(input).getName();
        String action = BeamAwsQueryFormEncoder.operationAction(op, service);
        String version = BeamAwsQueryFormEncoder.serviceVersion(service);

        writer.write("%% Encode AWS Query request for $L.", op.getId());
        ErlangFormat.writeSpec(writer, "encode_" + opName + "_request(" + inputType + ") -> #http_request{}");
        ErlangFormat.writeRecordFunctionHead(
                writer,
                "encode_" + opName + "_request",
                "Input",
                inputRecord,
                inputPatternParts(sp, input));
        writer.indent();
        writer.write("Pairs = [");
        writer.write("    {<<\"Action\">>, <<\"$L\">>},", action);
        writer.write("    {<<\"Version\">>, <<\"$L\">>}", version);
        writer.write("    | flatten_query_input(Input)");
        writer.write("],");
        writer.write("Body = uri_string:compose_query([{K, enc(V)} || {K, V} <- Pairs, V =/= undefined]),");
        writer.write("#http_request{");
        writer.write("    method = <<\"POST\">>,");
        writer.write("    path = <<\"/\">>,");
        writer.write("    query = #{},");
        writer.write("    headers = [{<<\"Content-Type\">>, <<\"$L\">>}],", CONTENT_TYPE);
        writer.write("    body = Body");
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    static void emitFlattenInputClause(
            ErlangWriter writer,
            Model model,
            HttpBindingIndex httpIndex,
            SymbolProvider sp,
            StructureShape input,
            boolean ec2Query,
            boolean lastClause) {

        String inputRecord = recordName(sp.toSymbol(input));
        List<MemberShape> members = documentMembers(httpIndex, input);

        writer.write("flatten_query_input(#$L{", inputRecord);
        for (int i = 0; i < members.size(); i++) {
            MemberShape member = members.get(i);
            String field = memberFieldName(sp, member);
            if (i < members.size() - 1) {
                writer.write("    $L = $L,", field, toBindingVar(field));
            } else {
                writer.write("    $L = $L", field, toBindingVar(field));
            }
        }
        writer.write("}) ->");
        writer.indent();
        String clauseTerminator = lastClause ? "." : ";";
        if (members.isEmpty()) {
            writer.write("[]$L", clauseTerminator);
        } else {
            writer.write("lists:append([");
            for (int i = 0; i < members.size(); i++) {
                MemberShape member = members.get(i);
                String field = memberFieldName(sp, member);
                String wireKey = queryFormKey(member, ec2Query);
                if (i < members.size() - 1) {
                    writer.write("    flatten_member(<<\"$L\">>, $L),", wireKey, toBindingVar(field));
                } else {
                    writer.write("    flatten_member(<<\"$L\">>, $L)", wireKey, toBindingVar(field));
                }
            }
            writer.write("])$L", clauseTerminator);
        }
        writer.dedent();
        writer.write("");
    }

    static void emitDecoder(
            ErlangWriter writer,
            Model model,
            ServiceShape service,
            OperationShape op,
            SymbolProvider sp,
            boolean ec2Query) {

        String opName = sp.toSymbol(op).getName();
        StructureShape output = model.expectShape(op.getOutputShape(), StructureShape.class);
        String outputRecord = recordName(sp.toSymbol(output));
        String outputType = sp.toSymbol(output).getName();
        String resultElement = ec2Query
                ? BeamXmlDecoder.ec2QueryResultElementName(op, service)
                : BeamXmlDecoder.queryResultElementName(op, service);

        writer.write("%% Decode AWS Query response for $L.", op.getId());
        ErlangFormat.writeSpec(
                writer,
                "decode_" + opName + "_response(#http_response{}) -> {'ok', " + outputType + "} | {'error', term()}");
        writer.write("decode_$L_response(#http_response{status = 200, body = Body}) ->", opName);
        writer.indent();
        if (output.members().isEmpty()) {
            writer.write("case unwrap_query_result(Body, <<\"$L\">>) of", resultElement);
            writer.indent();
            writer.write("{ok, _Result} -> {ok, #$L{}};", outputRecord);
            writer.write("{error, {missing_result, _}} -> {ok, #$L{}};", outputRecord);
            writer.write("{error, Reason} -> {error, Reason}");
            writer.dedent();
            writer.write("end;");
        } else {
            writer.write("case unwrap_query_result(Body, <<\"$L\">>) of", resultElement);
            writer.indent();
            writer.write("{ok, Result} ->");
            writer.indent();
            writer.write("{ok, #$L{", outputRecord);
            emitOutputFields(writer, model, sp, output, "Result", ec2Query);
            writer.write("}};");
            writer.dedent();
            writer.write("{error, Reason} ->");
            writer.indent();
            writer.write("{error, Reason}");
            writer.dedent();
            writer.dedent();
            writer.write("end;");
        }
        writer.dedent();
        writer.write("decode_$L_response(#http_response{status = Status, body = Body}) ->", opName);
        writer.indent();
        writer.write("decode_query_error(Status, Body).");
        writer.dedent();
        writer.write("");
    }

    private static void emitOutputFields(
            ErlangWriter writer,
            Model model,
            SymbolProvider sp,
            StructureShape output,
            String resultVar,
            boolean ec2Query) {

        List<String> fields = new ArrayList<>();
        for (MemberShape member : output.members()) {
            String field = memberFieldName(sp, member);
            Shape target = model.expectShape(member.getTarget());
            if (target instanceof ListShape listShape) {
                fields.add("    " + field + " = "
                        + decodeListFieldFromXml(model, member, listShape, resultVar, sp, ec2Query));
            } else if (target instanceof StructureShape nested) {
                String element = BeamXmlDecoder.memberElementName(member);
                String nestedVar = xmlVarForElement(element);
                fields.add("    " + field + " = (case find_element(<<\"" + element + "\">>, element_content("
                        + resultVar + ")) of undefined -> undefined; " + nestedVar + " -> "
                        + decodeStructureFromXml(model, nested, nestedVar, sp, ec2Query) + " end)");
            } else {
                fields.add("    " + field + " = xml_child_text(" + resultVar + ", <<\""
                        + BeamXmlDecoder.memberElementName(member) + "\">>)");
            }
        }
        if (!fields.isEmpty()) {
            writer.write(String.join(",\n", fields));
        }
    }

    private static String decodeStructureFromXml(
            Model model,
            StructureShape structure,
            String xmlVar,
            SymbolProvider sp,
            boolean ec2Query) {
        List<String> fields = new ArrayList<>();
        String recordTag = recordName(sp.toSymbol(structure));
        for (MemberShape member : structure.members()) {
            String field = memberFieldName(sp, member);
            Shape target = model.expectShape(member.getTarget());
            if (target instanceof ListShape listShape) {
                fields.add(field + " = "
                        + decodeListFieldFromXml(model, member, listShape, xmlVar, sp, ec2Query));
            } else if (target instanceof StructureShape nested) {
                String element = BeamXmlDecoder.memberElementName(member);
                String nestedVar = xmlVarForElement(element);
                fields.add(field + " = (case find_element(<<\"" + element + "\">>, element_content(" + xmlVar
                        + ")) of undefined -> undefined; " + nestedVar + " -> "
                        + decodeStructureFromXml(model, nested, nestedVar, sp, ec2Query) + " end)");
            } else {
                fields.add(field + " = xml_child_text(" + xmlVar + ", <<\""
                        + BeamXmlDecoder.memberElementName(member) + "\">>)");
            }
        }
        if (fields.isEmpty()) {
            return "#" + recordTag + "{}";
        }
        return "#" + recordTag + "{" + String.join(", ", fields) + "}";
    }

    private static String decodeListFieldFromXml(
            Model model,
            MemberShape member,
            ListShape listShape,
            String xmlVar,
            SymbolProvider sp,
            boolean ec2Query) {
        String element = BeamXmlDecoder.memberElementName(member);
        String itemElement = listShape.getMember().hasTrait(software.amazon.smithy.model.traits.XmlNameTrait.class)
                ? BeamXmlDecoder.memberElementName(listShape.getMember())
                : BeamXmlBindingIndex.listItemElementName(member, listShape, model);
        String listNameExpr = "<<\"" + element + "\">>";
        Shape listMember = model.expectShape(listShape.getMember().getTarget());
        if (listMember instanceof StructureShape nested) {
            String itemRecord = decodeStructureFromXml(model, nested, "Item", sp, ec2Query);
            return "xml_child_struct_list(" + xmlVar + ", " + listNameExpr + ", <<\""
                    + itemElement + "\">>, fun(Item) -> " + itemRecord + " end)";
        }
        return "xml_child_list(" + xmlVar + ", " + listNameExpr + ", <<\"" + itemElement + "\">>)";
    }

    private static List<MemberShape> documentMembers(HttpBindingIndex httpIndex, StructureShape structure) {
        return new ArrayList<>(structure.members());
    }

    private static String queryFormKey(MemberShape member, boolean ec2Query) {
        return ec2Query
                ? BeamAwsQueryFormEncoder.ec2QueryFormKey(member)
                : BeamAwsQueryFormEncoder.awsQueryFormKey(member);
    }

    private static String recordName(software.amazon.smithy.codegen.core.Symbol symbol) {
        return symbol.getName().replace("()", "");
    }

    private static String toBindingVar(String snakeField) {
        return BeamNameUtils.toCamelCaseVariable(snakeField);
    }

    private static String memberFieldName(SymbolProvider sp, MemberShape member) {
        return sp.toSymbol(member).getProperty("fieldName", String.class).orElseThrow();
    }

    private static List<String> inputPatternParts(SymbolProvider sp, StructureShape input) {
        List<String> parts = new ArrayList<>();
        for (MemberShape member : input.members()) {
            String field = memberFieldName(sp, member);
            parts.add(field + " = " + toBindingVar(field));
        }
        return parts;
    }

    private static String inputPattern(SymbolProvider sp, StructureShape input) {
        List<String> parts = inputPatternParts(sp, input);
        return parts.isEmpty() ? "" : "\n    " + String.join(",\n    ", parts) + "\n";
    }

    private static String xmlVarForElement(String element) {
        if (element.isEmpty()) {
            return "NestedXml";
        }
        return Character.toUpperCase(element.charAt(0)) + element.substring(1) + "Xml";
    }
}
