package io.smithy.beam.erlang;

import io.beam.dsl.erlang.Function;
import io.beam.dsl.erlang.Module;
import io.smithy.beam.core.BeamAwsServiceMetadata;
import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.core.BeamProtocolIds;
import io.smithy.beam.core.BeamXmlBindingIndex;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.StructureShape;

final class ErlangAwsQueryDsl {
  private ErlangAwsQueryDsl() {}

  static String clientCodecFileName(
      ErlangContext ctx, ServiceShape service, ShapeId protocolTraitId) {
    return layout(ctx, service).codecModuleName(protocolTraitId) + ".erl";
  }

  static String serverCodecFileName(
      ErlangContext ctx, ServiceShape service, ShapeId protocolTraitId) {
    return layout(ctx, service).codecModuleName(protocolTraitId) + ".erl";
  }

  static Module buildClientCodecModule(
      ErlangContext ctx, ServiceShape service, ShapeId protocolTraitId) {
    boolean ec2Query = BeamProtocolIds.EC2_QUERY.equals(protocolTraitId);
    BeamAwsServiceMetadata.from(service).orElseThrow();
    Model model = ctx.model();
    BeamErlangLayout layout = layout(ctx, service);
    HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
    SymbolProvider sp = ctx.symbolProvider();

    List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
    List<String> exports = new ArrayList<>();
    for (OperationShape op : operations) {
      String name = sp.toSymbol(op).getName();
      exports.add("encode_" + name + "_request/1");
      exports.add("decode_" + name + "_response/1");
    }

    List<Function> functions =
        clientCodecFunctions(model, service, operations, httpIndex, sp, ec2Query);

    return Module.of(
        layout.codecModuleName(protocolTraitId),
        functions,
        List.of(
            "AWS Query codecs for " + service.getId() + " (generated).",
            "DO NOT EDIT -- generated by smithy-beam codegen."),
        null,
        List.of(layout.typesHeaderFile(), layout.runtimeTypesHeaderFile()),
        null,
        exports);
  }

  static Module buildServerCodecModule(
      ErlangContext ctx, ServiceShape service, ShapeId protocolTraitId) {
    boolean ec2Query = BeamProtocolIds.EC2_QUERY.equals(protocolTraitId);
    Model model = ctx.model();
    BeamErlangLayout layout = layout(ctx, service);
    SymbolProvider sp = ctx.symbolProvider();

    List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
    List<String> exports = new ArrayList<>();
    for (OperationShape op : operations) {
      String name = sp.toSymbol(op).getName();
      exports.add("decode_" + name + "_request/1");
      exports.add("encode_" + name + "_response/1");
    }

    Optional<String> serviceNamespace = BeamXmlBindingIndex.xmlNamespaceUri(service);

    List<Function> functions =
        serverCodecFunctions(model, service, operations, sp, serviceNamespace, ec2Query);

    return Module.of(
        layout.codecModuleName(protocolTraitId),
        functions,
        List.of(
            "Server AWS Query codecs for " + service.getId() + " (generated).",
            "DO NOT EDIT -- generated by smithy-beam codegen."),
        null,
        List.of(layout.typesHeaderFile(), layout.runtimeTypesHeaderFile()),
        null,
        exports);
  }

  static void emitClientCodecModule(
      ErlangContext ctx, ServiceShape service, ShapeId protocolTraitId) {
    Module module = buildClientCodecModule(ctx, service, protocolTraitId);
    ErlangCodecEmission.writeModule(
        ctx, clientCodecFileName(ctx, service, protocolTraitId), module);
  }

  static void emitServerCodecModule(
      ErlangContext ctx, ServiceShape service, ShapeId protocolTraitId) {
    Module module = buildServerCodecModule(ctx, service, protocolTraitId);
    ErlangCodecEmission.writeModule(
        ctx, serverCodecFileName(ctx, service, protocolTraitId), module);
  }

  private static BeamErlangLayout layout(ErlangContext ctx, ServiceShape service) {
    return new BeamErlangLayout(ctx.settings(), service.getId().getNamespace(), service);
  }

  static Function encodeRequest(
      Model model,
      ServiceShape service,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp) {
    return ErlangAwsQueryOperationDsl.buildEncodeRequest(model, service, op, httpIndex, sp);
  }

  static Function decodeResponse(
      Model model, ServiceShape service, OperationShape op, SymbolProvider sp, boolean ec2Query) {
    return ErlangAwsQueryOperationDsl.buildDecodeResponse(model, service, op, sp, ec2Query);
  }

  static Function flattenQueryInput(
      Model model,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      List<StructureShape> inputs,
      boolean ec2Query) {
    return ErlangAwsQueryOperationDsl.buildFlattenQueryInput(
        model, httpIndex, sp, inputs, ec2Query);
  }

  static List<Function> queryHelpers(boolean ec2Query) {
    return ErlangAwsQueryHelperDsl.queryHelperFunctions(ec2Query);
  }

  static List<Function> xmlHelpers(boolean ec2Query) {
    return ErlangAwsQueryHelperDsl.xmlHelperFunctions(ec2Query);
  }

  static Function serverDecodeRequest(
      Model model, OperationShape op, SymbolProvider sp, boolean ec2Query) {
    return ErlangAwsQueryOperationDsl.buildServerDecodeRequest(model, op, sp, ec2Query);
  }

  static Function serverEncodeResponse(
      Model model, ServiceShape service, OperationShape op, SymbolProvider sp, boolean ec2Query) {
    return ErlangAwsQueryOperationDsl.buildServerEncodeResponse(model, service, op, sp, ec2Query);
  }

  static Function parseInputFromForm(
      Model model, SymbolProvider sp, StructureShape input, boolean ec2Query) {
    return ErlangAwsQueryOperationDsl.buildParseInputFromForm(model, sp, input, ec2Query);
  }

  static List<Function> serverQueryDecodeHelpers(boolean ec2Query) {
    return ErlangAwsQueryHelperDsl.serverQueryDecodeHelperFunctions(ec2Query);
  }

  static List<Function> serverXmlEncodeHelpers(boolean ec2Query) {
    return ErlangAwsQueryHelperDsl.serverXmlEncodeHelperFunctions(ec2Query);
  }

  static List<StructureShape> inputShapes(Model model, ServiceShape service) {
    Set<StructureShape> shapes = new LinkedHashSet<>();
    for (OperationShape op : ErlangTopDown.containedOperationsSorted(model, service)) {
      shapes.add(model.expectShape(op.getInputShape(), StructureShape.class));
    }
    return new ArrayList<>(shapes);
  }

  static List<Function> clientCodecFunctions(
      Model model,
      ServiceShape service,
      List<OperationShape> operations,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      boolean ec2Query) {
    List<Function> functions = new ArrayList<>();
    for (OperationShape op : operations) {
      functions.add(encodeRequest(model, service, op, httpIndex, sp));
      functions.add(decodeResponse(model, service, op, sp, ec2Query));
    }
    functions.add(flattenQueryInput(model, httpIndex, sp, inputShapes(model, service), ec2Query));
    functions.add(
        ErlangAwsQueryOperationDsl.buildFlattenStructure(
            sp,
            ErlangAwsQueryOperationDsl.nestedQueryStructures(model, inputShapes(model, service)),
            ec2Query));
    functions.addAll(queryHelpers(ec2Query));
    functions.addAll(xmlHelpers(ec2Query));
    return functions;
  }

  static List<Function> serverCodecFunctions(
      Model model,
      ServiceShape service,
      List<OperationShape> operations,
      SymbolProvider sp,
      Optional<String> serviceNamespace,
      boolean ec2Query) {
    List<Function> functions = new ArrayList<>();
    functions.add(ErlangXmlCodecDsl.xmlNamespace(serviceNamespace));
    for (OperationShape op : operations) {
      functions.add(serverDecodeRequest(model, op, sp, ec2Query));
      functions.add(serverEncodeResponse(model, service, op, sp, ec2Query));
    }
    for (StructureShape input : inputShapes(model, service)) {
      functions.add(parseInputFromForm(model, sp, input, ec2Query));
    }
    functions.addAll(serverQueryDecodeHelpers(ec2Query));
    functions.addAll(serverXmlEncodeHelpers(ec2Query));
    return functions;
  }
}
