package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamAwsJson10ProtocolCodegen;
import io.smithy.beam.core.BeamAwsServiceMetadata;
import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.core.BeamNameUtils;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBinding;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.StructureShape;
import software.amazon.smithy.model.traits.HttpErrorTrait;

import java.util.ArrayList;
import java.util.List;

/**
 * AWS JSON 1.0 RPC codec emitter for Erlang. POST / with X-Amz-Target and JSON body.
 */
public final class ErlangAwsJson10Emitter {

    public static final String CONTENT_TYPE = "application/x-amz-json-1.0";

    private ErlangAwsJson10Emitter() {}

    public static void emitCodecModule(ErlangContext ctx, ServiceShape service) {
        BeamAwsServiceMetadata.from(service).orElseThrow();
        Model model = ctx.model();
        ShapeId protocol = BeamAwsJson10ProtocolCodegen.AWS_JSON_1_0;
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String codecFile = layout.clientCodecModuleName(protocol) + ".erl";
        String codecModule = layout.clientCodecModuleName(protocol);
        ErlangRuntimeHelpersEmitter.emitIfNeeded(ctx, service);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();
        String targetPrefix = service.getId().getName();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("encode_" + name + "_request/1");
            exports.add("decode_" + name + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(codecFile, writer -> {
            writer.write("%% AWS JSON 1.0 codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", codecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            writer.write("-export([$L]).", String.join(", ", exports));
            writer.write("");

            for (OperationShape op : operations) {
                emitEncoder(writer, model, op, httpIndex, sp, targetPrefix);
                emitDecoder(writer, model, op, httpIndex, sp);
            }

            for (OperationShape op : operations) {
                emitErrorDispatch(writer, model, op, sp);
            }

            ErlangRestJson1Emitter.emitSharedCodecHelpers(writer, model, service, sp);
        });
    }

    private static void emitEncoder(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp,
            String targetPrefix) {

        String opName = sp.toSymbol(op).getName();
        StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
        String inputRecord = ErlangJsonCodecSupport.recordName(sp.toSymbol(input));
        String inputType = sp.toSymbol(input).getName();
        String pattern = ErlangJsonCodecSupport.inputPattern(input);
        List<software.amazon.smithy.model.shapes.MemberShape> members =
                ErlangJsonCodecSupport.documentMembers(httpIndex, op, input, true);
        String amzTarget = targetPrefix + "." + op.getId().getName();

        writer.write("%% Encode AWS JSON request for $L.", op.getId());
        writer.write("-spec encode_$L_request($L) -> #http_request{}.", opName, inputType);
        writer.write("encode_$L_request(Input = #$L{$L}) ->", opName, inputRecord, pattern);
        writer.indent();
        writer.write("BodyMap = maps:filter(fun(_, V) -> V =/= undefined end, #{");
        ErlangJsonCodecSupport.emitBodyMapEntries(
                writer, model, httpIndex, sp, members, HttpBinding.Location.DOCUMENT);
        writer.write("}),");
        writer.write("Body = jsone:encode(BodyMap),");
        writer.write("#http_request{");
        writer.write("    method = <<\"POST\">>,");
        writer.write("    path = <<\"/\">>,");
        writer.write("    query = #{},");
        writer.write("    headers = [");
        writer.write("        {<<\"Content-Type\">>, <<\"$L\">>},", CONTENT_TYPE);
        writer.write("        {<<\"X-Amz-Target\">>, <<\"$L\">>}", amzTarget);
        writer.write("    ],");
        writer.write("    body = Body");
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    private static void emitDecoder(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        StructureShape output = model.expectShape(op.getOutputShape(), StructureShape.class);
        String outputRecord = ErlangJsonCodecSupport.recordName(sp.toSymbol(output));
        String outputType = sp.toSymbol(output).getName();
        List<software.amazon.smithy.model.shapes.MemberShape> members =
                ErlangJsonCodecSupport.documentMembers(httpIndex, op, output, false);

        writer.write("%% Decode AWS JSON response for $L.", op.getId());
        writer.write("-spec decode_$L_response(#http_response{}) -> {'ok', $L} | {'error', term()}.",
                opName, outputType);
        writer.write("decode_$L_response(#http_response{status = 200, body = Body}) ->", opName);
        writer.indent();
        ErlangJsonCodecSupport.emitDecodeJsonBody(writer);
        writer.write("{ok, #$L{", outputRecord);
        ErlangJsonCodecSupport.emitRecordFieldsFromDecoded(
                writer, model, httpIndex, sp, members, HttpBinding.Location.DOCUMENT);
        writer.write("}};");
        writer.dedent();
        writer.write(
                "decode_$L_response(#http_response{status = Status, headers = RespHeaders, body = Body}) ->",
                opName);
        writer.indent();
        writer.write("decode_$L_response_error(Status, RespHeaders, Body).", opName);
        writer.dedent();
        writer.write("");
    }

    private static void emitErrorDispatch(
            ErlangWriter writer, Model model, OperationShape op, SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        List<ShapeId> errors = new ArrayList<>(op.getErrors());

        writer.write("%% Error dispatch for $L.", op.getId());
        for (ShapeId errorId : errors) {
            StructureShape errShape = model.expectShape(errorId, StructureShape.class);
            String recName = ErlangJsonCodecSupport.recordName(sp.toSymbol(errShape));
            int httpStatus = errShape.hasTrait(HttpErrorTrait.class)
                    ? errShape.expectTrait(HttpErrorTrait.class).getCode()
                    : -1;
            if (httpStatus <= 0) {
                continue;
            }
            writer.write("decode_$L_response_error($L, _Hdrs, Body) ->", opName, httpStatus);
            writer.indent();
            writer.write("Decoded = decode_json_body(Body),");
            List<String> fields = buildErrorFields(errShape);
            writer.write("{error, #$L{$L}};", recName,
                    fields.isEmpty() ? "" : "\n    " + String.join(",\n    ", fields) + "\n");
            writer.dedent();
        }

        boolean hasTypeDiscriminated = errors.stream().anyMatch(e ->
                !model.expectShape(e, StructureShape.class).hasTrait(HttpErrorTrait.class));

        if (hasTypeDiscriminated) {
            writer.write("decode_$L_response_error(Status, _Hdrs, Body) when Status >= 400 ->", opName);
            writer.indent();
            writer.write("Decoded = decode_json_body(Body),");
            writer.write("ErrorType = maps:get(<<\"__type\">>, Decoded, undefined),");
            writer.write("case ErrorType of");
            writer.indent();
            for (ShapeId errorId : errors) {
                StructureShape errShape = model.expectShape(errorId, StructureShape.class);
                if (errShape.hasTrait(HttpErrorTrait.class)) {
                    continue;
                }
                String recName = ErlangJsonCodecSupport.recordName(sp.toSymbol(errShape));
                String localName = errorId.getName();
                List<String> fields = buildErrorFields(errShape);
                writer.write("<<\"$L\">> ->", localName);
                writer.indent();
                writer.write("{error, #$L{$L}};", recName,
                        fields.isEmpty() ? "" : "\n        " + String.join(",\n        ", fields) + "\n    ");
                writer.dedent();
            }
            writer.write("_ ->");
            writer.indent();
            writer.write("{error, {unknown_error, Status, Body}}");
            writer.dedent();
            writer.dedent();
            writer.write("end.");
            writer.dedent();
            writer.write("");
        } else {
            writer.write("decode_$L_response_error(Status, _Hdrs, Body) ->", opName);
            writer.indent();
            writer.write("{error, {unknown_error, Status, Body}}.");
            writer.dedent();
            writer.write("");
        }
    }

    private static List<String> buildErrorFields(StructureShape errShape) {
        List<String> fields = new ArrayList<>();
        for (software.amazon.smithy.model.shapes.MemberShape member : errShape.members()) {
            if (member.getMemberName().equals("__beam_error_kind")) {
                continue;
            }
            String field = BeamNameUtils.toSnakeCase(member.getMemberName());
            String jsonKey = member.getMemberName();
            fields.add(field + " = maps:get(<<\"" + jsonKey + "\">>, Decoded, undefined)");
        }
        return fields;
    }
}
