package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamAwsServiceMetadata;
import io.smithy.beam.core.BeamProtocolIds;
import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.ir.erlang.ErlAttribute;
import io.smithy.beam.ir.erlang.ErlComment;
import io.smithy.beam.ir.erlang.ErlExportAttribute;
import io.smithy.beam.ir.erlang.ErlFunction;
import io.smithy.beam.ir.erlang.ErlModule;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.StructureShape;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

/**
 * AWS Query protocol codec emitter for Erlang clients. POST / with form-urlencoded body.
 */
public final class ErlangAwsQueryEmitter {

    private ErlangAwsQueryEmitter() {}

    static void emitCodecModule(ErlangContext ctx, ServiceShape service) {
        emitCodecModule(ctx, service, BeamProtocolIds.AWS_QUERY);
    }

    static void emitCodecModule(ErlangContext ctx, ServiceShape service, ShapeId protocolTraitId) {
        boolean ec2Query = BeamProtocolIds.EC2_QUERY.equals(protocolTraitId);
        BeamAwsServiceMetadata.from(service).orElseThrow();
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String codecFile = layout.clientCodecModuleName(protocolTraitId) + ".erl";
        String codecModule = layout.clientCodecModuleName(protocolTraitId);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("encode_" + name + "_request/1");
            exports.add("decode_" + name + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(codecFile, writer -> {
            List<ErlFunction> functions = ErlangAwsQueryIr.clientCodecFunctions(
                    model, service, operations, httpIndex, sp, ec2Query);

            ErlModule module = new ErlModule(
                    codecModule,
                    List.of(
                            ErlComment.comment("AWS Query codecs for " + service.getId() + " (generated)."),
                            ErlComment.comment("DO NOT EDIT -- generated by smithy-beam codegen.")),
                    List.of(
                            new ErlAttribute("include", "\"" + layout.typesHeaderFile() + "\""),
                            new ErlAttribute("include", "\"" + layout.runtimeTypesHeaderFile() + "\""),
                            ErlExportAttribute.export(exports)),
                    functions);

            writer.write("$L", module.asString());
        });
    }

    static void emitServerCodecModule(ErlangContext ctx, ServiceShape service) {
        emitServerCodecModule(ctx, service, BeamProtocolIds.AWS_QUERY);
    }

    static void emitServerCodecModule(ErlangContext ctx, ServiceShape service, ShapeId protocolTraitId) {
        boolean ec2Query = BeamProtocolIds.EC2_QUERY.equals(protocolTraitId);
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String serverCodecFile = layout.serverCodecModuleName(protocolTraitId) + ".erl";
        String serverCodecModule = layout.serverCodecModuleName(protocolTraitId);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("decode_" + name + "_request/1");
            exports.add("encode_" + name + "_response/1");
        }

        Optional<String> serviceNamespace = io.smithy.beam.core.BeamXmlBindingIndex.xmlNamespaceUri(service);

        ctx.writerDelegator().useFileWriter(serverCodecFile, writer -> {
            List<ErlFunction> functions = ErlangAwsQueryIr.serverCodecFunctions(
                    model, service, operations, sp, serviceNamespace, ec2Query);

            ErlModule module = new ErlModule(
                    serverCodecModule,
                    List.of(
                            ErlComment.comment("Server AWS Query codecs for " + service.getId() + " (generated)."),
                            ErlComment.comment("DO NOT EDIT -- generated by smithy-beam codegen.")),
                    List.of(
                            new ErlAttribute("include", "\"" + layout.typesHeaderFile() + "\""),
                            new ErlAttribute("include", "\"" + layout.runtimeTypesHeaderFile() + "\""),
                            ErlExportAttribute.export(exports)),
                    functions);

            writer.write("$L", module.asString());
        });
    }
}
