package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamAwsServiceMetadata;
import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.ir.erlang.ErlAttribute;
import io.smithy.beam.ir.erlang.ErlComment;
import io.smithy.beam.ir.erlang.ErlExportAttribute;
import io.smithy.beam.ir.erlang.ErlFunction;
import io.smithy.beam.ir.erlang.ErlModule;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.ShapeId;

import java.util.ArrayList;
import java.util.List;

/**
 * Shared AWS JSON RPC codec emitter for Erlang. POST / with X-Amz-Target and JSON body.
 */
final class ErlangAwsJsonRpcEmitter {

    private ErlangAwsJsonRpcEmitter() {}

    static void emitServerCodecModule(
            ErlangContext ctx, ServiceShape service, ShapeId protocol, String contentType, String versionLabel) {
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String serverCodecFile = layout.serverCodecModuleName(protocol) + ".erl";
        String serverCodecModule = layout.serverCodecModuleName(protocol);
        ErlangRuntimeHelpersEmitter.emitIfNeeded(ctx, service);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();
        String eventStreamModule = layout.eventStreamModuleName();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("decode_" + name + "_request/1");
            exports.add("encode_" + name + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(serverCodecFile, writer -> {
            List<ErlFunction> functions = ErlangAwsJsonIr.serverCodecFunctions(
                    model, service, operations, httpIndex, sp, contentType, eventStreamModule);

            ErlModule module = new ErlModule(
                    serverCodecModule,
                    List.of(
                            ErlComment.comment("Server AWS JSON " + versionLabel + " codecs for "
                                    + service.getId() + " (generated)."),
                            ErlComment.comment("DO NOT EDIT -- generated by smithy-beam codegen.")),
                    List.of(
                            new ErlAttribute("include", "\"" + layout.typesHeaderFile() + "\""),
                            new ErlAttribute("include", "\"" + layout.runtimeTypesHeaderFile() + "\""),
                            ErlExportAttribute.export(exports)),
                    functions);

            writer.write("$L", module.asString());
        });
    }

    static void emitCodecModule(
            ErlangContext ctx, ServiceShape service, ShapeId protocol, String contentType, String versionLabel) {
        BeamAwsServiceMetadata.from(service).orElseThrow();
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String codecFile = layout.clientCodecModuleName(protocol) + ".erl";
        String codecModule = layout.clientCodecModuleName(protocol);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();
        String targetPrefix = service.getId().getName();
        String eventStreamModule = layout.eventStreamModuleName();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("encode_" + name + "_request/1");
            exports.add("decode_" + name + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(codecFile, writer -> {
            List<ErlFunction> functions = ErlangAwsJsonIr.clientCodecFunctions(
                    model, service, operations, httpIndex, sp,
                    targetPrefix, contentType, eventStreamModule);

            ErlModule module = new ErlModule(
                    codecModule,
                    List.of(
                            ErlComment.comment("AWS JSON " + versionLabel + " codecs for "
                                    + service.getId() + " (generated)."),
                            ErlComment.comment("DO NOT EDIT -- generated by smithy-beam codegen.")),
                    List.of(
                            new ErlAttribute("include", "\"" + layout.typesHeaderFile() + "\""),
                            new ErlAttribute("include", "\"" + layout.runtimeTypesHeaderFile() + "\""),
                            ErlExportAttribute.export(exports)),
                    functions);

            writer.write("$L", module.asString());
        });
    }
}
