package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamEventStreamIndex;
import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.ir.erlang.ErlExportAttribute;
import io.smithy.beam.core.BeamHostLabelIndex;
import io.smithy.beam.core.BeamHttpBindings;
import io.smithy.beam.core.BeamHttpChecksumIndex;
import io.smithy.beam.core.BeamNameUtils;
import software.amazon.smithy.codegen.core.Symbol;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.neighbor.Walker;
import software.amazon.smithy.model.knowledge.HttpBinding;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.BlobShape;
import software.amazon.smithy.model.shapes.EnumShape;
import software.amazon.smithy.model.shapes.IntEnumShape;
import software.amazon.smithy.model.shapes.ListShape;
import software.amazon.smithy.model.shapes.MapShape;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.StringShape;
import software.amazon.smithy.model.shapes.StructureShape;
import software.amazon.smithy.model.shapes.TimestampShape;
import software.amazon.smithy.model.shapes.UnionShape;
import software.amazon.smithy.model.traits.EndpointTrait;
import software.amazon.smithy.model.traits.EnumValueTrait;
import software.amazon.smithy.model.traits.TimestampFormatTrait;
import software.amazon.smithy.model.traits.HttpErrorTrait;
import software.amazon.smithy.model.traits.HttpTrait;
import software.amazon.smithy.model.traits.IdempotencyTokenTrait;
import software.amazon.smithy.model.traits.JsonNameTrait;
import software.amazon.smithy.model.traits.MediaTypeTrait;
import software.amazon.smithy.model.traits.SparseTrait;
import software.amazon.smithy.model.traits.StreamingTrait;

import software.amazon.smithy.model.pattern.SmithyPattern;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * REST JSON codec scaffolding for Erlang. Emits real encode/decode functions
 * when a REST JSON 1 protocol is selected; keeps codegen-core free of Erlang imports.
 */
public final class ErlangRestJson1Emitter {

    private ErlangRestJson1Emitter() {}

    /** Entry point called from ErlangClientDirectedCodegen#generateService. */
    public static void emitCodecModule(ErlangContext ctx, ServiceShape service) {
        Model model = ctx.model();
        ShapeId protocol = ctx.resolvedProtocolTraitId();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String codecFile = layout.clientCodecModuleName(protocol) + ".erl";
        String codecModule = layout.clientCodecModuleName(protocol);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        boolean encodeWithConfig = serviceHasHostLabelOperations(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
            exports.add("encode_" + name + "_request/" + (encodeWithConfig ? "2" : "1"));
            exports.add("decode_" + name + "_request/" + (labels.isEmpty() ? "1" : "2"));
            exports.add("decode_" + name + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(codecFile, writer -> {
            writer.write("%% REST JSON 1 codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", codecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            writer.write("$L", ErlExportAttribute.export(exports).asString());
            writer.write("");

            for (OperationShape op : operations) {
                ErlangRestJsonIr.writeFunction(writer, ErlangRestJsonIr.encodeRequest(
                        model, service, op, httpIndex, sp, encodeWithConfig, layout.eventStreamModuleName()));
                ErlangRestJsonIr.writeFunction(writer, ErlangRestJsonIr.decodeRequest(
                        model, op, httpIndex, sp, layout.eventStreamModuleName()));
                ErlangRestJsonIr.writeFunction(writer, ErlangRestJsonIr.decodeResponse(
                        model, service, op, httpIndex, sp, layout));
            }

            for (OperationShape op : operations) {
                ErlangRestJsonIr.writeFunction(writer, ErlangRestJsonIr.errorDispatch(
                        model, service, op, httpIndex, sp));
            }

            ErlangRestJsonIr.writeFunctions(writer, ErlangRestJsonIr.structureHelperFunctions(model, service, sp));
            ErlangRestJsonIr.writeFunctions(writer, ErlangRestJsonIr.enumHelperFunctions(model, service, sp));
            ErlangRestJsonIr.writeFunctions(writer, ErlangRestJsonIr.unionHelperFunctions(model, service, sp));
            ErlangRestJsonIr.writeFunctions(writer, ErlangRestJsonIr.privateCodecHelpers(model, service));
            if (encodeWithConfig) {
                emitBuildHostHelpers(writer, model, service, sp);
            }
        });
    }

    /** Entry point called from ErlangServerDirectedCodegen#generateService. */
    public static void emitServerCodecModule(ErlangContext ctx, ServiceShape service) {
        Model model = ctx.model();
        ShapeId protocol = ctx.resolvedProtocolTraitId();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String serverCodecFile = layout.serverCodecModuleName(protocol) + ".erl";
        String serverCodecModule = layout.serverCodecModuleName(protocol);
        ErlangRuntimeHelpersEmitter.emitIfNeeded(ctx, service);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        Set<ShapeId> errorIds = new LinkedHashSet<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
            exports.add("decode_" + name + "_request/" + (labels.isEmpty() ? "1" : "2"));
            exports.add("encode_" + name + "_response/1");
            errorIds.addAll(op.getErrors());
        }
        for (ShapeId errorId : errorIds) {
            StructureShape errShape = model.expectShape(errorId, StructureShape.class);
            exports.add("encode_" + recordName(sp.toSymbol(errShape)) + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(serverCodecFile, writer -> {
            writer.write("%% Server REST JSON 1 codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", serverCodecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            writer.write("$L", ErlExportAttribute.export(exports).asString());
            writer.write("");

            Set<ShapeId> emittedErrorEncoders = new LinkedHashSet<>();
            for (OperationShape op : operations) {
                ErlangRestJsonIr.writeFunction(writer, ErlangRestJsonIr.decodeRequest(
                        model, op, httpIndex, sp, layout.eventStreamModuleName()));
                emitResponseEncoder(writer, model, op, httpIndex, sp);
                emitErrorResponseEncoders(writer, model, op, sp, emittedErrorEncoders);
            }
            ErlangRestJsonIr.writeFunctions(writer, ErlangRestJsonIr.structureHelperFunctions(model, service, sp));
            ErlangRestJsonIr.writeFunctions(writer, ErlangRestJsonIr.enumHelperFunctions(model, service, sp));
            ErlangRestJsonIr.writeFunctions(writer, ErlangRestJsonIr.unionHelperFunctions(model, service, sp));
            ErlangRestJsonIr.writeFunctions(writer, ErlangRestJsonIr.privateCodecHelpers(model, service));
        });
    }

    /** Emits encode_<op>_response/1: takes OutputRecord, returns http_response(). */
    private static void emitResponseEncoder(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        StructureShape output = model.expectShape(op.getOutputShape(), StructureShape.class);
        String outputRecord = recordName(sp.toSymbol(output));
        String outputType = sp.toSymbol(output).getName();
        int successCode = httpIndex.getResponseCode(op);

        List<HttpBinding> respHeaders = httpIndex.getResponseBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> respPrefixHeaders = httpIndex.getResponseBindings(op, HttpBinding.Location.PREFIX_HEADERS);
        List<HttpBinding> respDoc = httpIndex.getResponseBindings(op, HttpBinding.Location.DOCUMENT);
        List<HttpBinding> respPayload = httpIndex.getResponseBindings(op, HttpBinding.Location.PAYLOAD);

        String responseContentType = resolvedResponseContentType(model, op);

        List<String> patternParts = new ArrayList<>();
        for (HttpBinding b : concat(respHeaders, respPrefixHeaders, respDoc, respPayload)) {
            String field = BeamNameUtils.toSnakeCase(b.getMember().getMemberName());
            patternParts.add(field + " = " + toBindingVar(field));
        }
        String pattern = patternParts.isEmpty()
                ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

        writer.write("%% Encode HTTP response for $L.", op.getId());
        ErlangFormat.writeSpec(writer, "encode_" + opName + "_response(" + outputType + ") -> #http_response{}");
        writer.write("encode_$L_response(#$L{$L}) ->", opName, outputRecord, pattern);
        writer.indent();

        if (respHeaders.isEmpty()) {
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"$L\">>}],", responseContentType);
        } else {
            List<String> headerClauses = new ArrayList<>();
            for (HttpBinding hb : respHeaders) {
                String headerName = hb.getLocationName();
                headerClauses.add(
                        "(V) when V =/= undefined -> {true, {<<\"" + headerName + "\">>, to_binary(V)}};");
            }
            headerClauses.add("(_) -> false");
            String headerArgs = respHeaders.stream()
                    .map(hb -> toBindingVar(BeamNameUtils.toSnakeCase(hb.getMember().getMemberName())))
                    .collect(Collectors.joining(", "));
            writer.write("ExtraHeaders = ");
            ErlangFormat.writeFiltermap(writer, headerClauses, headerArgs);
            writer.write(",");
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"$L\">>} | ExtraHeaders],", responseContentType);
        }

        for (HttpBinding ph : respPrefixHeaders) {
            String fieldName = BeamNameUtils.toSnakeCase(ph.getMember().getMemberName());
            String prefix = ph.getLocationName();
            writer.write("Headers = Headers ++ prefix_headers_to_list(<<\"$L\">>, $L),",
                    prefix, toBindingVar(fieldName));
        }

        if (!respPayload.isEmpty()) {
            HttpBinding pb = respPayload.get(0);
            String fieldName = BeamNameUtils.toSnakeCase(pb.getMember().getMemberName());
            if (isStreamingBlob(model, pb.getMember())) {
                writer.write("Stream = case $L of", toBindingVar(fieldName));
                writer.indent();
                writer.write("undefined -> undefined;");
                writer.write("Value -> Value");
                writer.dedent();
                writer.write("end,");
                writer.write("Body = <<>>,");
            } else {
                writer.write("Body = $L,", toBindingVar(fieldName));
            }
        } else if (!respDoc.isEmpty()) {
            writer.write("BodyMap = maps:filter(fun(_, V) -> V =/= undefined end, #{");
            for (int i = 0; i < respDoc.size(); i++) {
                HttpBinding db = respDoc.get(i);
                String fieldName = BeamNameUtils.toSnakeCase(db.getMember().getMemberName());
                String wireKey = jsonKey(db.getMember());
                String comma = i < respDoc.size() - 1 ? "," : "";
                Shape target = model.expectShape(db.getMember().getTarget());
                if (target instanceof EnumShape || target instanceof IntEnumShape) {
                    String helperName = sp.toSymbol(target).getName().replace("()", "");
                    writer.write("    <<\"$L\">> => encode_$L($L)$L",
                            wireKey, helperName, toBindingVar(fieldName), comma);
                } else if (target instanceof UnionShape) {
                    String helperName = sp.toSymbol(target).getName().replace("()", "");
                    writer.write("    <<\"$L\">> => encode_$L($L)$L",
                            wireKey, helperName, toBindingVar(fieldName), comma);
                } else if (target instanceof TimestampShape) {
                    String encodeHelper = timestampEncodeHelper(
                            httpIndex, db.getMember(), HttpBinding.Location.DOCUMENT);
                    writer.write("    <<\"$L\">> => $L($L)$L",
                            wireKey, encodeHelper, toBindingVar(fieldName), comma);
                } else {
                    writer.write("    <<\"$L\">> => $L$L",
                            wireKey,
                            ErlangJsonCodecSupport.encodeDocumentValue(
                                    model, sp, httpIndex, db.getMember(), fieldName),
                            comma);
                }
            }
            writer.write("}),");
            writer.write("Body = jsone:encode(BodyMap),");
        } else {
            writer.write("Body = <<>>,");
        }

        writer.write("#http_response{");
        writer.write("    status = $L,", successCode);
        writer.write("    headers = Headers,");
        writer.write("    body = Body");
        if (!respPayload.isEmpty() && isStreamingBlob(model, respPayload.get(0).getMember())) {
            writer.write("    ,stream = Stream");
        }
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    /** Emits encode_<error>_response/1 for each operation error record. */
    private static void emitErrorResponseEncoders(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            SymbolProvider sp,
            Set<ShapeId> emitted) {

        for (ShapeId errorId : op.getErrors()) {
            if (!emitted.add(errorId)) {
                continue;
            }
            StructureShape errShape = model.expectShape(errorId, StructureShape.class);
            String recName = recordName(sp.toSymbol(errShape));
            int status = errShape.hasTrait(HttpErrorTrait.class)
                    ? errShape.expectTrait(HttpErrorTrait.class).getCode()
                    : 500;

            List<String> patternParts = errShape.members().stream()
                    .filter(m -> !m.getMemberName().equals("__beam_error_kind"))
                    .map(m -> {
                        String field = BeamNameUtils.toSnakeCase(m.getMemberName());
                        return field + " = " + toBindingVar(field);
                    })
                    .collect(Collectors.toList());

            String pattern = patternParts.isEmpty()
                    ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

            writer.write("%% Encode HTTP error response for $L.", errorId);
            writer.write("encode_$L_response(#$L{$L}) ->", recName, recName, pattern);
            writer.indent();
            writer.write("BodyMap = #{");
            writer.write("    <<\"__type\">> => <<\"$L\">>", errorId.getName());
            for (MemberShape m : errShape.members()) {
                if (m.getMemberName().equals("__beam_error_kind")) {
                    continue;
                }
                String field = BeamNameUtils.toSnakeCase(m.getMemberName());
                writer.write("    , <<\"$L\">> => $L", m.getMemberName(), toBindingVar(field));
            }
            writer.write("},");
            writer.write("Body = jsone:encode(BodyMap),");
            writer.write("#http_response{");
            writer.write("    status = $L,", status);
            writer.write("    headers = [{<<\"Content-Type\">>, <<\"application/json\">>}],");
            writer.write("    body = Body");
            writer.write("}.");
            writer.dedent();
            writer.write("");
        }
    }

    static List<EnumShape> reachableEnumShapes(Model model, ServiceShape service) {
        Set<ShapeId> emitted = new LinkedHashSet<>();
        List<EnumShape> shapes = new ArrayList<>();
        for (Shape shape : new Walker(model).walkShapes(service)) {
            if (shape instanceof EnumShape enumShape && emitted.add(enumShape.getId())) {
                shapes.add(enumShape);
            }
        }
        return shapes;
    }

    static List<IntEnumShape> reachableIntEnumShapes(Model model, ServiceShape service) {
        Set<ShapeId> emitted = new LinkedHashSet<>();
        List<IntEnumShape> shapes = new ArrayList<>();
        for (Shape shape : new Walker(model).walkShapes(service)) {
            if (shape instanceof IntEnumShape intEnumShape && emitted.add(intEnumShape.getId())) {
                shapes.add(intEnumShape);
            }
        }
        return shapes;
    }

    private static void collectEnumTarget(Model model, MemberShape member, Set<ShapeId> out) {
        Shape target = model.expectShape(member.getTarget());
        if (target instanceof EnumShape || target instanceof IntEnumShape) {
            out.add(target.getId());
        }
    }

    static void collectStructureHelperTargets(
            Model model,
            ServiceShape service,
            HttpBindingIndex httpIndex,
            Set<StructureShape> structures,
            Set<StructureShape> listElementStructures) {
        Set<ShapeId> emitted = new LinkedHashSet<>();
        Set<ShapeId> listElementIds = new LinkedHashSet<>();

        for (OperationShape op : ErlangTopDown.containedOperationsSorted(model, service)) {
            StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
            for (MemberShape member : ErlangJsonCodecSupport.documentMembers(httpIndex, op, input, true)) {
                collectStructureTargets(model, member, emitted, listElementIds);
            }
            StructureShape output = model.expectShape(op.getOutputShape(), StructureShape.class);
            for (MemberShape member : ErlangJsonCodecSupport.documentMembers(httpIndex, op, output, false)) {
                collectStructureTargets(model, member, emitted, listElementIds);
            }
            for (HttpBinding.Location loc : HttpBinding.Location.values()) {
                for (HttpBinding b : httpIndex.getRequestBindings(op, loc)) {
                    collectStructureTargets(model, b.getMember(), emitted, listElementIds);
                }
                for (HttpBinding b : httpIndex.getResponseBindings(op, loc)) {
                    collectStructureTargets(model, b.getMember(), emitted, listElementIds);
                }
            }
        }

        for (ShapeId structureId : emitted) {
            structures.add(model.expectShape(structureId, StructureShape.class));
        }
        for (ShapeId structureId : listElementIds) {
            listElementStructures.add(model.expectShape(structureId, StructureShape.class));
        }
    }

    private static void collectStructureTargets(
            Model model, MemberShape member, Set<ShapeId> out, Set<ShapeId> listElements) {
        Shape target = model.expectShape(member.getTarget());
        if (target instanceof StructureShape structure) {
            if (out.add(structure.getId())) {
                for (MemberShape nested : structure.members()) {
                    collectStructureTargets(model, nested, out, listElements);
                }
            }
        } else if (target instanceof ListShape list) {
            Shape element = model.expectShape(list.getMember().getTarget());
            if (element instanceof StructureShape structure) {
                listElements.add(structure.getId());
            }
            collectStructureTargets(model, list.getMember(), out, listElements);
        } else if (target instanceof MapShape map) {
            collectStructureTargets(model, map.getValue(), out, listElements);
        }
    }

    static List<UnionShape> reachableUnionShapes(Model model, ServiceShape service) {
        BeamEventStreamIndex eventStreamIndex = BeamEventStreamIndex.of(model);
        Set<ShapeId> emitted = new LinkedHashSet<>();
        List<UnionShape> shapes = new ArrayList<>();
        for (Shape shape : new Walker(model).walkShapes(service)) {
            if (shape instanceof UnionShape union
                    && !eventStreamIndex.isEventStreamUnion(union)
                    && emitted.add(union.getId())) {
                shapes.add(union);
            }
        }
        return shapes;
    }

    private static void emitBuildHostHelpers(
            ErlangWriter writer,
            Model model,
            ServiceShape service,
            SymbolProvider sp) {

        writer.write("%% Host label helpers for @endpoint hostPrefix expansion.");
        writer.write("split_base_url(<<>>) ->");
        writer.indent();
        writer.write("{<<>>, <<>>};");
        writer.dedent();
        writer.write("split_base_url(BaseUrl) ->");
        writer.indent();
        writer.write("case uri_string:parse(binary_to_list(BaseUrl)) of");
        writer.indent();
        writer.write("#{scheme := Scheme, host := Host} = Parts ->");
        writer.indent();
        writer.write("PortSuffix = case maps:get(port, Parts, undefined) of");
        writer.indent();
        writer.write("undefined -> <<>>;");
        writer.write("Port -> <<\":\", (integer_to_binary(Port))/binary>>");
        writer.dedent();
        writer.write("end,");
        writer.write("{<< (list_to_binary(Scheme))/binary, \"://\">>,");
        writer.write(" << (list_to_binary(Host))/binary, PortSuffix/binary >>};");
        writer.dedent();
        writer.write("_ ->");
        writer.indent();
        writer.write("{<<>>, BaseUrl}");
        writer.dedent();
        writer.dedent();
        writer.write("end.");
        writer.dedent();
        writer.write("");

        BeamHostLabelIndex hostLabelIndex = BeamHostLabelIndex.of(model);
        for (OperationShape op : ErlangTopDown.containedOperationsSorted(model, service)) {
            List<MemberShape> hostLabels = hostLabelIndex.hostLabelMembers(op);
            if (hostLabels.isEmpty() || !op.hasTrait(EndpointTrait.class)) {
                continue;
            }
            StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
            String inputRecord = recordName(sp.toSymbol(input));
            SmithyPattern hostPrefix = op.expectTrait(EndpointTrait.class).getHostPrefix();
            String prefixExpr = buildHostPrefixExpression(hostPrefix);
            List<String> patternParts = hostLabels.stream()
                    .map(m -> {
                        String field = BeamNameUtils.toSnakeCase(m.getMemberName());
                        return field + " = " + toBindingVar(field);
                    })
                    .toList();
            String pattern = patternParts.isEmpty()
                    ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

            writer.write("build_host(#$L{$L}, Config) ->", inputRecord, pattern);
            writer.indent();
            writer.write("BaseUrl = maps:get(base_url, Config, <<>>),");
            writer.write("{_Scheme, Authority} = split_base_url(BaseUrl),");
            writer.write("Prefix = $L,", prefixExpr);
            writer.write("<<Prefix/binary, Authority/binary>>.");
            writer.dedent();
            writer.write("");
        }
    }

    public static boolean serviceHasHostLabelOperations(Model model, ServiceShape service) {
        BeamHostLabelIndex hostLabelIndex = BeamHostLabelIndex.of(model);
        for (OperationShape op : ErlangTopDown.containedOperationsSorted(model, service)) {
            if (!hostLabelIndex.hostLabelMembers(op).isEmpty() && op.hasTrait(EndpointTrait.class)) {
                return true;
            }
        }
        return false;
    }

    private static String buildHostPrefixExpression(SmithyPattern hostPrefix) {
        if (hostPrefix.getSegments().isEmpty()) {
            return "<<>>";
        }
        StringBuilder sb = new StringBuilder("<<");
        List<SmithyPattern.Segment> segments = hostPrefix.getSegments();
        for (int i = 0; i < segments.size(); i++) {
            SmithyPattern.Segment segment = segments.get(i);
            if (segment.isLabel()) {
                String memberName = segment.getContent();
                String fieldName = BeamNameUtils.toSnakeCase(memberName);
                sb.append("(uri_encode(to_binary(")
                        .append(toBindingVar(fieldName))
                        .append(")))/binary");
            } else {
                sb.append("\"").append(segment.getContent()).append("\"");
            }
            if (i < segments.size() - 1) {
                sb.append(", ");
            }
        }
        sb.append(">>");
        return sb.toString();
    }

    /** Record tag for #-record{} syntax; symbol names carry a trailing {@code ()} type suffix. */
    private static String recordName(Symbol symbol) {
        return symbol.getName().replace("()", "");
    }

    private static boolean isStreamingBlob(Model model, MemberShape member) {
        Shape target = model.expectShape(member.getTarget());
        return target instanceof BlobShape && target.hasTrait(StreamingTrait.class);
    }

    /** Erlang variable for a snake_case record field (Inaka CamelCase, no underscores). */
    private static String toBindingVar(String snakeField) {
        return BeamNameUtils.toCamelCaseVariable(snakeField);
    }

    private static String jsonKey(MemberShape member) {
        return member.getTrait(JsonNameTrait.class)
                .map(JsonNameTrait::getValue)
                .orElse(member.getMemberName());
    }

    private static String timestampEncodeHelper(
            HttpBindingIndex httpIndex, MemberShape member, HttpBinding.Location location) {
        TimestampFormatTrait.Format fmt = httpIndex.determineTimestampFormat(
                member, location, TimestampFormatTrait.Format.DATE_TIME);
        return fmt == TimestampFormatTrait.Format.EPOCH_SECONDS
                ? "encode_timestamp_epoch_seconds"
                : "encode_timestamp_date_time";
    }

    private static String timestampDecodeHelper(
            HttpBindingIndex httpIndex, MemberShape member, HttpBinding.Location location) {
        TimestampFormatTrait.Format fmt = httpIndex.determineTimestampFormat(
                member, location, TimestampFormatTrait.Format.DATE_TIME);
        return fmt == TimestampFormatTrait.Format.EPOCH_SECONDS
                ? "decode_timestamp_epoch_seconds"
                : "decode_timestamp_date_time";
    }

    @SafeVarargs
    private static <T> List<T> concat(List<T>... lists) {
        List<T> out = new ArrayList<>();
        for (List<T> l : lists) {
            out.addAll(l);
        }
        return out;
    }

    private static String resolvedResponseContentType(Model model, OperationShape op) {
        return BeamHttpBindings.from(model)
                .responseContentType(op, "application/json")
                .orElse("application/json");
    }
}
