package io.smithy.beam.erlang;

import io.beam.ir.erlang.BinaryExpr;
import io.beam.ir.erlang.BinaryPattern;
import io.beam.ir.erlang.Function;
import io.beam.ir.erlang.FunctionClause;
import io.beam.ir.erlang.Module;
import io.beam.ir.erlang.OpaqueExpr;
import io.beam.ir.erlang.Spec;
import io.beam.ir.erlang.TypeAlias;
import io.beam.ir.erlang.VariablePattern;
import java.util.ArrayList;
import java.util.List;
import software.amazon.smithy.model.shapes.ServiceShape;

final class ErlangS3EndpointIr {
  private static final String CLIENT_CONFIG = "client_config()";

  private ErlangS3EndpointIr() {}

  static Module s3EndpointModule(ServiceShape service) {
    List<Function> functions = new ArrayList<>();
    functions.add(regionHost());
    functions.add(resolveBucketUrl());
    functions.addAll(helperFunctions());
    return Module.of(
        "s3_endpoint",
        functions,
        List.of(
            "S3 bucket addressing helpers for " + service.getId() + " (generated).",
            "DO NOT EDIT -- generated by smithy-beam codegen."),
        null,
        null,
        List.of(TypeAlias.of("client_config", "#{binary() => term()}")),
        List.of("resolve_bucket_url/3", "region_host/1"));
  }

  static Function regionHost() {
    return Function.of(
        "region_host",
        List.of(
            FunctionClause.of(
                List.of(VariablePattern.of("Config")),
                OpaqueExpr.of(
                    """
                    BaseUrl = maps:get(base_url, Config, <<>>),
                    {_Scheme, Authority} = utils:split_base_url(BaseUrl),
                    Authority"""
                        .strip()))),
        Spec.of("region_host(" + CLIENT_CONFIG + ") -> binary()"),
        null,
        null);
  }

  static Function resolveBucketUrl() {
    return Function.of(
        "resolve_bucket_url",
        List.of(
            FunctionClause.of(
                List.of(
                    VariablePattern.of("Config"),
                    VariablePattern.of("Bucket"),
                    VariablePattern.of("Key")),
                OpaqueExpr.of(
                    """
                    Style = maps:get(s3_addressing_style, Config, virtual_host),
                    RegionHost = region_host(Config),
                    KeyPath = key_path(Key),
                    case Style of
                        virtual_host ->
                            Host = virtual_host(Config, Bucket, RegionHost),
                            {Host, KeyPath};
                        path_style ->
                            {RegionHost, <<"/", Bucket/binary, KeyPath/binary>>};
                        _ ->
                            Host = virtual_host(Config, Bucket, RegionHost),
                            {Host, KeyPath}
                    end"""
                        .strip()))),
        Spec.of(
            "resolve_bucket_url(" + CLIENT_CONFIG + ", binary(), binary()) -> {binary(), binary()}"),
        null,
        null);
  }

  static List<Function> helperFunctions() {
    return List.of(keyPath(), virtualHost(), s3HostSuffix());
  }

  private static Function keyPath() {
    return Function.of(
        "key_path",
        List.of(
            FunctionClause.of(List.of(BinaryPattern.of("")), BinaryExpr.of("")),
            FunctionClause.of(
                List.of(VariablePattern.of("Key")),
                OpaqueExpr.of("<<\"/\", Key/binary>>".strip()))),
        null,
        null,
        null);
  }

  private static Function virtualHost() {
    return Function.of(
        "virtual_host",
        List.of(
            FunctionClause.of(
                List.of(
                    VariablePattern.of("Config"),
                    VariablePattern.of("Bucket"),
                    VariablePattern.of("RegionHost")),
                OpaqueExpr.of(
                    """
                    case maps:get(s3_use_accelerate, Config, false) of
                        true -> <<Bucket/binary, ".s3-accelerate.amazonaws.com">>;
                        false ->
                            Suffix = s3_host_suffix(Config),
                            <<Bucket/binary, Suffix/binary, RegionHost/binary>>
                    end"""
                        .strip()))),
        null,
        null,
        null);
  }

  private static Function s3HostSuffix() {
    return Function.of(
        "s3_host_suffix",
        List.of(
            FunctionClause.of(
                List.of(VariablePattern.of("Config")),
                OpaqueExpr.of(
                    """
                    case maps:get(s3_use_dualstack, Config, false) of
                        true -> <<".s3.dualstack.">>;
                        false -> <<".s3.">>
                    end"""
                        .strip()))),
        null,
        null,
        null);
  }

}
