package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamAwsJson10ProtocolCodegen;
import io.smithy.beam.core.BeamAwsServiceMetadata;
import io.smithy.beam.core.BeamErlangLayout;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBinding;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.StructureShape;

import java.util.ArrayList;
import java.util.List;

/**
 * AWS JSON 1.0 RPC codec emitter for Erlang. POST / with X-Amz-Target and JSON body.
 */
public final class ErlangAwsJson10Emitter {

    public static final String CONTENT_TYPE = "application/x-amz-json-1.0";

    private ErlangAwsJson10Emitter() {}

    public static void emitCodecModule(ErlangContext ctx, ServiceShape service) {
        BeamAwsServiceMetadata.from(service).orElseThrow();
        Model model = ctx.model();
        ShapeId protocol = BeamAwsJson10ProtocolCodegen.AWS_JSON_1_0;
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String codecFile = layout.clientCodecModuleName(protocol) + ".erl";
        String codecModule = layout.clientCodecModuleName(protocol);
        ErlangRuntimeHelpersEmitter.emitIfNeeded(ctx, service);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();
        String targetPrefix = service.getId().getName();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("encode_" + name + "_request/1");
        }

        ctx.writerDelegator().useFileWriter(codecFile, writer -> {
            writer.write("%% AWS JSON 1.0 codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", codecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            writer.write("-export([$L]).", String.join(", ", exports));
            writer.write("");

            for (OperationShape op : operations) {
                emitEncoder(writer, model, op, httpIndex, sp, targetPrefix);
            }

            ErlangRestJson1Emitter.emitSharedCodecHelpers(writer, model, service, sp);
        });
    }

    private static void emitEncoder(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp,
            String targetPrefix) {

        String opName = sp.toSymbol(op).getName();
        StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
        String inputRecord = ErlangJsonCodecSupport.recordName(sp.toSymbol(input));
        String inputType = sp.toSymbol(input).getName();
        String pattern = ErlangJsonCodecSupport.inputPattern(input);
        List<software.amazon.smithy.model.shapes.MemberShape> members =
                ErlangJsonCodecSupport.documentMembers(httpIndex, op, input, true);
        String amzTarget = targetPrefix + "." + op.getId().getName();

        writer.write("%% Encode AWS JSON request for $L.", op.getId());
        writer.write("-spec encode_$L_request($L) -> #http_request{}.", opName, inputType);
        writer.write("encode_$L_request(Input = #$L{$L}) ->", opName, inputRecord, pattern);
        writer.indent();
        writer.write("BodyMap = maps:filter(fun(_, V) -> V =/= undefined end, #{");
        ErlangJsonCodecSupport.emitBodyMapEntries(
                writer, model, httpIndex, sp, members, HttpBinding.Location.DOCUMENT);
        writer.write("}),");
        writer.write("Body = jsone:encode(BodyMap),");
        writer.write("#http_request{");
        writer.write("    method = <<\"POST\">>,");
        writer.write("    path = <<\"/\">>,");
        writer.write("    query = #{},");
        writer.write("    headers = [");
        writer.write("        {<<\"Content-Type\">>, <<\"$L\">>},", CONTENT_TYPE);
        writer.write("        {<<\"X-Amz-Target\">>, <<\"$L\">>}", amzTarget);
        writer.write("    ],");
        writer.write("    body = Body");
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }
}
