package io.smithy.beam.erlang;

import io.beam.ir.erlang.Function;
import io.smithy.beam.core.BeamAwsServiceMetadata;
import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.core.BeamProtocolIds;
import io.smithy.beam.ir.erlang.ErlAttribute;
import io.smithy.beam.ir.erlang.ErlComment;
import io.smithy.beam.ir.erlang.ErlExportAttribute;
import io.smithy.beam.ir.erlang.ErlFunction;
import io.smithy.beam.ir.erlang.ErlModule;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.ShapeId;

final class ErlangAwsJsonIr {
  private static final Map<ShapeId, String> CONTENT_TYPES =
      Map.of(
          BeamProtocolIds.AWS_JSON_1_0, "application/x-amz-json-1.0",
          BeamProtocolIds.AWS_JSON_1_1, "application/x-amz-json-1.1");

  private static final Map<ShapeId, String> VERSION_LABELS =
      Map.of(
          BeamProtocolIds.AWS_JSON_1_0, "1.0",
          BeamProtocolIds.AWS_JSON_1_1, "1.1");

  private ErlangAwsJsonIr() {}

  static String clientCodecFileName(ErlangContext ctx, ServiceShape service, ShapeId protocol) {
    return layout(ctx, service).clientCodecModuleName(protocol) + ".erl";
  }

  static String serverCodecFileName(ErlangContext ctx, ServiceShape service, ShapeId protocol) {
    return layout(ctx, service).serverCodecModuleName(protocol) + ".erl";
  }

  static ErlModule buildClientCodecModule(
      ErlangContext ctx, ServiceShape service, ShapeId protocol) {
    BeamAwsServiceMetadata.from(service).orElseThrow();
    Model model = ctx.model();
    BeamErlangLayout layout = layout(ctx, service);
    HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
    SymbolProvider sp = ctx.symbolProvider();
    String targetPrefix = service.getId().getName();
    String contentType = contentType(protocol);
    String versionLabel = versionLabel(protocol);
    String eventStreamModule = layout.eventStreamModuleName();

    List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
    List<String> exports = new ArrayList<>();
    for (OperationShape op : operations) {
      String name = sp.toSymbol(op).getName();
      exports.add("encode_" + name + "_request/1");
      exports.add("decode_" + name + "_response/1");
    }

    List<ErlFunction> functions =
        clientCodecFunctions(
            model,
            service,
            operations,
            httpIndex,
            sp,
            targetPrefix,
            contentType,
            eventStreamModule);

    return new ErlModule(
        layout.clientCodecModuleName(protocol),
        List.of(
            ErlComment.comment(
                "AWS JSON " + versionLabel + " codecs for " + service.getId() + " (generated)."),
            ErlComment.comment("DO NOT EDIT -- generated by smithy-beam codegen.")),
        List.of(
            new ErlAttribute("include", "\"" + layout.typesHeaderFile() + "\""),
            new ErlAttribute("include", "\"" + layout.runtimeTypesHeaderFile() + "\""),
            ErlExportAttribute.export(exports)),
        functions);
  }

  static ErlModule buildServerCodecModule(
      ErlangContext ctx, ServiceShape service, ShapeId protocol) {
    Model model = ctx.model();
    BeamErlangLayout layout = layout(ctx, service);
    HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
    SymbolProvider sp = ctx.symbolProvider();
    String contentType = contentType(protocol);
    String versionLabel = versionLabel(protocol);
    String eventStreamModule = layout.eventStreamModuleName();

    List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
    List<String> exports = new ArrayList<>();
    for (OperationShape op : operations) {
      String name = sp.toSymbol(op).getName();
      exports.add("decode_" + name + "_request/1");
      exports.add("encode_" + name + "_response/1");
    }

    List<ErlFunction> functions =
        serverCodecFunctions(
            model, service, operations, httpIndex, sp, contentType, eventStreamModule);

    return new ErlModule(
        layout.serverCodecModuleName(protocol),
        List.of(
            ErlComment.comment(
                "Server AWS JSON "
                    + versionLabel
                    + " codecs for "
                    + service.getId()
                    + " (generated)."),
            ErlComment.comment("DO NOT EDIT -- generated by smithy-beam codegen.")),
        List.of(
            new ErlAttribute("include", "\"" + layout.typesHeaderFile() + "\""),
            new ErlAttribute("include", "\"" + layout.runtimeTypesHeaderFile() + "\""),
            ErlExportAttribute.export(exports)),
        functions);
  }

  static void emitClientCodecModule(ErlangContext ctx, ServiceShape service, ShapeId protocol) {
    ErlModule module = buildClientCodecModule(ctx, service, protocol);
    ErlangCodecEmission.writeModule(ctx, clientCodecFileName(ctx, service, protocol), module);
  }

  static void emitServerCodecModule(ErlangContext ctx, ServiceShape service, ShapeId protocol) {
    ErlangCodecEmission.emitRuntimeHelpersIfNeeded(ctx, service, true);
    ErlModule module = buildServerCodecModule(ctx, service, protocol);
    ErlangCodecEmission.writeModule(ctx, serverCodecFileName(ctx, service, protocol), module);
  }

  private static BeamErlangLayout layout(ErlangContext ctx, ServiceShape service) {
    return new BeamErlangLayout(ctx.settings(), service.getId().getNamespace(), service);
  }

  private static String contentType(ShapeId protocol) {
    String contentType = CONTENT_TYPES.get(protocol);
    if (contentType == null) {
      throw new IllegalArgumentException("Unsupported AWS JSON protocol: " + protocol);
    }
    return contentType;
  }

  private static String versionLabel(ShapeId protocol) {
    String versionLabel = VERSION_LABELS.get(protocol);
    if (versionLabel == null) {
      throw new IllegalArgumentException("Unsupported AWS JSON protocol: " + protocol);
    }
    return versionLabel;
  }

  static ErlFunction encodeRequest(
      Model model,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      String targetPrefix,
      String contentType,
      String eventStreamModule) {
    return ErlangAwsJsonOperationIr.buildEncodeRequest(
        model, op, httpIndex, sp, targetPrefix, contentType, eventStreamModule);
  }

  static ErlFunction decodeResponse(
      Model model,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      String eventStreamModule) {
    return ErlangAwsJsonOperationIr.buildDecodeResponse(
        model, op, httpIndex, sp, eventStreamModule);
  }

  static ErlFunction errorDispatch(Model model, OperationShape op, SymbolProvider sp) {
    return ErlangAwsJsonOperationIr.buildErrorDispatch(model, op, sp);
  }

  static ErlFunction decodeRequest(
      Model model,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      String eventStreamModule) {
    return ErlangAwsJsonOperationIr.buildDecodeRequest(model, op, httpIndex, sp, eventStreamModule);
  }

  static ErlFunction encodeResponse(
      Model model,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      String contentType,
      String eventStreamModule) {
    return ErlangAwsJsonOperationIr.buildEncodeResponse(
        model, op, httpIndex, sp, contentType, eventStreamModule);
  }

  static List<Function> sharedCodecHelpers(
      Model model, ServiceShape service, SymbolProvider sp) {
    List<Function> functions = new ArrayList<>();
    functions.addAll(ErlangRestJsonIr.structureHelperFunctions(model, service, sp));
    functions.addAll(ErlangRestJsonIr.enumHelperFunctions(model, service, sp));
    functions.addAll(ErlangRestJsonIr.unionHelperFunctions(model, service, sp));
    functions.addAll(ErlangRestJsonIr.mapHelperFunctions(model, service, sp));
    functions.addAll(ErlangRestJsonIr.privateCodecHelpers(model, service));
    return functions;
  }

  static List<ErlFunction> clientCodecFunctions(
      Model model,
      ServiceShape service,
      List<OperationShape> operations,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      String targetPrefix,
      String contentType,
      String eventStreamModule) {
    List<ErlFunction> functions = new ArrayList<>();
    for (OperationShape op : operations) {
      functions.add(
          encodeRequest(model, op, httpIndex, sp, targetPrefix, contentType, eventStreamModule));
      functions.add(decodeResponse(model, op, httpIndex, sp, eventStreamModule));
    }
    for (OperationShape op : operations) {
      functions.add(errorDispatch(model, op, sp));
    }
    functions.addAll(sharedCodecHelpers(model, service, sp));
    return functions;
  }

  static List<ErlFunction> serverCodecFunctions(
      Model model,
      ServiceShape service,
      List<OperationShape> operations,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      String contentType,
      String eventStreamModule) {
    List<ErlFunction> functions = new ArrayList<>();
    for (OperationShape op : operations) {
      functions.add(decodeRequest(model, op, httpIndex, sp, eventStreamModule));
      functions.add(encodeResponse(model, op, httpIndex, sp, contentType, eventStreamModule));
    }
    functions.addAll(sharedCodecHelpers(model, service, sp));
    return functions;
  }
}
