package io.smithy.beam.erlang;

import io.beam.ir.erlang.AtomExpr;
import io.beam.ir.erlang.AtomPattern;
import io.beam.ir.erlang.BinaryExpr;
import io.beam.ir.erlang.BinaryPattern;
import io.beam.ir.erlang.BinarySegmentExpr;
import io.beam.ir.erlang.CaseExpr;
import io.beam.ir.erlang.Clause;
import io.beam.ir.erlang.Function;
import io.beam.ir.erlang.FunctionClause;
import io.beam.ir.erlang.LocalCallExpr;
import io.beam.ir.erlang.MatchExpr;
import io.beam.ir.erlang.Module;
import io.beam.ir.erlang.RemoteCallExpr;
import io.beam.ir.erlang.Spec;
import io.beam.ir.erlang.TupleExpr;
import io.beam.ir.erlang.TuplePattern;
import io.beam.ir.erlang.TypeAlias;
import io.beam.ir.erlang.Variable;
import io.beam.ir.erlang.VariablePattern;
import io.beam.ir.erlang.WildcardPattern;
import java.util.ArrayList;
import java.util.List;
import software.amazon.smithy.model.shapes.ServiceShape;

final class ErlangS3EndpointIr {
  private static final String CLIENT_CONFIG = "client_config()";

  private ErlangS3EndpointIr() {}

  static Module s3EndpointModule(ServiceShape service) {
    List<Function> functions = new ArrayList<>();
    functions.add(regionHost());
    functions.add(resolveBucketUrl());
    functions.addAll(helperFunctions());
    return Module.of(
        "s3_endpoint",
        functions,
        List.of(
            "S3 bucket addressing helpers for " + service.getId() + " (generated).",
            "DO NOT EDIT -- generated by smithy-beam codegen."),
        null,
        null,
        List.of(TypeAlias.of("client_config", "#{binary() => term()}")),
        List.of("resolve_bucket_url/3", "region_host/1"));
  }

  static Function regionHost() {
    return Function.of(
        "region_host",
        List.of(
            FunctionClause.of(
                List.of(VariablePattern.of("Config")),
                MatchExpr.bind(
                    "BaseUrl",
                    RemoteCallExpr.of(
                        "maps",
                        "get",
                        List.of(AtomExpr.of("base_url"), Variable.of("Config"), BinaryExpr.of(""))),
                    MatchExpr.of(
                        TuplePattern.of(
                            List.of(WildcardPattern.of(), VariablePattern.of("Authority"))),
                        RemoteCallExpr.of(
                            "utils", "split_base_url", List.of(Variable.of("BaseUrl"))),
                        Variable.of("Authority"))))),
        Spec.of("region_host(" + CLIENT_CONFIG + ") -> binary()"));
  }

  static Function resolveBucketUrl() {
    return Function.of(
        "resolve_bucket_url",
        List.of(
            FunctionClause.of(
                List.of(
                    VariablePattern.of("Config"),
                    VariablePattern.of("Bucket"),
                    VariablePattern.of("Key")),
                MatchExpr.bind(
                    "Style",
                    RemoteCallExpr.of(
                        "maps",
                        "get",
                        List.of(
                            AtomExpr.of("s3_addressing_style"),
                            Variable.of("Config"),
                            AtomExpr.of("virtual_host"))),
                    MatchExpr.bind(
                        "RegionHost",
                        LocalCallExpr.of("region_host", List.of(Variable.of("Config"))),
                        MatchExpr.bind(
                            "KeyPath",
                            LocalCallExpr.of("key_path", List.of(Variable.of("Key"))),
                            CaseExpr.of(
                                Variable.of("Style"),
                                List.of(
                                    Clause.of(
                                        AtomPattern.of("virtual_host"),
                                        MatchExpr.bind(
                                            "Host",
                                            LocalCallExpr.of(
                                                "virtual_host",
                                                List.of(
                                                    Variable.of("Config"),
                                                    Variable.of("Bucket"),
                                                    Variable.of("RegionHost"))),
                                            TupleExpr.of(
                                                List.of(
                                                    Variable.of("Host"), Variable.of("KeyPath"))))),
                                    Clause.of(
                                        AtomPattern.of("path_style"),
                                        TupleExpr.of(
                                            List.of(
                                                Variable.of("RegionHost"),
                                                BinaryExpr.of(
                                                    List.of(
                                                        BinarySegmentExpr.literal("/"),
                                                        BinarySegmentExpr.of(
                                                            Variable.of("Bucket"), "binary"),
                                                        BinarySegmentExpr.of(
                                                            Variable.of("KeyPath"), "binary")))))),
                                    Clause.of(
                                        WildcardPattern.of(),
                                        MatchExpr.bind(
                                            "Host",
                                            LocalCallExpr.of(
                                                "virtual_host",
                                                List.of(
                                                    Variable.of("Config"),
                                                    Variable.of("Bucket"),
                                                    Variable.of("RegionHost"))),
                                            TupleExpr.of(
                                                List.of(
                                                    Variable.of("Host"),
                                                    Variable.of("KeyPath")))))))))))),
        Spec.of(
            "resolve_bucket_url("
                + CLIENT_CONFIG
                + ", binary(), binary()) -> {binary(), binary()}"));
  }

  static List<Function> helperFunctions() {
    return List.of(keyPath(), virtualHost(), s3HostSuffix());
  }

  private static Function keyPath() {
    return Function.of(
        "key_path",
        List.of(
            FunctionClause.of(List.of(BinaryPattern.of("")), BinaryExpr.of("")),
            FunctionClause.of(
                List.of(VariablePattern.of("Key")),
                BinaryExpr.of(
                    List.of(
                        BinarySegmentExpr.literal("/"),
                        BinarySegmentExpr.of(Variable.of("Key"), "binary"))))));
  }

  private static Function virtualHost() {
    return Function.of(
        "virtual_host",
        List.of(
            FunctionClause.of(
                List.of(
                    VariablePattern.of("Config"),
                    VariablePattern.of("Bucket"),
                    VariablePattern.of("RegionHost")),
                CaseExpr.of(
                    RemoteCallExpr.of(
                        "maps",
                        "get",
                        List.of(
                            AtomExpr.of("s3_use_accelerate"),
                            Variable.of("Config"),
                            AtomExpr.of("false"))),
                    List.of(
                        Clause.of(
                            AtomPattern.of("true"),
                            BinaryExpr.of(
                                List.of(
                                    BinarySegmentExpr.of(Variable.of("Bucket"), "binary"),
                                    BinarySegmentExpr.literal(".s3-accelerate.amazonaws.com")))),
                        Clause.of(
                            WildcardPattern.of(),
                            MatchExpr.bind(
                                "Suffix",
                                LocalCallExpr.of("s3_host_suffix", List.of(Variable.of("Config"))),
                                BinaryExpr.of(
                                    List.of(
                                        BinarySegmentExpr.of(Variable.of("Bucket"), "binary"),
                                        BinarySegmentExpr.of(Variable.of("Suffix"), "binary"),
                                        BinarySegmentExpr.of(
                                            Variable.of("RegionHost"), "binary"))))))))));
  }

  private static Function s3HostSuffix() {
    return Function.of(
        "s3_host_suffix",
        List.of(
            FunctionClause.of(
                List.of(VariablePattern.of("Config")),
                CaseExpr.of(
                    RemoteCallExpr.of(
                        "maps",
                        "get",
                        List.of(
                            AtomExpr.of("s3_use_dualstack"),
                            Variable.of("Config"),
                            AtomExpr.of("false"))),
                    List.of(
                        Clause.of(AtomPattern.of("true"), BinaryExpr.of(".s3.dualstack.")),
                        Clause.of(WildcardPattern.of(), BinaryExpr.of(".s3.")))))));
  }
}
