package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamAwsServiceMetadata;
import io.smithy.beam.core.BeamProtocolIds;
import io.smithy.beam.core.BeamErlangLayout;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.StructureShape;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

/**
 * AWS Query protocol codec emitter for Erlang clients. POST / with form-urlencoded body.
 */
public final class ErlangAwsQueryEmitter {

    private ErlangAwsQueryEmitter() {}

    static void emitCodecModule(ErlangContext ctx, ServiceShape service) {
        emitCodecModule(ctx, service, BeamProtocolIds.AWS_QUERY);
    }

    static void emitCodecModule(ErlangContext ctx, ServiceShape service, ShapeId protocolTraitId) {
        boolean ec2Query = BeamProtocolIds.EC2_QUERY.equals(protocolTraitId);
        BeamAwsServiceMetadata.from(service).orElseThrow();
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String codecFile = layout.clientCodecModuleName(protocolTraitId) + ".erl";
        String codecModule = layout.clientCodecModuleName(protocolTraitId);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("encode_" + name + "_request/1");
            exports.add("decode_" + name + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(codecFile, writer -> {
            writer.write("%% AWS Query codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", codecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            ErlangFormat.writeExport(writer, exports);
            writer.write("");

            for (OperationShape op : operations) {
                ErlangAwsQueryIr.writeFunction(writer, ErlangAwsQueryIr.encodeRequest(
                        model, service, op, httpIndex, sp));
                ErlangAwsQueryIr.writeFunction(writer, ErlangAwsQueryIr.decodeResponse(
                        model, service, op, sp, ec2Query));
            }

            List<StructureShape> flattenInputs = ErlangAwsQueryIr.inputShapes(model, service);
            ErlangAwsQueryIr.writeFunction(writer, ErlangAwsQueryIr.flattenQueryInput(
                    model, httpIndex, sp, flattenInputs, ec2Query));

            ErlangAwsQueryIr.writeFunctions(writer, ErlangAwsQueryIr.queryHelpers(ec2Query));
            ErlangAwsQueryIr.writeFunctions(writer, ErlangAwsQueryIr.xmlHelpers(ec2Query));
        });
    }

    static void emitServerCodecModule(ErlangContext ctx, ServiceShape service) {
        emitServerCodecModule(ctx, service, BeamProtocolIds.AWS_QUERY);
    }

    static void emitServerCodecModule(ErlangContext ctx, ServiceShape service, ShapeId protocolTraitId) {
        boolean ec2Query = BeamProtocolIds.EC2_QUERY.equals(protocolTraitId);
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String serverCodecFile = layout.serverCodecModuleName(protocolTraitId) + ".erl";
        String serverCodecModule = layout.serverCodecModuleName(protocolTraitId);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("decode_" + name + "_request/1");
            exports.add("encode_" + name + "_response/1");
        }

        Set<StructureShape> inputShapes = new LinkedHashSet<>();
        for (OperationShape op : operations) {
            inputShapes.add(model.expectShape(op.getInputShape(), StructureShape.class));
        }

        Optional<String> serviceNamespace = io.smithy.beam.core.BeamXmlBindingIndex.xmlNamespaceUri(service);

        ctx.writerDelegator().useFileWriter(serverCodecFile, writer -> {
            writer.write("%% Server AWS Query codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", serverCodecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            ErlangFormat.writeExport(writer, exports);
            writer.write("");

            emitServiceXmlNamespace(writer, serviceNamespace);

            for (OperationShape op : operations) {
                ErlangAwsQueryIr.writeFunction(writer, ErlangAwsQueryIr.serverDecodeRequest(
                        model, op, sp, ec2Query));
                ErlangAwsQueryIr.writeFunction(writer, ErlangAwsQueryIr.serverEncodeResponse(
                        model, service, op, sp, ec2Query));
            }

            for (StructureShape input : inputShapes) {
                ErlangAwsQueryIr.writeFunction(writer, ErlangAwsQueryIr.parseInputFromForm(
                        model, sp, input, ec2Query));
            }

            ErlangAwsQueryIr.writeFunctions(writer, ErlangAwsQueryIr.serverQueryDecodeHelpers(ec2Query));
            ErlangAwsQueryIr.writeFunctions(writer, ErlangAwsQueryIr.serverXmlEncodeHelpers(ec2Query));
        });
    }

    private static void emitServiceXmlNamespace(ErlangWriter writer, Optional<String> namespaceUri) {
        if (namespaceUri.isPresent()) {
            writer.write("xml_namespace() -> #{uri => <<\"$L\">>}.", namespaceUri.get());
        } else {
            writer.write("xml_namespace() -> #{}.");
        }
        writer.write("");
    }
}
