package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.core.BeamHostLabelIndex;
import io.smithy.beam.core.BeamHttpBindings;
import io.smithy.beam.core.BeamHttpChecksumIndex;
import io.smithy.beam.core.BeamNameUtils;
import io.smithy.beam.core.BeamRestXmlProtocolCodegen;
import io.smithy.beam.core.BeamS3CustomizationIndex;
import io.smithy.beam.core.BeamXmlBindingIndex;
import software.amazon.smithy.codegen.core.Symbol;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBinding;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.BlobShape;
import software.amazon.smithy.model.shapes.ListShape;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.StringShape;
import software.amazon.smithy.model.shapes.StructureShape;
import software.amazon.smithy.model.traits.EndpointTrait;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.traits.HttpErrorTrait;
import software.amazon.smithy.model.traits.HttpTrait;
import software.amazon.smithy.model.traits.IdempotencyTokenTrait;
import software.amazon.smithy.model.traits.MediaTypeTrait;
import software.amazon.smithy.model.pattern.SmithyPattern;

import java.util.LinkedHashSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * REST-XML protocol codec emitter for Erlang clients. Combines HTTP bindings
 * with XML payload encoding for restXml services.
 */
public final class ErlangRestXmlEmitter {

    private static final String DEFAULT_CONTENT_TYPE = "application/xml";

    private ErlangRestXmlEmitter() {}

    public static void emitCodecModule(ErlangContext ctx, ServiceShape service) {
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String codecFile = layout.clientCodecModuleName(BeamRestXmlProtocolCodegen.REST_XML) + ".erl";
        String codecModule = layout.clientCodecModuleName(BeamRestXmlProtocolCodegen.REST_XML);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        boolean encodeWithConfig = serviceEncodesWithConfig(model, service);
        boolean checksumBindings = ErlangHttpChecksumEmitter.serviceHasChecksumOperations(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
            exports.add("encode_" + name + "_request/" + (encodeWithConfig ? "2" : "1"));
            exports.add("decode_" + name + "_request/" + (labels.isEmpty() ? "1" : "2"));
            exports.add("decode_" + name + "_response/1");
        }

        Optional<String> serviceNamespace = BeamXmlBindingIndex.xmlNamespaceUri(service);

        ctx.writerDelegator().useFileWriter(codecFile, writer -> {
            writer.write("%% REST-XML codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", codecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            ErlangFormat.writeExport(writer, exports);
            writer.write("");

            emitServiceXmlNamespace(writer, serviceNamespace);

            for (OperationShape op : operations) {
                emitEncoder(writer, model, service, op, httpIndex, sp, encodeWithConfig);
                emitRequestDecoder(writer, model, op, httpIndex, sp);
                emitDecoder(writer, model, op, httpIndex, sp);
            }

            emitXmlEncodeHelpers(writer);
            emitXmlDecodeHelpers(writer);
            if (checksumBindings) {
                ErlangHttpChecksumEmitter.emitChecksumHelpers(writer);
            }
            if (encodeWithConfig) {
                emitBuildHostHelpers(writer, model, service, sp);
            }
        });
    }

    public static void emitServerCodecModule(ErlangContext ctx, ServiceShape service) {
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String serverCodecFile = layout.serverCodecModuleName(BeamRestXmlProtocolCodegen.REST_XML) + ".erl";
        String serverCodecModule = layout.serverCodecModuleName(BeamRestXmlProtocolCodegen.REST_XML);
        ErlangRuntimeHelpersEmitter.emitIfNeeded(ctx, service);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        Set<ShapeId> errorIds = new LinkedHashSet<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
            exports.add("decode_" + name + "_request/" + (labels.isEmpty() ? "1" : "2"));
            exports.add("encode_" + name + "_response/1");
            errorIds.addAll(op.getErrors());
        }
        for (ShapeId errorId : errorIds) {
            StructureShape errShape = model.expectShape(errorId, StructureShape.class);
            exports.add("encode_" + recordName(sp.toSymbol(errShape)) + "_response/1");
        }

        Optional<String> serviceNamespace = BeamXmlBindingIndex.xmlNamespaceUri(service);

        ctx.writerDelegator().useFileWriter(serverCodecFile, writer -> {
            writer.write("%% Server REST-XML codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", serverCodecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            ErlangFormat.writeExport(writer, exports);
            writer.write("");

            emitServiceXmlNamespace(writer, serviceNamespace);

            Set<ShapeId> emittedErrorEncoders = new LinkedHashSet<>();
            for (OperationShape op : operations) {
                emitRequestDecoder(writer, model, op, httpIndex, sp);
                emitResponseEncoder(writer, model, op, httpIndex, sp);
                emitErrorResponseEncoders(writer, model, op, sp, emittedErrorEncoders);
            }

            emitXmlEncodeHelpers(writer);
            emitXmlDecodeHelpers(writer);
        });
    }

    private static void emitRequestDecoder(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
        String inputRecord = recordName(sp.toSymbol(input));
        String inputType = sp.toSymbol(input).getName();

        List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
        List<HttpBinding> queries = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY);
        List<HttpBinding> queryParams = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY_PARAMS);
        List<HttpBinding> headers = httpIndex.getRequestBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> prefixHeaders = httpIndex.getRequestBindings(op, HttpBinding.Location.PREFIX_HEADERS);
        List<HttpBinding> payloadMembers = httpIndex.getRequestBindings(op, HttpBinding.Location.PAYLOAD);

        writer.write("%% Decode REST-XML request for $L.", op.getId());
        if (labels.isEmpty()) {
            writer.write("-spec decode_$L_request(#http_request{}) -> {'ok', $L} | {'error', term()}.",
                    opName, inputType);
            writer.write("decode_$L_request(#http_request{query = Query, headers = Headers, body = Body}) ->",
                    opName);
        } else {
            writer.write("-spec decode_$L_request(map(), #http_request{}) -> {'ok', $L} | {'error', term()}.",
                    opName, inputType);
            writer.write("decode_$L_request(Labels, #http_request{query = Query, headers = Headers, body = Body}) ->",
                    opName);
        }
        writer.indent();

        for (HttpBinding lb : labels) {
            String fieldName = BeamNameUtils.toSnakeCase(lb.getMember().getMemberName());
            writer.write("$L = maps:get(<<\"$L\">>, Labels, undefined),",
                    toBindingVar(fieldName), lb.getLocationName());
        }
        for (HttpBinding qb : queries) {
            String fieldName = BeamNameUtils.toSnakeCase(qb.getMember().getMemberName());
            writer.write("$L = maps:get(<<\"$L\">>, Query, undefined),",
                    toBindingVar(fieldName), qb.getLocationName());
        }
        for (HttpBinding hb : headers) {
            String fieldName = BeamNameUtils.toSnakeCase(hb.getMember().getMemberName());
            writer.write("$L = proplists:get_value(<<\"$L\">>, Headers, undefined),",
                    toBindingVar(fieldName), hb.getLocationName());
        }
        for (HttpBinding ph : prefixHeaders) {
            String fieldName = BeamNameUtils.toSnakeCase(ph.getMember().getMemberName());
            writer.write("$L = prefix_headers_from_list(Headers, <<\"$L\">>),",
                    toBindingVar(fieldName), ph.getLocationName());
        }

        emitPayloadDecodeField(writer, model, payloadMembers, inputRecord, sp);

        List<String> recordFields = new ArrayList<>();
        for (HttpBinding b : concat(labels, queries, queryParams, headers, prefixHeaders, payloadMembers)) {
            String fieldName = BeamNameUtils.toSnakeCase(b.getMember().getMemberName());
            recordFields.add("    " + fieldName + " = " + toBindingVar(fieldName));
        }

        writer.write("{ok, #$L{", inputRecord);
        if (!recordFields.isEmpty()) {
            writer.write(String.join(",\n", recordFields));
        }
        writer.write("}}.");
        writer.dedent();
        writer.write("");
    }

    private static void emitPayloadDecodeField(
            ErlangWriter writer,
            Model model,
            List<HttpBinding> payloadMembers,
            String inputRecord,
            SymbolProvider sp) {

        if (payloadMembers.isEmpty()) {
            return;
        }
        HttpBinding payload = payloadMembers.get(0);
        MemberShape member = payload.getMember();
        Shape target = model.expectShape(member.getTarget());
        String fieldName = BeamNameUtils.toSnakeCase(member.getMemberName());
        String bindingVar = toBindingVar(fieldName);

        if (target instanceof BlobShape || target instanceof StringShape) {
            writer.write("$L = Body,", bindingVar);
            return;
        }

        String rootElement = BeamXmlBindingIndex.payloadRootElementName(member, target);
        writer.write("$L = case Body of", bindingVar);
        writer.indent();
        writer.write("<<>> -> undefined;");
        writer.write("_ ->");
        writer.indent();
        writer.write("case parse_xml_root(Body, <<\"$L\">>) of", rootElement);
        writer.indent();
        writer.write("{ok, Root} -> $L;",
                decodeStructureFromXml(model, (StructureShape) target, "Root", sp));
        writer.write("{error, _} -> undefined");
        writer.dedent();
        writer.write("end");
        writer.dedent();
        writer.dedent();
        writer.write("end,");
    }

    private static void emitDecoder(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        StructureShape output = model.expectShape(op.getOutputShape(), StructureShape.class);
        String outputRecord = recordName(sp.toSymbol(output));
        String outputType = sp.toSymbol(output).getName();
        int successCode = httpIndex.getResponseCode(op);

        List<HttpBinding> respHeaders = httpIndex.getResponseBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> respPrefixHeaders = httpIndex.getResponseBindings(op, HttpBinding.Location.PREFIX_HEADERS);
        List<HttpBinding> respPayload = httpIndex.getResponseBindings(op, HttpBinding.Location.PAYLOAD);

        writer.write("%% Decode REST-XML response for $L.", op.getId());
        ErlangFormat.writeSpec(
                writer,
                "decode_" + opName + "_response(#http_response{}) -> {'ok', " + outputType + "} | {'error', term()}");
        writer.write("decode_$L_response(#http_response{status = $L, headers = Headers, body = Body}) ->",
                opName, successCode);
        writer.indent();

        for (HttpBinding hb : respHeaders) {
            String fieldName = BeamNameUtils.toSnakeCase(hb.getMember().getMemberName());
            writer.write("$L = proplists:get_value(<<\"$L\">>, Headers, undefined),",
                    toBindingVar(fieldName), hb.getLocationName());
        }
        for (HttpBinding ph : respPrefixHeaders) {
            String fieldName = BeamNameUtils.toSnakeCase(ph.getMember().getMemberName());
            writer.write("$L = prefix_headers_from_list(Headers, <<\"$L\">>),",
                    toBindingVar(fieldName), ph.getLocationName());
        }

        if (!respPayload.isEmpty()) {
            HttpBinding pb = respPayload.get(0);
            MemberShape member = pb.getMember();
            Shape target = model.expectShape(member.getTarget());
            String fieldName = BeamNameUtils.toSnakeCase(member.getMemberName());
            if (target instanceof BlobShape || target instanceof StringShape) {
                writer.write("$L = Body,", toBindingVar(fieldName));
            } else {
                String rootElement = BeamXmlBindingIndex.payloadRootElementName(member, target);
                writer.write("$L = case parse_xml_root(Body, <<\"$L\">>) of",
                        toBindingVar(fieldName), rootElement);
                writer.indent();
                writer.write("{ok, Root} -> $L;",
                        decodeStructureFromXml(model, (StructureShape) target, "Root", sp));
                writer.write("{error, _} -> undefined");
                writer.dedent();
                writer.write("end,");
            }
        } else if (!output.members().isEmpty()) {
            String rootElement = BeamXmlBindingIndex.shapeElementName(output);
            writer.write("Parsed = case parse_xml_root(Body, <<\"$L\">>) of", rootElement);
            writer.indent();
            writer.write("{ok, Root} -> Root;");
            writer.write("{error, _} -> undefined");
            writer.dedent();
            writer.write("end,");
            emitStructureFieldsFromXml(writer, model, output, "Parsed", sp, "    ");
        }

        List<String> recordFields = new ArrayList<>();
        for (HttpBinding hb : concat(respHeaders, respPrefixHeaders, respPayload)) {
            String fieldName = BeamNameUtils.toSnakeCase(hb.getMember().getMemberName());
            recordFields.add("    " + fieldName + " = " + toBindingVar(fieldName));
        }
        if (respPayload.isEmpty() && !output.members().isEmpty()) {
            for (MemberShape member : output.members()) {
                String fieldName = BeamNameUtils.toSnakeCase(member.getMemberName());
                recordFields.add("    " + fieldName + " = " + toBindingVar(fieldName));
            }
        }

        StringBuilder success = new StringBuilder();
        success.append("{ok, #").append(outputRecord).append("{");
        if (!recordFields.isEmpty()) {
            success.append("\n").append(String.join(",\n", recordFields)).append("\n");
        }
        success.append("}}");
        if (BeamHttpChecksumIndex.of(model).responseChecksums(op).isEmpty()) {
            writer.write("$L;", success.toString());
        } else {
            writer.write("Result = $L,", success.toString());
            ErlangHttpChecksumEmitter.emitResponseChecksumGuard(writer, model, op, "Result");
            writer.write(";");
        }
        writer.dedent();
        writer.write("decode_$L_response(#http_response{status = Status, body = Body}) ->", opName);
        writer.indent();
        writer.write("decode_rest_xml_error(Status, Body).");
        writer.dedent();
        writer.write("");
    }

    private static void emitResponseEncoder(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        StructureShape output = model.expectShape(op.getOutputShape(), StructureShape.class);
        String outputRecord = recordName(sp.toSymbol(output));
        String outputType = sp.toSymbol(output).getName();
        int successCode = httpIndex.getResponseCode(op);

        List<HttpBinding> respHeaders = httpIndex.getResponseBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> respPrefixHeaders = httpIndex.getResponseBindings(op, HttpBinding.Location.PREFIX_HEADERS);
        List<HttpBinding> respPayload = httpIndex.getResponseBindings(op, HttpBinding.Location.PAYLOAD);

        List<String> patternParts = new ArrayList<>();
        for (HttpBinding b : concat(respHeaders, respPrefixHeaders, respPayload)) {
            String field = BeamNameUtils.toSnakeCase(b.getMember().getMemberName());
            patternParts.add(field + " = " + toBindingVar(field));
        }
        boolean implicitBody = respPayload.isEmpty() && !output.members().isEmpty();
        if (implicitBody) {
            patternParts.clear();
            for (MemberShape member : output.members()) {
                String field = BeamNameUtils.toSnakeCase(member.getMemberName());
                patternParts.add(field + " = " + toBindingVar(field));
            }
        }
        String pattern = patternParts.isEmpty() ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

        writer.write("%% Encode REST-XML response for $L.", op.getId());
        ErlangFormat.writeSpec(writer, "encode_" + opName + "_response(" + outputType + ") -> #http_response{}");
        writer.write("encode_$L_response(#$L{$L}) ->", opName, outputRecord, pattern);
        writer.indent();

        if (respHeaders.isEmpty()) {
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"application/xml\">>}],");
        } else {
            writer.write("ExtraHeaders = lists:filtermap(fun");
            for (HttpBinding hb : respHeaders) {
                writer.write("    (V) when V =/= undefined -> {true, {<<\"$L\">>, to_binary(V)}};",
                        hb.getLocationName());
            }
            writer.write("    (_) -> false");
            writer.write("end, [$L]),",
                    respHeaders.stream()
                            .map(hb -> toBindingVar(
                                    BeamNameUtils.toSnakeCase(hb.getMember().getMemberName())))
                            .collect(Collectors.joining(", ")));
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"application/xml\">>} | ExtraHeaders],");
        }

        for (HttpBinding ph : respPrefixHeaders) {
            String fieldName = BeamNameUtils.toSnakeCase(ph.getMember().getMemberName());
            writer.write("Headers = Headers ++ prefix_headers_to_list(<<\"$L\">>, $L),",
                    ph.getLocationName(), toBindingVar(fieldName));
        }

        if (!respPayload.isEmpty()) {
            emitResponseBodyFromPayload(writer, model, respPayload.get(0), sp);
        } else if (implicitBody) {
            String rootElement = BeamXmlBindingIndex.shapeElementName(output);
            writer.write("XmlNs = xml_namespace(),");
            writer.write("MemberMap = maps:filter(fun(_, V) -> V =/= undefined end, #{");
            for (MemberShape member : output.members()) {
                String field = BeamNameUtils.toSnakeCase(member.getMemberName());
                String wireName = BeamXmlBindingIndex.memberElementName(member);
                writer.write("    <<\"$L\">> => $L,", wireName, toBindingVar(field));
            }
            writer.write("}),");
            writer.write("Body = encode_xml(#{<<\"$L\">> => MemberMap}, XmlNs),", rootElement);
        } else {
            writer.write("Body = <<>>,");
        }

        writer.write("#http_response{");
        writer.write("    status = $L,", successCode);
        writer.write("    headers = Headers,");
        writer.write("    body = Body");
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    private static void emitResponseBodyFromPayload(
            ErlangWriter writer, Model model, HttpBinding payload, SymbolProvider sp) {

        MemberShape member = payload.getMember();
        Shape target = model.expectShape(member.getTarget());
        String bindingVar = toBindingVar(BeamNameUtils.toSnakeCase(member.getMemberName()));

        if (target instanceof BlobShape || target instanceof StringShape) {
            writer.write("Body = case $L of", bindingVar);
            writer.indent();
            writer.write("undefined -> <<>>;");
            writer.write("Value -> Value");
            writer.dedent();
            writer.write("end,");
            return;
        }

        String rootElement = BeamXmlBindingIndex.payloadRootElementName(member, target);
        writer.write("XmlNs = xml_namespace(),");
        writer.write("Body = case $L of", bindingVar);
        writer.indent();
        writer.write("undefined -> <<>>;");
        writer.write("PayloadValue ->");
        writer.indent();
        if (target instanceof StructureShape structure) {
            writer.write("MemberMap = $L,",
                    buildStructureXmlMap(model, structure, "PayloadValue", recordName(sp.toSymbol(structure))));
            writer.write("encode_xml(#{<<\"$L\">> => MemberMap}, XmlNs)", rootElement);
        } else {
            writer.write("encode_xml(#{<<\"$L\">> => PayloadValue}, XmlNs)", rootElement);
        }
        writer.dedent();
        writer.dedent();
        writer.write("end,");
    }

    private static void emitErrorResponseEncoders(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            SymbolProvider sp,
            Set<ShapeId> emitted) {

        for (ShapeId errorId : op.getErrors()) {
            if (!emitted.add(errorId)) {
                continue;
            }
            StructureShape errShape = model.expectShape(errorId, StructureShape.class);
            String recName = recordName(sp.toSymbol(errShape));
            int status = errShape.hasTrait(HttpErrorTrait.class)
                    ? errShape.expectTrait(HttpErrorTrait.class).getCode()
                    : 500;
            String rootElement = BeamXmlBindingIndex.shapeElementName(errShape);

            writer.write("encode_$L_response(Error = #$L{}) ->", recName, recName);
            writer.indent();
            writer.write("XmlNs = xml_namespace(),");
            writer.write("MemberMap = $L,", buildStructureXmlMap(model, errShape, "Error", recName));
            writer.write("Inner = encode_xml(#{<<\"$L\">> => MemberMap}, XmlNs),", rootElement);
            writer.write("Body = encode_xml(#{<<\"Error\">> => Inner}, XmlNs),");
            writer.write("#http_response{");
            writer.write("    status = $L,", status);
            writer.write("    headers = [{<<\"Content-Type\">>, <<\"application/xml\">>}],");
            writer.write("    body = Body");
            writer.write("}.");
            writer.dedent();
            writer.write("");
        }
    }

    private static String decodeStructureFromXml(
            Model model, StructureShape structure, String xmlVar, SymbolProvider sp) {
        List<String> fields = new ArrayList<>();
        String recordTag = recordName(sp.toSymbol(structure));
        for (MemberShape member : structure.members()) {
            String field = BeamNameUtils.toSnakeCase(member.getMemberName());
            Shape target = model.expectShape(member.getTarget());
            if (BeamXmlBindingIndex.isXmlAttribute(member)) {
                fields.add(field + " = xml_attribute(" + xmlVar + ", <<\""
                        + BeamXmlBindingIndex.memberElementName(member) + "\">>)");
            } else if (target instanceof ListShape listShape) {
                fields.add(field + " = "
                        + decodeListFieldFromXml(model, member, listShape, xmlVar, sp));
            } else {
                fields.add(field + " = xml_child_text(" + xmlVar + ", <<\""
                        + BeamXmlBindingIndex.memberElementName(member) + "\">>)");
            }
        }
        if (fields.isEmpty()) {
            return "#" + recordTag + "{}";
        }
        return "#" + recordTag + "{" + String.join(", ", fields) + "}";
    }

    private static String decodeListFieldFromXml(
            Model model,
            MemberShape member,
            ListShape listShape,
            String xmlVar,
            SymbolProvider sp) {
        String element = BeamXmlBindingIndex.memberElementName(member);
        String itemElement = BeamXmlBindingIndex.listItemElementName(member, listShape, model);
        String listNameExpr = "<<" + "\"" + element + "\"" + ">>";
        Shape listMember = model.expectShape(listShape.getMember().getTarget());
        if (listMember instanceof StructureShape nested) {
            String itemRecord = decodeStructureFromXml(model, nested, "Item", sp);
            return "xml_child_struct_list(" + xmlVar + ", " + listNameExpr + ", <<\""
                    + itemElement + "\">>, fun(Item) -> " + itemRecord + " end)";
        }
        return "xml_child_list(" + xmlVar + ", " + listNameExpr + ", <<\"" + itemElement + "\">>)";
    }

    private static void emitStructureFieldsFromXml(
            ErlangWriter writer,
            Model model,
            StructureShape structure,
            String xmlVar,
            SymbolProvider sp,
            String indent) {

        for (MemberShape member : structure.members()) {
            String field = BeamNameUtils.toSnakeCase(member.getMemberName());
            Shape target = model.expectShape(member.getTarget());
            if (BeamXmlBindingIndex.isXmlAttribute(member)) {
                writer.write(indent + "$L = xml_attribute($L, <<\"$L\">>),",
                        toBindingVar(field), xmlVar, BeamXmlBindingIndex.memberElementName(member));
            } else if (target instanceof ListShape listShape) {
                writer.write(indent + "$L = $L,",
                        toBindingVar(field),
                        decodeListFieldFromXml(model, member, listShape, xmlVar, sp));
            } else if (target instanceof StructureShape nested) {
                String element = BeamXmlBindingIndex.memberElementName(member);
                writer.write(indent + "$L = case find_element(<<\"$L\">>, element_content($L)) of",
                        toBindingVar(field), element, xmlVar);
                writer.indent();
                writer.write("undefined -> undefined;");
                writer.write("Nested -> $L", decodeStructureFromXml(model, nested, "Nested", sp));
                writer.dedent();
            } else {
                writer.write(indent + "$L = xml_child_text($L, <<\"$L\">>),",
                        toBindingVar(field), xmlVar, BeamXmlBindingIndex.memberElementName(member));
            }
        }
    }

    private static void emitXmlDecodeHelpers(ErlangWriter writer) {
        writer.write("parse_xml_root(Body, RootName) ->");
        writer.indent();
        writer.write("try");
        writer.indent();
        writer.write("{Xml, _} = xmerl_scan:string(binary_to_list(Body)),");
        writer.write("case xml_element_named(Xml, RootName) of");
        writer.indent();
        writer.write("true -> {ok, Xml};");
        writer.write("false ->");
        writer.indent();
        writer.write("case find_element(RootName, element_content(Xml)) of");
        writer.indent();
        writer.write("undefined -> {error, {missing_root, RootName}};");
        writer.write("Root -> {ok, Root}");
        writer.dedent();
        writer.write("end");
        writer.dedent();
        writer.write("end");
        writer.dedent();
        writer.write("catch");
        writer.indent();
        writer.write("_:Reason -> {error, {xml_parse_error, Reason}}");
        writer.dedent();
        writer.write("end.");
        writer.dedent();
        writer.write("");
        writer.write("xml_element_named(Element, Name) ->");
        writer.indent();
        writer.write("is_element(Element) andalso element_name(Element) =:= Name.");
        writer.dedent();
        writer.write("");
        writer.write("element_content({xmlElement, _, _, _, _, _, _, _, Content, _, _, _}) -> Content;");
        writer.write("element_content({_, _, Content, _, _, _}) when is_list(Content) -> Content;");
        writer.write("element_content([H | _]) -> element_content(H);");
        writer.write("element_content(_) -> [].");
        writer.write("");
        writer.write("find_element(Name, Content) ->");
        writer.indent();
        writer.write("case [C || C <- Content, is_element(C), element_name(C) =:= Name] of");
        writer.indent();
        writer.write("[Element | _] -> Element;");
        writer.write("[] -> undefined");
        writer.dedent();
        writer.write("end.");
        writer.dedent();
        writer.write("");
        writer.write("is_element({xmlElement, _, _, _, _, _, _, _, _, _, _, _}) -> true;");
        writer.write("is_element({_, _, Content, _, _, _}) when is_list(Content) -> true;");
        writer.write("is_element(_) -> false.");
        writer.write("");
        writer.write("element_name({xmlElement, Name, _, _, _, _, _, _, _, _, _, _}) when is_atom(Name) ->");
        writer.indent();
        writer.write("list_to_binary(atom_to_list(Name));");
        writer.dedent();
        writer.write("element_name({xmlElement, Name, _, _, _, _, _, _, _, _, _, _}) when is_list(Name) ->");
        writer.indent();
        writer.write("list_to_binary(Name);");
        writer.dedent();
        writer.write("element_name({xmlElement, Name, _, _, _, _, _, _, _, _, _, _}) when is_binary(Name) -> Name;");
        writer.write("element_name({Name, _, _, _, _, _}) when is_atom(Name) -> list_to_binary(atom_to_list(Name));");
        writer.write("element_name({Name, _, _, _, _, _}) when is_list(Name) -> list_to_binary(Name);");
        writer.write("element_name({Name, _, _, _, _, _}) when is_binary(Name) -> Name.");
        writer.write("");
        writer.write("xml_child_text(Parent, Name) ->");
        writer.indent();
        writer.write("case find_element(Name, element_content(Parent)) of");
        writer.indent();
        writer.write("undefined -> undefined;");
        writer.write("Element ->");
        writer.indent();
        writer.write("case element_text(Element) of");
        writer.indent();
        writer.write("[] -> undefined;");
        writer.write("Text -> list_to_binary(Text)");
        writer.dedent();
        writer.write("end");
        writer.dedent();
        writer.dedent();
        writer.write("end.");
        writer.dedent();
        writer.write("");
        writer.write("element_text({xmlElement, _, _, _, _, _, _, _, Content, _, _, _}) ->");
        writer.indent();
        writer.write("xml_text_values(Content);");
        writer.dedent();
        writer.write("element_text({_, _, Content, _, _, _}) when is_list(Content) ->");
        writer.indent();
        writer.write("[T || T <- Content, is_list(T), not is_element_string(T)];");
        writer.dedent();
        writer.write("element_text(_) -> [].");
        writer.write("");
        writer.write("xml_text_values(Content) ->");
        writer.indent();
        writer.write("lists:flatten([case C of");
        writer.indent();
        writer.write("{xmlText, _, _, _, V, _} when is_list(V) -> V;");
        writer.write("{xmlText, _, _, _, V, _} when is_binary(V) -> binary_to_list(V);");
        writer.write("_ -> []");
        writer.dedent();
        writer.write("end || C <- Content]).");
        writer.dedent();
        writer.write("");
        writer.write("is_element_string(T) when is_list(T) ->");
        writer.indent();
        writer.write("case T of");
        writer.indent();
        writer.write("{xmlElement, _, _, _, _, _, _, _, _, _, _, _} -> true;");
        writer.write("{_, _, _, _, _, _} -> true;");
        writer.write("_ -> false");
        writer.dedent();
        writer.write("end;");
        writer.dedent();
        writer.write("is_element_string(_) -> false.");
        writer.write("");
        writer.write("xml_attribute(Element, AttrName) ->");
        writer.indent();
        writer.write("case proplists:get_value(AttrName, element(Element, 2), undefined) of");
        writer.indent();
        writer.write("undefined -> undefined;");
        writer.write("Value -> list_to_binary(Value)");
        writer.dedent();
        writer.write("end.");
        writer.dedent();
        writer.write("");
        writer.write("xml_child_list(Parent, undefined, ItemName) ->");
        writer.indent();
        writer.write("[ItemText || Item <- element_content(Parent),");
        writer.write("             is_element(Item),");
        writer.write("             element_name(Item) =:= ItemName,");
        writer.write("             ItemText <- [list_to_binary(element_text(Item))],");
        writer.write("             ItemText =/= <<>>];");
        writer.dedent();
        writer.write("xml_child_list(Parent, ListName, ItemName) ->");
        writer.indent();
        writer.write("case find_element(ListName, element_content(Parent)) of");
        writer.indent();
        writer.write("undefined -> undefined;");
        writer.write("ListElement ->");
        writer.indent();
        writer.write("[ItemText || Item <- element_content(ListElement),");
        writer.write("             is_element(Item),");
        writer.write("             element_name(Item) =:= ItemName,");
        writer.write("             ItemText <- [list_to_binary(element_text(Item))],");
        writer.write("             ItemText =/= <<>>]");
        writer.dedent();
        writer.dedent();
        writer.write("end.");
        writer.dedent();
        writer.write("");
        writer.write("xml_child_struct_list(Parent, undefined, ItemName, DecodeFun) ->");
        writer.indent();
        writer.write("[DecodeFun(Item) || Item <- element_content(Parent),");
        writer.write("                    is_element(Item),");
        writer.write("                    element_name(Item) =:= ItemName];");
        writer.dedent();
        writer.write("xml_child_struct_list(Parent, ListName, ItemName, DecodeFun) ->");
        writer.indent();
        writer.write("case find_element(ListName, element_content(Parent)) of");
        writer.indent();
        writer.write("undefined -> undefined;");
        writer.write("ListElement ->");
        writer.indent();
        writer.write("[DecodeFun(Item) || Item <- element_content(ListElement),");
        writer.write("                    is_element(Item),");
        writer.write("                    element_name(Item) =:= ItemName]");
        writer.dedent();
        writer.dedent();
        writer.write("end.");
        writer.dedent();
        writer.write("");
        writer.write("decode_rest_xml_error(Status, Body) ->");
        writer.indent();
        writer.write("try");
        writer.indent();
        writer.write("{Xml, _} = xmerl_scan:string(binary_to_list(Body)),");
        writer.write("case find_element(<<\"ErrorResponse\">>, element_content(Xml)) of");
        writer.indent();
        writer.write("undefined -> {error, {unknown_error, Status, Body}};");
        writer.write("ErrorResponse ->");
        writer.indent();
        writer.write("case find_element(<<\"Error\">>, element_content(ErrorResponse)) of");
        writer.indent();
        writer.write("undefined -> {error, {unknown_error, Status, Body}};");
        writer.write("Error ->");
        writer.indent();
        writer.write("{error, {xml_child_text(Error, <<\"Code\">>), xml_child_text(Error, <<\"Message\">>)}}");
        writer.dedent();
        writer.write("end");
        writer.dedent();
        writer.write("end");
        writer.dedent();
        writer.write("catch");
        writer.indent();
        writer.write("_:Reason -> {error, {unknown_error, Status, Body}}");
        writer.dedent();
        writer.write("end.");
        writer.dedent();
        writer.write("");
    }

    private static void emitServiceXmlNamespace(ErlangWriter writer, Optional<String> namespaceUri) {
        if (namespaceUri.isPresent()) {
            writer.write("xml_namespace() -> #{uri => <<\"$L\">>}.", namespaceUri.get());
        } else {
            writer.write("xml_namespace() -> #{}.");
        }
        writer.write("");
    }

    private static void emitEncoder(
            ErlangWriter writer,
            Model model,
            ServiceShape service,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp,
            boolean encodeWithConfig) {

        String opName = sp.toSymbol(op).getName();
        StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
        String inputRecord = recordName(sp.toSymbol(input));
        String inputType = sp.toSymbol(input).getName();
        HttpTrait httpTrait = op.expectTrait(HttpTrait.class);
        String method = httpTrait.getMethod();
        String uriTemplate = httpTrait.getUri().toString();

        List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
        List<HttpBinding> queries = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY);
        List<HttpBinding> queryParams = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY_PARAMS);
        List<HttpBinding> headers = httpIndex.getRequestBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> prefixHeaders = httpIndex.getRequestBindings(op, HttpBinding.Location.PREFIX_HEADERS);
        List<HttpBinding> payloadMembers = httpIndex.getRequestBindings(op, HttpBinding.Location.PAYLOAD);

        String requestContentType = resolvedRequestContentType(model, op, payloadMembers);

        List<String> patternParts = buildPatternParts(labels, queries, queryParams, headers, prefixHeaders, payloadMembers);
        String pattern = patternParts.isEmpty() ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

        writer.write("%% Encode REST-XML request for $L.", op.getId());
        if (encodeWithConfig) {
            ErlangFormat.writeSpec(
                    writer,
                    "encode_" + opName + "_request(client_config(), " + inputType + ") -> #http_request{}");
            writer.write("encode_$L_request(Config, Input = #$L{$L}) ->", opName, inputRecord, pattern);
        } else {
            ErlangFormat.writeSpec(writer, "encode_" + opName + "_request(" + inputType + ") -> #http_request{}");
            writer.write("encode_$L_request(Input = #$L{$L}) ->", opName, inputRecord, pattern);
        }
        writer.indent();

        List<MemberShape> idempotencyMembers = input.members().stream()
                .filter(m -> m.hasTrait(IdempotencyTokenTrait.class))
                .collect(Collectors.toList());
        if (!idempotencyMembers.isEmpty()) {
            String currentInput = "Input";
            int step = 1;
            for (MemberShape member : idempotencyMembers) {
                String field = BeamNameUtils.toSnakeCase(member.getMemberName());
                String nextInput = "Input" + step;
                writer.write("$L = case $L#$L of", nextInput, currentInput, field);
                writer.indent();
                writer.write("undefined -> $L#$L{ $L = generate_uuid() };", currentInput, inputRecord, field);
                writer.write("_ -> $L", currentInput);
                writer.dedent();
                writer.write("end,");
                currentInput = nextInput;
                step++;
            }
            for (MemberShape member : idempotencyMembers) {
                String field = BeamNameUtils.toSnakeCase(member.getMemberName());
                writer.write("$L = $L#$L,", toBindingVar(field), currentInput, field);
            }
        }

        BeamHostLabelIndex hostLabelIndex = BeamHostLabelIndex.of(model);
        boolean hasHostLabels = !hostLabelIndex.hostLabelMembers(op).isEmpty()
                && op.hasTrait(EndpointTrait.class);
        BeamS3CustomizationIndex s3Index = BeamS3CustomizationIndex.of(model);
        boolean s3BucketAddressing = s3Index.isS3Service(service)
                && s3Index.bucketLabelBinding(op).isPresent();

        if (s3BucketAddressing) {
            String bucketVar = toBindingVar(s3Index.bucketMemberSnakeCase(op));
            String keyVar = s3Index.keyMemberSnakeCase(op)
                    .map(ErlangRestXmlEmitter::toBindingVar)
                    .orElse("<<>>");
            if (encodeWithConfig) {
                writer.write("{Host, Path} = s3_endpoint:resolve_bucket_url(Config, $L, $L),",
                        bucketVar, keyVar);
            } else {
                writer.write("{Host, Path} = s3_endpoint:resolve_bucket_url(#{}, $L, $L),",
                        bucketVar, keyVar);
            }
        } else {
            String pathExpr = buildPathExpression(uriTemplate, labels);
            writer.write("Path = $L,", pathExpr);
        }

        if (queries.isEmpty()) {
            writer.write("Query = [],");
        } else {
            writer.write("Query = lists:filtermap(fun");
            for (HttpBinding qb : queries) {
                String paramName = qb.getLocationName();
                writer.write("    (V) when V =/= undefined -> {true, {<<\"$L\">>, encode_query_value(V)}};",
                        paramName);
            }
            writer.write("    (_) -> false");
            writer.write("end, [$L]),",
                    queries.stream()
                            .map(qb -> toBindingVar(
                                    BeamNameUtils.toSnakeCase(qb.getMember().getMemberName())))
                            .collect(Collectors.joining(", ")));
        }

        if (!queryParams.isEmpty()) {
            for (HttpBinding qp : queryParams) {
                String fieldName = BeamNameUtils.toSnakeCase(qp.getMember().getMemberName());
                String bindingVar = toBindingVar(fieldName);
                writer.write("QueryExtra = case $L of", bindingVar);
                writer.indent();
                writer.write("undefined -> [];");
                writer.write("M when is_map(M) ->");
                writer.indent();
                writer.write("[{K, V} || {K, V} <- maps:to_list(M)]");
                writer.dedent();
                writer.dedent();
                writer.write("end,");
                writer.write("Query = Query ++ QueryExtra,");
            }
        }

        if (headers.isEmpty()) {
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"$L\">>}],", requestContentType);
        } else {
            writer.write("Headers0 = lists:filtermap(fun");
            for (HttpBinding hb : headers) {
                String headerName = hb.getLocationName();
                writer.write("    (V) when V =/= undefined -> {true, {<<\"$L\">>, to_binary(V)}};",
                        headerName);
            }
            writer.write("    (_) -> false");
            writer.write("end, [$L]),",
                    headers.stream()
                            .map(hb -> toBindingVar(
                                    BeamNameUtils.toSnakeCase(hb.getMember().getMemberName())))
                            .collect(Collectors.joining(", ")));
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"$L\">>} | Headers0],", requestContentType);
        }

        for (HttpBinding ph : prefixHeaders) {
            String fieldName = BeamNameUtils.toSnakeCase(ph.getMember().getMemberName());
            String prefix = ph.getLocationName();
            writer.write("Headers = Headers ++ prefix_headers_to_list(<<\"$L\">>, $L),",
                    prefix, toBindingVar(fieldName));
        }

        emitRequestBody(writer, model, payloadMembers, method, sp);
        ErlangHttpChecksumEmitter.emitRequestChecksumHeaders(writer, model, op, sp);

        if (hasHostLabels && !s3BucketAddressing) {
            writer.write("Host = build_host(Input, Config),");
        }

        writer.write("#http_request{");
        writer.write("    method = <<\"$L\">>,", method);
        writer.write("    path = Path,");
        writer.write("    query = maps:from_list(Query),");
        writer.write("    headers = Headers,");
        writer.write("    body = Body");
        if (hasHostLabels || s3BucketAddressing) {
            writer.write("    ,host = Host");
        }
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    private static void emitRequestBody(
            ErlangWriter writer,
            Model model,
            List<HttpBinding> payloadMembers,
            String method,
            SymbolProvider sp) {

        if (payloadMembers.isEmpty()
                || method.equals("GET")
                || method.equals("DELETE")
                || method.equals("HEAD")) {
            writer.write("Body = <<>>,");
            return;
        }

        HttpBinding payload = payloadMembers.get(0);
        MemberShape member = payload.getMember();
        Shape target = model.expectShape(member.getTarget());
        String fieldName = BeamNameUtils.toSnakeCase(member.getMemberName());
        String bindingVar = toBindingVar(fieldName);

        if (target instanceof BlobShape || target instanceof StringShape) {
            writer.write("Body = case $L of", bindingVar);
            writer.indent();
            writer.write("undefined -> <<>>;");
            writer.write("Value -> Value");
            writer.dedent();
            writer.write("end,");
            return;
        }

        String rootElement = BeamXmlBindingIndex.payloadRootElementName(member, target);
        writer.write("XmlNs = xml_namespace(),");
        writer.write("Body = case $L of", bindingVar);
        writer.indent();
        writer.write("undefined -> <<>>;");
        writer.write("PayloadValue ->");
        writer.indent();
        if (target instanceof StructureShape structure) {
            writer.write("MemberMap = $L,",
                    buildStructureXmlMap(model, structure, "PayloadValue", recordName(sp.toSymbol(structure))));
            writer.write("Payload = encode_xml(#{<<\"$L\">> => MemberMap}, XmlNs),", rootElement);
        } else {
            writer.write("Payload = encode_xml(#{<<\"$L\">> => PayloadValue}, XmlNs),", rootElement);
        }
        writer.write("Payload");
        writer.dedent();
        writer.dedent();
        writer.write("end,");
    }

    private static String buildStructureXmlMap(
            Model model, StructureShape structure, String recordVar, String recordTag) {
        List<String> entries = new ArrayList<>();
        for (MemberShape member : structure.members()) {
            if (BeamXmlBindingIndex.isXmlAttribute(member)) {
                continue;
            }
            String field = BeamNameUtils.toSnakeCase(member.getMemberName());
            String wireName = BeamXmlBindingIndex.memberElementName(member);
            entries.add("<<\"" + wireName + "\">> => " + recordVar + "#" + recordTag + "." + field);
        }
        if (entries.isEmpty()) {
            return "#{}" ;
        }
        return "#{" + String.join(", ", entries) + "}";
    }

    private static void emitXmlEncodeHelpers(ErlangWriter writer) {
        writer.write("encode_xml(RootMap, XmlNs) ->");
        writer.indent();
        writer.write("[{RootName, Content}] = maps:to_list(RootMap),");
        writer.write("Element = build_xml_element(RootName, Content, XmlNs),");
        writer.write("iolist_to_binary(xmerl:export_simple([Element], xmerl_xmlns, [], [{prolog, false}])).");
        writer.dedent();
        writer.write("");
        writer.write("build_xml_element(Name, Content, XmlNs) when is_map(Content) ->");
        writer.indent();
        writer.write("Attrs = xml_namespace_attrs(XmlNs),");
        writer.write("Children = [build_xml_child(K, V) || {K, V} <- maps:to_list(Content), V =/= undefined],");
        writer.write("{Name, Attrs, Children};");
        writer.dedent();
        writer.write("build_xml_element(Name, Content, XmlNs) ->");
        writer.indent();
        writer.write("{Name, xml_namespace_attrs(XmlNs), [{text, to_binary(Content)}]}.");
        writer.dedent();
        writer.write("");
        writer.write("build_xml_child(Name, Value) when is_map(Value) ->");
        writer.indent();
        writer.write("{Name, [], [build_xml_element(K, V, #{}) || {K, V} <- maps:to_list(Value), V =/= undefined]};");
        writer.dedent();
        writer.write("build_xml_child(Name, Values) when is_list(Values) ->");
        writer.indent();
        writer.write("{Name, [], [build_xml_element(<<\"member\">>, V, #{}) || V <- Values, V =/= undefined]};");
        writer.dedent();
        writer.write("build_xml_child(Name, Value) ->");
        writer.indent();
        writer.write("{Name, [], [{text, to_binary(Value)}]}.");
        writer.dedent();
        writer.write("");
        writer.write("xml_namespace_attrs(#{uri := Uri}) -> [{xmlns, Uri}];");
        writer.write("xml_namespace_attrs(#{uri := Uri, prefix := Prefix}) ->");
        writer.indent();
        writer.write("[{'xmlns:' ++ binary_to_list(Prefix), Uri}];");
        writer.dedent();
        writer.write("xml_namespace_attrs(_) -> [].");
        writer.write("");
        writer.write("encode_query_value(V) when is_integer(V) -> integer_to_binary(V);");
        writer.write("encode_query_value(V) when is_float(V) -> float_to_binary(V, [short]);");
        writer.write("encode_query_value(V) when is_boolean(V) -> atom_to_binary(V, utf8);");
        writer.write("encode_query_value(V) -> to_binary(V).");
        writer.write("");
        writer.write("to_binary(V) when is_binary(V) -> V;");
        writer.write("to_binary(V) when is_list(V) -> list_to_binary(V);");
        writer.write("to_binary(V) when is_atom(V) -> atom_to_binary(V, utf8);");
        writer.write("to_binary(V) when is_integer(V) -> integer_to_binary(V);");
        writer.write("to_binary(V) when is_float(V) -> float_to_binary(V, [short]);");
        writer.write("to_binary(V) when is_boolean(V) -> atom_to_binary(V, utf8).");
        writer.write("");
    }

    private static void emitBuildHostHelpers(
            ErlangWriter writer, Model model, ServiceShape service, SymbolProvider sp) {
        writer.write("split_base_url(BaseUrl) ->");
        writer.indent();
        writer.write("case uri_string:parse(binary_to_list(BaseUrl)) of");
        writer.indent();
        writer.write("#{scheme := Scheme, host := Host} = Parts ->");
        writer.indent();
        writer.write("PortSuffix = case maps:get(port, Parts, undefined) of");
        writer.indent();
        writer.write("undefined -> <<>>;");
        writer.write("Port -> <<\":\", (integer_to_binary(Port))/binary>>");
        writer.dedent();
        writer.write("end,");
        writer.write("{<< (list_to_binary(Scheme))/binary, \"://\">>,");
        writer.write(" << (list_to_binary(Host))/binary, PortSuffix/binary >>};");
        writer.dedent();
        writer.write("_ ->");
        writer.indent();
        writer.write("{<<>>, BaseUrl}");
        writer.dedent();
        writer.dedent();
        writer.write("end.");
        writer.dedent();
        writer.write("");

        BeamHostLabelIndex hostLabelIndex = BeamHostLabelIndex.of(model);
        for (OperationShape op : ErlangTopDown.containedOperationsSorted(model, service)) {
            List<MemberShape> hostLabels = hostLabelIndex.hostLabelMembers(op);
            if (hostLabels.isEmpty() || !op.hasTrait(EndpointTrait.class)) {
                continue;
            }
            StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
            String inputRecord = recordName(sp.toSymbol(input));
            SmithyPattern hostPrefix = op.expectTrait(EndpointTrait.class).getHostPrefix();
            String prefixExpr = buildHostPrefixExpression(hostPrefix);
            List<String> patternParts = hostLabels.stream()
                    .map(m -> {
                        String field = BeamNameUtils.toSnakeCase(m.getMemberName());
                        return field + " = " + toBindingVar(field);
                    })
                    .toList();
            String pattern = patternParts.isEmpty()
                    ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

            writer.write("build_host(#$L{$L}, Config) ->", inputRecord, pattern);
            writer.indent();
            writer.write("BaseUrl = maps:get(base_url, Config, <<>>),");
            writer.write("{_Scheme, Authority} = split_base_url(BaseUrl),");
            writer.write("Prefix = $L,", prefixExpr);
            writer.write("<<Prefix/binary, Authority/binary>>.");
            writer.dedent();
            writer.write("");
        }
    }

    public static boolean serviceHasHostLabelOperations(Model model, ServiceShape service) {
        BeamHostLabelIndex hostLabelIndex = BeamHostLabelIndex.of(model);
        for (OperationShape op : ErlangTopDown.containedOperationsSorted(model, service)) {
            if (!hostLabelIndex.hostLabelMembers(op).isEmpty() && op.hasTrait(EndpointTrait.class)) {
                return true;
            }
        }
        return false;
    }

    public static boolean serviceEncodesWithConfig(Model model, ServiceShape service) {
        return serviceHasHostLabelOperations(model, service)
                || BeamS3CustomizationIndex.of(model).serviceUsesBucketAddressing(service);
    }

    private static String recordName(Symbol symbol) {
        return symbol.getName().replace("()", "");
    }

    private static List<String> buildPatternParts(
            List<HttpBinding> labels,
            List<HttpBinding> queries,
            List<HttpBinding> queryParams,
            List<HttpBinding> headers,
            List<HttpBinding> prefixHeaders,
            List<HttpBinding> payloadMembers) {
        List<String> parts = new ArrayList<>();
        for (HttpBinding b : concat(labels, queries, queryParams, headers, prefixHeaders, payloadMembers)) {
            String field = BeamNameUtils.toSnakeCase(b.getMember().getMemberName());
            parts.add(field + " = " + toBindingVar(field));
        }
        return parts;
    }

    private static String toBindingVar(String snakeField) {
        return BeamNameUtils.toCamelCaseVariable(snakeField);
    }

    @SafeVarargs
    private static <T> List<T> concat(List<T>... lists) {
        List<T> out = new ArrayList<>();
        for (List<T> l : lists) {
            out.addAll(l);
        }
        return out;
    }

    private static String buildPathExpression(String uriTemplate, List<HttpBinding> labels) {
        if (labels.isEmpty()) {
            return "<<\"" + uriTemplate + "\">>";
        }
        StringBuilder sb = new StringBuilder("<<");
        int pos = 0;
        while (pos < uriTemplate.length()) {
            int start = uriTemplate.indexOf('{', pos);
            if (start < 0) {
                sb.append("\"").append(uriTemplate.substring(pos)).append("\"");
                break;
            }
            if (start > pos) {
                sb.append("\"").append(uriTemplate, pos, start).append("\", ");
            }
            int end = uriTemplate.indexOf('}', start);
            String labelName = uriTemplate.substring(start + 1, end);
            String fieldName = BeamNameUtils.toSnakeCase(labelName);
            sb.append("(uri_encode(to_binary(").append(toBindingVar(fieldName)).append(")))/binary");
            pos = end + 1;
            if (pos < uriTemplate.length()) {
                sb.append(", ");
            }
        }
        sb.append(">>");
        return sb.toString();
    }

    private static String buildHostPrefixExpression(SmithyPattern hostPrefix) {
        if (hostPrefix.getSegments().isEmpty()) {
            return "<<>>";
        }
        StringBuilder sb = new StringBuilder("<<");
        List<SmithyPattern.Segment> segments = hostPrefix.getSegments();
        for (int i = 0; i < segments.size(); i++) {
            SmithyPattern.Segment segment = segments.get(i);
            if (segment.isLabel()) {
                String fieldName = BeamNameUtils.toSnakeCase(segment.getContent());
                sb.append("(uri_encode(to_binary(")
                        .append(toBindingVar(fieldName))
                        .append(")))/binary");
            } else {
                sb.append("\"").append(segment.getContent()).append("\"");
            }
            if (i < segments.size() - 1) {
                sb.append(", ");
            }
        }
        sb.append(">>");
        return sb.toString();
    }

    private static String resolvedRequestContentType(
            Model model, OperationShape op, List<HttpBinding> payloadMembers) {
        if (!payloadMembers.isEmpty()) {
            MemberShape member = payloadMembers.get(0).getMember();
            Shape target = model.expectShape(member.getTarget());
            Optional<String> mediaType = member.getTrait(MediaTypeTrait.class)
                    .map(MediaTypeTrait::getValue);
            if (mediaType.isPresent()) {
                return mediaType.get();
            }
            if (target instanceof BlobShape) {
                return "application/octet-stream";
            }
            if (target instanceof StringShape) {
                return "text/plain";
            }
        }
        return BeamHttpBindings.from(model)
                .requestContentType(op, DEFAULT_CONTENT_TYPE)
                .orElse(DEFAULT_CONTENT_TYPE);
    }
}
