package io.smithy.beam.erlang;

import io.beam.dsl.erlang.AtomExpr;
import io.beam.dsl.erlang.AtomPattern;
import io.beam.dsl.erlang.Function;
import io.beam.dsl.erlang.FunctionClause;
import io.beam.dsl.erlang.InfixExpr;
import io.beam.dsl.erlang.IsTypeGuard;
import io.beam.dsl.erlang.ListComprehensionExpr;
import io.beam.dsl.erlang.LocalCallExpr;
import io.beam.dsl.erlang.Module;
import io.beam.dsl.erlang.TypeAlias;
import io.beam.dsl.erlang.Variable;
import io.beam.dsl.erlang.VariablePattern;
import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.core.BeamRequestCompressionIndex;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBinding;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.EnumShape;
import software.amazon.smithy.model.shapes.IntEnumShape;
import software.amazon.smithy.model.shapes.MapShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.StructureShape;
import software.amazon.smithy.model.shapes.UnionShape;

final class ErlangRestJsonDsl {
  private ErlangRestJsonDsl() {}

  static String clientCodecFileName(ErlangContext ctx, ServiceShape service) {
    return layout(ctx, service).codecModuleName(ctx.resolvedProtocolTraitId()) + ".erl";
  }

  static String serverCodecFileName(ErlangContext ctx, ServiceShape service) {
    return layout(ctx, service).codecModuleName(ctx.resolvedProtocolTraitId()) + ".erl";
  }

  static Module buildClientCodecModule(ErlangContext ctx, ServiceShape service) {
    Model model = ctx.model();
    ShapeId protocol = ctx.resolvedProtocolTraitId();
    BeamErlangLayout layout = layout(ctx, service);
    HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
    SymbolProvider sp = ctx.symbolProvider();
    List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
    boolean encodeWithConfig = ErlangRestJsonSupport.serviceHasHostLabelOperations(model, service);

    List<String> exports = new ArrayList<>();
    for (OperationShape op : operations) {
      String name = sp.toSymbol(op).getName();
      List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
      exports.add("encode_" + name + "_request/" + (encodeWithConfig ? "2" : "1"));
      exports.add("decode_" + name + "_request/" + (labels.isEmpty() ? "1" : "2"));
      exports.add("decode_" + name + "_response/1");
    }

    List<Function> functions =
        clientCodecFunctions(model, service, operations, httpIndex, sp, layout, encodeWithConfig);

    return Module.of(
        layout.codecModuleName(protocol),
        functions,
        List.of(
            "REST JSON 1 codecs for " + service.getId() + " (generated).",
            "DO NOT EDIT -- generated by smithy-beam codegen."),
        null,
        List.of(layout.typesHeaderFile(), layout.runtimeTypesHeaderFile()),
        encodeWithConfig ? List.of(TypeAlias.of("client_config", "#{binary() => term()}")) : null,
        exports);
  }

  static Module buildServerCodecModule(ErlangContext ctx, ServiceShape service) {
    Model model = ctx.model();
    ShapeId protocol = ctx.resolvedProtocolTraitId();
    BeamErlangLayout layout = layout(ctx, service);
    HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
    SymbolProvider sp = ctx.symbolProvider();

    List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
    List<String> exports = new ArrayList<>();
    Set<ShapeId> errorIds = new LinkedHashSet<>();
    for (OperationShape op : operations) {
      String name = sp.toSymbol(op).getName();
      List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
      exports.add("decode_" + name + "_request/" + (labels.isEmpty() ? "1" : "2"));
      exports.add("encode_" + name + "_response/1");
      errorIds.addAll(op.getErrors());
    }
    for (ShapeId errorId : errorIds) {
      StructureShape errShape = model.expectShape(errorId, StructureShape.class);
      exports.add(
          "encode_" + ErlangRestJsonSupport.recordName(sp.toSymbol(errShape)) + "_response/1");
    }

    List<Function> functions =
        serverCodecFunctions(model, service, operations, httpIndex, sp, layout);

    return Module.of(
        layout.codecModuleName(protocol),
        functions,
        List.of(
            "Server REST JSON 1 codecs for " + service.getId() + " (generated).",
            "DO NOT EDIT -- generated by smithy-beam codegen."),
        null,
        List.of(layout.typesHeaderFile(), layout.runtimeTypesHeaderFile()),
        null,
        exports);
  }

  static void emitClientCodecModule(ErlangContext ctx, ServiceShape service) {
    Module module = buildClientCodecModule(ctx, service);
    ErlangCodecEmission.writeModule(ctx, clientCodecFileName(ctx, service), module);
  }

  static void emitServerCodecModule(ErlangContext ctx, ServiceShape service) {
    Module module = buildServerCodecModule(ctx, service);
    ErlangCodecEmission.writeModule(ctx, serverCodecFileName(ctx, service), module);
  }

  private static BeamErlangLayout layout(ErlangContext ctx, ServiceShape service) {
    return new BeamErlangLayout(ctx.settings(), service.getId().getNamespace(), service);
  }

  static Function encodeRequest(
      Model model,
      ServiceShape service,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      boolean encodeWithConfig,
      String eventStreamModule) {
    return ErlangRestJsonOperationDsl.buildEncodeRequest(
        model, service, op, httpIndex, sp, encodeWithConfig, eventStreamModule);
  }

  static Function decodeRequest(
      Model model,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      String eventStreamModule) {
    return ErlangRestJsonOperationDsl.buildDecodeRequest(
        model, op, httpIndex, sp, eventStreamModule);
  }

  static Function decodeResponse(
      Model model,
      ServiceShape service,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      BeamErlangLayout layout) {
    return ErlangRestJsonOperationDsl.buildDecodeResponse(
        model, service, op, httpIndex, sp, layout);
  }

  static Function errorDispatch(
      Model model,
      ServiceShape service,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp) {
    return ErlangRestJsonOperationDsl.buildErrorDispatch(model, service, op, httpIndex, sp);
  }

  static List<Function> structureHelperFunctions(
      Model model, ServiceShape service, SymbolProvider sp) {
    List<Function> functions = new ArrayList<>();
    Set<StructureShape> structures = new LinkedHashSet<>();
    Set<StructureShape> listElementStructures = new LinkedHashSet<>();
    HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
    ErlangRestJsonSupport.collectStructureHelperTargets(
        model, service, httpIndex, structures, listElementStructures);
    for (StructureShape structure : structures) {
      functions.addAll(
          ErlangStructureHelperDsl.structureDecodeEncode(model, httpIndex, structure, sp));
      if (listElementStructures.contains(structure)) {
        functions.addAll(buildStructureListDecodeEncodeFunctions(structure, sp));
      }
    }
    return functions;
  }

  static List<Function> buildStructureDecodeEncode(
      Model model, HttpBindingIndex httpIndex, StructureShape structure, SymbolProvider sp) {
    return ErlangStructureHelperDsl.structureDecodeEncode(model, httpIndex, structure, sp);
  }

  static List<Function> buildStructureListDecodeEncodeFunctions(
      StructureShape structure, SymbolProvider sp) {
    String helperName = ErlangJsonCodecSupport.structureHelperName(sp, structure);
    return List.of(buildStructureListDecode(helperName), buildStructureListEncode(helperName));
  }

  private static Function buildStructureListDecode(String helperName) {
    return Function.of(
        "decode_" + helperName + "_list",
        List.of(
            FunctionClause.of(List.of(AtomPattern.of("undefined")), AtomExpr.of("undefined")),
            FunctionClause.of(List.of(AtomPattern.of("null")), AtomExpr.of("undefined")),
            FunctionClause.of(
                List.of(VariablePattern.of("List")),
                IsTypeGuard.of("list", Variable.of("List")),
                ListComprehensionExpr.of(
                    LocalCallExpr.of("decode_" + helperName, List.of(Variable.of("V"))),
                    VariablePattern.of("V"),
                    Variable.of("List"),
                    InfixExpr.of(Variable.of("V"), "=/=", AtomExpr.of("null"))))));
  }

  private static Function buildStructureListEncode(String helperName) {
    return Function.of(
        "encode_" + helperName + "_list",
        List.of(
            FunctionClause.of(List.of(AtomPattern.of("undefined")), AtomExpr.of("undefined")),
            FunctionClause.of(
                List.of(VariablePattern.of("List")),
                IsTypeGuard.of("list", Variable.of("List")),
                ListComprehensionExpr.of(
                    LocalCallExpr.of("encode_" + helperName, List.of(Variable.of("V"))),
                    VariablePattern.of("V"),
                    Variable.of("List"),
                    InfixExpr.of(Variable.of("V"), "=/=", AtomExpr.of("undefined"))))));
  }

  static List<Function> enumHelperFunctions(Model model, ServiceShape service, SymbolProvider sp) {
    List<Function> functions = new ArrayList<>();
    for (EnumShape enumShape : ErlangRestJsonSupport.reachableEnumShapes(model, service)) {
      functions.addAll(ErlangEnumHelperDsl.enumDecodeEncode(enumShape, sp));
    }
    for (IntEnumShape intEnumShape : ErlangRestJsonSupport.reachableIntEnumShapes(model, service)) {
      functions.addAll(ErlangEnumHelperDsl.intEnumDecodeEncode(intEnumShape, sp));
    }
    return functions;
  }

  static List<Function> unionHelperFunctions(Model model, ServiceShape service, SymbolProvider sp) {
    List<Function> functions = new ArrayList<>();
    for (UnionShape union : ErlangRestJsonSupport.reachableUnionShapes(model, service)) {
      functions.addAll(ErlangUnionHelperDsl.unionDecodeEncode(union, sp));
    }
    return functions;
  }

  static List<Function> mapHelperFunctions(Model model, ServiceShape service, SymbolProvider sp) {
    List<Function> functions = new ArrayList<>();
    HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
    for (MapShape map : ErlangRestJsonSupport.reachableTypedMapShapes(model, service)) {
      functions.addAll(ErlangMapHelperDsl.mapDecodeEncode(model, httpIndex, map, sp));
    }
    return functions;
  }

  static List<Function> privateCodecHelpers(Model model, ServiceShape service) {
    List<Function> functions = new ArrayList<>();
    functions.add(ErlangCodecHelperDsl.toBinary(ErlangCodecHelperDsl.ToBinaryVariant.REST_JSON));
    functions.add(ErlangCodecHelperDsl.encodeQueryValueRestJson());
    functions.add(ErlangCodecHelperDsl.uriEncode());
    functions.add(ErlangCodecHelperDsl.uriDecode());
    functions.add(ErlangCodecHelperDsl.decodeQueryParam());
    functions.add(ErlangCodecHelperDsl.prefixHeadersToList());
    functions.add(ErlangCodecHelperDsl.prefixHeadersFromList());
    functions.add(ErlangCodecHelperDsl.decodeJsonBody());
    functions.add(ErlangCodecHelperDsl.contentTypeMatches());
    functions.add(ErlangCodecHelperDsl.ctBase());
    functions.add(ErlangCodecHelperDsl.decodeSparseList());
    functions.add(ErlangCodecHelperDsl.decodeList());
    functions.add(ErlangXmlCodecDsl.decodeSparseMap());
    functions.add(ErlangCodecHelperDsl.encodeSparseList());
    functions.add(ErlangCodecHelperDsl.encodeSparseMap());
    functions.add(ErlangCodecHelperDsl.encodeTimestampEpochSeconds());
    functions.add(ErlangCodecHelperDsl.encodeTimestampDateTime());
    functions.add(ErlangCodecHelperDsl.decodeTimestampEpochSeconds());
    functions.add(ErlangCodecHelperDsl.decodeTimestampDateTime());
    functions.add(ErlangCodecHelperDsl.generateUuid());

    boolean compressionBindings = serviceHasCompressionOperations(model, service);
    if (compressionBindings) {
      functions.add(ErlangCodecHelperDsl.headersSet());
    }
    return functions;
  }

  static boolean serviceHasCompressionOperations(Model model, ServiceShape service) {
    for (OperationShape op : ErlangTopDown.containedOperationsSorted(model, service)) {
      if (supportsGzipCompression(op)) {
        return true;
      }
    }
    return false;
  }

  static boolean supportsGzipCompression(OperationShape op) {
    return BeamRequestCompressionIndex.forOperation(op)
        .map(
            trait ->
                trait.getEncodings().stream()
                    .anyMatch(encoding -> encoding.equalsIgnoreCase("gzip")))
        .orElse(false);
  }

  static List<Function> clientCodecFunctions(
      Model model,
      ServiceShape service,
      List<OperationShape> operations,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      BeamErlangLayout layout,
      boolean encodeWithConfig) {
    List<Function> functions = new ArrayList<>();
    String eventStreamModule = layout.eventStreamModuleName();
    for (OperationShape op : operations) {
      functions.add(
          encodeRequest(model, service, op, httpIndex, sp, encodeWithConfig, eventStreamModule));
      functions.add(decodeRequest(model, op, httpIndex, sp, eventStreamModule));
      functions.add(decodeResponse(model, service, op, httpIndex, sp, layout));
    }
    for (OperationShape op : operations) {
      functions.add(errorDispatch(model, service, op, httpIndex, sp));
    }
    functions.addAll(structureHelperFunctions(model, service, sp));
    functions.addAll(enumHelperFunctions(model, service, sp));
    functions.addAll(unionHelperFunctions(model, service, sp));
    functions.addAll(mapHelperFunctions(model, service, sp));
    functions.addAll(privateCodecHelpers(model, service));
    if (encodeWithConfig) {
      functions.addAll(ErlangHostLabelDsl.buildHostFunctions(model, service, sp));
    }
    return functions;
  }

  static List<Function> serverCodecFunctions(
      Model model,
      ServiceShape service,
      List<OperationShape> operations,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      BeamErlangLayout layout) {
    List<Function> functions = new ArrayList<>();
    String eventStreamModule = layout.eventStreamModuleName();
    Set<ShapeId> emittedErrorEncoders = new LinkedHashSet<>();
    for (OperationShape op : operations) {
      functions.add(decodeRequest(model, op, httpIndex, sp, eventStreamModule));
      functions.add(ErlangRestJsonOperationDsl.buildEncodeResponse(model, op, httpIndex, sp));
      for (ShapeId errorId : op.getErrors()) {
        if (emittedErrorEncoders.add(errorId)) {
          functions.add(ErlangRestJsonOperationDsl.buildErrorResponseEncoder(model, errorId, sp));
        }
      }
    }
    functions.addAll(structureHelperFunctions(model, service, sp));
    functions.addAll(enumHelperFunctions(model, service, sp));
    functions.addAll(unionHelperFunctions(model, service, sp));
    functions.addAll(mapHelperFunctions(model, service, sp));
    functions.addAll(privateCodecHelpers(model, service));
    return functions;
  }
}
