package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.core.BeamNameUtils;
import software.amazon.smithy.codegen.core.Symbol;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBinding;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.StructureShape;
import software.amazon.smithy.model.traits.HttpTrait;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * REST JSON codec scaffolding for Erlang. Emits real encode/decode functions
 * when a REST JSON 1 protocol is selected; keeps codegen-core free of Erlang imports.
 */
public final class ErlangRestJson1Emitter {

    private ErlangRestJson1Emitter() {}

    /** Entry point called from ErlangClientDirectedCodegen#generateService. */
    public static void emitCodecModule(ErlangContext ctx, ServiceShape service) {
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(ctx.settings(), service.getId().getNamespace());
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("encode_" + name + "_request/1");
            exports.add("decode_" + name + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(layout.codecModuleFile(), writer -> {
            writer.write("%% REST JSON 1 codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", layout.codecModuleName());
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            writer.write("-export([$L]).", String.join(", ", exports));
            writer.write("");

            for (OperationShape op : operations) {
                emitEncoder(writer, model, service, op, httpIndex, sp);
                emitDecoder(writer, model, service, op, httpIndex, sp, layout);
            }

            emitHelpers(writer);
        });
    }

    /** Emits encode_<op>_request/1 for one operation. */
    private static void emitEncoder(
            ErlangWriter writer,
            Model model,
            ServiceShape service,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
        String inputRecord = recordName(sp.toSymbol(input));
        HttpTrait httpTrait = op.expectTrait(HttpTrait.class);
        String method = httpTrait.getMethod();
        String uriTemplate = httpTrait.getUri().toString();

        List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
        List<HttpBinding> queries = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY);
        List<HttpBinding> headers = httpIndex.getRequestBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> docMembers = httpIndex.getRequestBindings(op, HttpBinding.Location.DOCUMENT);

        List<String> patternParts = buildPatternParts(labels, queries, headers, docMembers, sp, model);
        String pattern = patternParts.isEmpty() ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

        writer.write("%% Encode HTTP request for $L.", op.getId());
        writer.write("encode_$L_request(#$L{$L}) ->", opName, inputRecord, pattern);
        writer.indent();

        String pathExpr = buildPathExpression(uriTemplate, labels, sp, model);
        writer.write("Path = $L,", pathExpr);

        if (queries.isEmpty()) {
            writer.write("Query = [],");
        } else {
            writer.write("Query = lists:filtermap(fun");
            for (HttpBinding qb : queries) {
                String fieldName = BeamNameUtils.toSnakeCase(qb.getMember().getMemberName());
                String paramName = qb.getLocationName();
                writer.write("    (V) when V =/= undefined -> {true, {<<\"$L\">>, encode_query_value(V)}};",
                        paramName);
            }
            writer.write("    (_) -> false");
            writer.write("end, [$L]),",
                    queries.stream()
                            .map(qb -> BeamNameUtils.toSnakeCase(qb.getMember().getMemberName()))
                            .collect(Collectors.joining(", ")));
        }

        if (headers.isEmpty()) {
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"application/json\">>}],");
        } else {
            writer.write("Headers0 = lists:filtermap(fun");
            for (HttpBinding hb : headers) {
                String fieldName = BeamNameUtils.toSnakeCase(hb.getMember().getMemberName());
                String headerName = hb.getLocationName();
                writer.write("    (V) when V =/= undefined -> {true, {<<\"$L\">>, to_binary(V)}};",
                        headerName);
            }
            writer.write("    (_) -> false");
            writer.write("end, [$L]),",
                    headers.stream()
                            .map(hb -> BeamNameUtils.toSnakeCase(hb.getMember().getMemberName()))
                            .collect(Collectors.joining(", ")));
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"application/json\">>} | Headers0],");
        }

        if (docMembers.isEmpty() || method.equals("GET") || method.equals("DELETE") || method.equals("HEAD")) {
            writer.write("Body = <<>>,");
        } else {
            writer.write("BodyMap = maps:filter(fun(_, V) -> V =/= undefined end, #{");
            for (HttpBinding db : docMembers) {
                String fieldName = BeamNameUtils.toSnakeCase(db.getMember().getMemberName());
                String jsonKey = db.getMember().getMemberName();
                writer.write("    <<\"$L\">> => $L,", jsonKey, fieldName);
            }
            writer.write("}),");
            writer.write("Body = jsone:encode(BodyMap),");
        }

        writer.write("#http_request{");
        writer.write("    method = <<\"$L\">>,", method);
        writer.write("    path = Path,");
        writer.write("    query = maps:from_list(Query),");
        writer.write("    headers = Headers,");
        writer.write("    body = Body");
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    /** Emits decode_<op>_response/1 for one operation. */
    private static void emitDecoder(
            ErlangWriter writer,
            Model model,
            ServiceShape service,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp,
            BeamErlangLayout layout) {

        String opName = sp.toSymbol(op).getName();
        StructureShape output = model.expectShape(op.getOutputShape(), StructureShape.class);
        String outputRecord = recordName(sp.toSymbol(output));
        int successCode = httpIndex.getResponseCode(op);

        List<HttpBinding> respHeaders = httpIndex.getResponseBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> respDoc = httpIndex.getResponseBindings(op, HttpBinding.Location.DOCUMENT);
        List<HttpBinding> respPayload = httpIndex.getResponseBindings(op, HttpBinding.Location.PAYLOAD);

        writer.write("%% Decode HTTP response for $L.", op.getId());
        writer.write("decode_$L_response(#http_response{status = $L, headers = _Headers, body = Body}) ->",
                opName, successCode);
        writer.indent();

        if (!respDoc.isEmpty() || !respPayload.isEmpty()) {
            writer.write("Decoded = case Body of");
            writer.indent();
            writer.write("<<>> -> #{};");
            writer.write("_ ->");
            writer.indent();
            writer.write("case jsone:decode(Body) of");
            writer.indent();
            writer.write("{ok, Val} -> Val;");
            writer.write("{error, _} -> #{}");
            writer.dedent();
            writer.write("end");
            writer.dedent();
            writer.dedent();
            writer.write("end,");
        }

        for (HttpBinding hb : respHeaders) {
            String fieldName = BeamNameUtils.toSnakeCase(hb.getMember().getMemberName());
            String headerName = hb.getLocationName();
            writer.write("$L = proplists:get_value(<<\"$L\">>, _Headers, undefined),",
                    fieldName, headerName);
        }

        List<String> recordFields = new ArrayList<>();
        for (HttpBinding hb : respHeaders) {
            String fieldName = BeamNameUtils.toSnakeCase(hb.getMember().getMemberName());
            recordFields.add("    " + fieldName + " = " + fieldName);
        }
        for (HttpBinding db : respDoc) {
            String fieldName = BeamNameUtils.toSnakeCase(db.getMember().getMemberName());
            String jsonKey = db.getMember().getMemberName();
            recordFields.add("    " + fieldName + " = maps:get(<<\"" + jsonKey + "\">>, Decoded, undefined)");
        }
        for (HttpBinding pb : respPayload) {
            String fieldName = BeamNameUtils.toSnakeCase(pb.getMember().getMemberName());
            recordFields.add("    " + fieldName + " = Body");
        }
        writer.write("{ok, #$L{", outputRecord);
        if (!recordFields.isEmpty()) {
            writer.write(String.join(",\n", recordFields));
        }
        writer.write("}};");

        writer.dedent();
        writer.write("decode_$L_response(#http_response{status = Status, body = Body}) ->", opName);
        writer.indent();
        writer.write("{error, {http_error, Status, Body}}.");
        writer.dedent();
        writer.write("");
    }

    /** Emits private helper functions used across all codecs. */
    private static void emitHelpers(ErlangWriter writer) {
        writer.write("%% -- Private helpers --");
        writer.write("");
        writer.write("to_binary(V) when is_binary(V) -> V;");
        writer.write("to_binary(V) when is_list(V) -> list_to_binary(V);");
        writer.write("to_binary(V) when is_integer(V) -> integer_to_binary(V);");
        writer.write("to_binary(V) when is_float(V) -> float_to_binary(V);");
        writer.write("to_binary(true) -> <<\"true\">>;");
        writer.write("to_binary(false) -> <<\"false\">>;");
        writer.write("to_binary(V) when is_atom(V) -> atom_to_binary(V, utf8).");
        writer.write("");
        writer.write("encode_query_value(V) when is_boolean(V) ->");
        writer.write("    atom_to_binary(V, utf8);");
        writer.write("encode_query_value(V) when is_integer(V) ->");
        writer.write("    integer_to_binary(V);");
        writer.write("encode_query_value(V) when is_float(V) ->");
        writer.write("    float_to_binary(V);");
        writer.write("encode_query_value(V) when is_binary(V) ->");
        writer.write("    V;");
        writer.write("encode_query_value(V) when is_atom(V) ->");
        writer.write("    atom_to_binary(V, utf8).");
        writer.write("");
        writer.write("uri_encode(Value) ->");
        writer.write("    uri_string:quote(Value).");
    }

    /** Record tag for #-record{} syntax; symbol names carry a trailing {@code ()} type suffix. */
    private static String recordName(Symbol symbol) {
        return symbol.getName().replace("()", "");
    }

    private static List<String> buildPatternParts(
            List<HttpBinding> labels,
            List<HttpBinding> queries,
            List<HttpBinding> headers,
            List<HttpBinding> docMembers,
            SymbolProvider sp,
            Model model) {
        List<String> parts = new ArrayList<>();
        for (HttpBinding b : concat(labels, queries, headers, docMembers)) {
            String field = BeamNameUtils.toSnakeCase(b.getMember().getMemberName());
            parts.add(field + " = " + field);
        }
        return parts;
    }

    @SafeVarargs
    private static <T> List<T> concat(List<T>... lists) {
        List<T> out = new ArrayList<>();
        for (List<T> l : lists) {
            out.addAll(l);
        }
        return out;
    }

    private static String buildPathExpression(
            String uriTemplate,
            List<HttpBinding> labels,
            SymbolProvider sp,
            Model model) {
        if (labels.isEmpty()) {
            return "<<\"" + uriTemplate + "\">>";
        }
        StringBuilder sb = new StringBuilder("<<");
        int pos = 0;
        while (pos < uriTemplate.length()) {
            int start = uriTemplate.indexOf('{', pos);
            if (start < 0) {
                sb.append("\"").append(uriTemplate.substring(pos)).append("\"");
                break;
            }
            if (start > pos) {
                sb.append("\"").append(uriTemplate, pos, start).append("\", ");
            }
            int end = uriTemplate.indexOf('}', start);
            String labelName = uriTemplate.substring(start + 1, end);
            String fieldName = BeamNameUtils.toSnakeCase(labelName);
            sb.append("(uri_encode(to_binary(").append(fieldName).append(")))/binary");
            pos = end + 1;
            if (pos < uriTemplate.length()) {
                sb.append(", ");
            }
        }
        sb.append(">>");
        return sb.toString();
    }
}
