package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.core.BeamHostLabelIndex;
import io.smithy.beam.core.BeamHttpBindings;
import io.smithy.beam.core.BeamNameUtils;
import io.smithy.beam.core.BeamRestXmlProtocolCodegen;
import io.smithy.beam.core.BeamXmlBindingIndex;
import software.amazon.smithy.codegen.core.Symbol;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBinding;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.BlobShape;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.StringShape;
import software.amazon.smithy.model.shapes.StructureShape;
import software.amazon.smithy.model.traits.EndpointTrait;
import software.amazon.smithy.model.traits.HttpTrait;
import software.amazon.smithy.model.traits.IdempotencyTokenTrait;
import software.amazon.smithy.model.traits.MediaTypeTrait;
import software.amazon.smithy.model.pattern.SmithyPattern;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * REST-XML protocol codec emitter for Erlang clients. Combines HTTP bindings
 * with XML payload encoding for restXml services.
 */
public final class ErlangRestXmlEmitter {

    private static final String DEFAULT_CONTENT_TYPE = "application/xml";

    private ErlangRestXmlEmitter() {}

    public static void emitCodecModule(ErlangContext ctx, ServiceShape service) {
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String codecFile = layout.clientCodecModuleName(BeamRestXmlProtocolCodegen.REST_XML) + ".erl";
        String codecModule = layout.clientCodecModuleName(BeamRestXmlProtocolCodegen.REST_XML);
        ErlangRuntimeHelpersEmitter.emitIfNeeded(ctx, service);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
        boolean encodeWithConfig = serviceHasHostLabelOperations(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("encode_" + name + "_request/" + (encodeWithConfig ? "2" : "1"));
        }

        Optional<String> serviceNamespace = BeamXmlBindingIndex.xmlNamespaceUri(service);

        ctx.writerDelegator().useFileWriter(codecFile, writer -> {
            writer.write("%% REST-XML codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by smithy-beam codegen.");
            writer.write("-module($L).", codecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            writer.write("-export([$L]).", String.join(", ", exports));
            writer.write("");

            emitServiceXmlNamespace(writer, serviceNamespace);

            for (OperationShape op : operations) {
                emitEncoder(writer, model, service, op, httpIndex, sp, encodeWithConfig);
            }

            emitXmlEncodeHelpers(writer);
            if (encodeWithConfig) {
                emitBuildHostHelpers(writer, model, service, sp);
            }
        });
    }

    private static void emitServiceXmlNamespace(ErlangWriter writer, Optional<String> namespaceUri) {
        if (namespaceUri.isPresent()) {
            writer.write("xml_namespace() -> #{uri => <<\"$L\">>}.", namespaceUri.get());
        } else {
            writer.write("xml_namespace() -> #{}.");
        }
        writer.write("");
    }

    private static void emitEncoder(
            ErlangWriter writer,
            Model model,
            ServiceShape service,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp,
            boolean encodeWithConfig) {

        String opName = sp.toSymbol(op).getName();
        StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
        String inputRecord = recordName(sp.toSymbol(input));
        String inputType = sp.toSymbol(input).getName();
        HttpTrait httpTrait = op.expectTrait(HttpTrait.class);
        String method = httpTrait.getMethod();
        String uriTemplate = httpTrait.getUri().toString();

        List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
        List<HttpBinding> queries = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY);
        List<HttpBinding> queryParams = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY_PARAMS);
        List<HttpBinding> headers = httpIndex.getRequestBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> prefixHeaders = httpIndex.getRequestBindings(op, HttpBinding.Location.PREFIX_HEADERS);
        List<HttpBinding> payloadMembers = httpIndex.getRequestBindings(op, HttpBinding.Location.PAYLOAD);

        String requestContentType = resolvedRequestContentType(model, op, payloadMembers);

        List<String> patternParts = buildPatternParts(labels, queries, queryParams, headers, prefixHeaders, payloadMembers);
        String pattern = patternParts.isEmpty() ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

        writer.write("%% Encode REST-XML request for $L.", op.getId());
        if (encodeWithConfig) {
            writer.write("-spec encode_$L_request(client_config(), $L) -> #http_request{}.",
                    opName, inputType);
            writer.write("encode_$L_request(Config, Input = #$L{$L}) ->", opName, inputRecord, pattern);
        } else {
            writer.write("-spec encode_$L_request($L) -> #http_request{}.", opName, inputType);
            writer.write("encode_$L_request(Input = #$L{$L}) ->", opName, inputRecord, pattern);
        }
        writer.indent();

        List<MemberShape> idempotencyMembers = input.members().stream()
                .filter(m -> m.hasTrait(IdempotencyTokenTrait.class))
                .collect(Collectors.toList());
        if (!idempotencyMembers.isEmpty()) {
            String currentInput = "Input";
            int step = 1;
            for (MemberShape member : idempotencyMembers) {
                String field = BeamNameUtils.toSnakeCase(member.getMemberName());
                String nextInput = "Input" + step;
                writer.write("$L = case $L#$L of", nextInput, currentInput, field);
                writer.indent();
                writer.write("undefined -> $L#$L{ $L = generate_uuid() };", currentInput, inputRecord, field);
                writer.write("_ -> $L", currentInput);
                writer.dedent();
                writer.write("end,");
                currentInput = nextInput;
                step++;
            }
            for (MemberShape member : idempotencyMembers) {
                String field = BeamNameUtils.toSnakeCase(member.getMemberName());
                writer.write("$L = $L#$L,", toBindingVar(field), currentInput, field);
            }
        }

        BeamHostLabelIndex hostLabelIndex = BeamHostLabelIndex.of(model);
        boolean hasHostLabels = !hostLabelIndex.hostLabelMembers(op).isEmpty()
                && op.hasTrait(EndpointTrait.class);

        String pathExpr = buildPathExpression(uriTemplate, labels);
        writer.write("Path = $L,", pathExpr);

        if (queries.isEmpty()) {
            writer.write("Query = [],");
        } else {
            writer.write("Query = lists:filtermap(fun");
            for (HttpBinding qb : queries) {
                String paramName = qb.getLocationName();
                writer.write("    (V) when V =/= undefined -> {true, {<<\"$L\">>, encode_query_value(V)}};",
                        paramName);
            }
            writer.write("    (_) -> false");
            writer.write("end, [$L]),",
                    queries.stream()
                            .map(qb -> toBindingVar(
                                    BeamNameUtils.toSnakeCase(qb.getMember().getMemberName())))
                            .collect(Collectors.joining(", ")));
        }

        if (!queryParams.isEmpty()) {
            for (HttpBinding qp : queryParams) {
                String fieldName = BeamNameUtils.toSnakeCase(qp.getMember().getMemberName());
                String bindingVar = toBindingVar(fieldName);
                writer.write("QueryExtra = case $L of", bindingVar);
                writer.indent();
                writer.write("undefined -> [];");
                writer.write("M when is_map(M) ->");
                writer.indent();
                writer.write("[{K, V} || {K, V} <- maps:to_list(M)]");
                writer.dedent();
                writer.dedent();
                writer.write("end,");
                writer.write("Query = Query ++ QueryExtra,");
            }
        }

        if (headers.isEmpty()) {
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"$L\">>}],", requestContentType);
        } else {
            writer.write("Headers0 = lists:filtermap(fun");
            for (HttpBinding hb : headers) {
                String headerName = hb.getLocationName();
                writer.write("    (V) when V =/= undefined -> {true, {<<\"$L\">>, to_binary(V)}};",
                        headerName);
            }
            writer.write("    (_) -> false");
            writer.write("end, [$L]),",
                    headers.stream()
                            .map(hb -> toBindingVar(
                                    BeamNameUtils.toSnakeCase(hb.getMember().getMemberName())))
                            .collect(Collectors.joining(", ")));
            writer.write("Headers = [{<<\"Content-Type\">>, <<\"$L\">>} | Headers0],", requestContentType);
        }

        for (HttpBinding ph : prefixHeaders) {
            String fieldName = BeamNameUtils.toSnakeCase(ph.getMember().getMemberName());
            String prefix = ph.getLocationName();
            writer.write("Headers = Headers ++ prefix_headers_to_list(<<\"$L\">>, $L),",
                    prefix, toBindingVar(fieldName));
        }

        emitRequestBody(writer, model, payloadMembers, method, sp);

        if (hasHostLabels) {
            writer.write("Host = build_host(Input, Config),");
        }

        writer.write("#http_request{");
        writer.write("    method = <<\"$L\">>,", method);
        writer.write("    path = Path,");
        writer.write("    query = maps:from_list(Query),");
        writer.write("    headers = Headers,");
        writer.write("    body = Body");
        if (hasHostLabels) {
            writer.write("    ,host = Host");
        }
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    private static void emitRequestBody(
            ErlangWriter writer,
            Model model,
            List<HttpBinding> payloadMembers,
            String method,
            SymbolProvider sp) {

        if (payloadMembers.isEmpty()
                || method.equals("GET")
                || method.equals("DELETE")
                || method.equals("HEAD")) {
            writer.write("Body = <<>>,");
            return;
        }

        HttpBinding payload = payloadMembers.get(0);
        MemberShape member = payload.getMember();
        Shape target = model.expectShape(member.getTarget());
        String fieldName = BeamNameUtils.toSnakeCase(member.getMemberName());
        String bindingVar = toBindingVar(fieldName);

        if (target instanceof BlobShape || target instanceof StringShape) {
            writer.write("Body = case $L of", bindingVar);
            writer.indent();
            writer.write("undefined -> <<>>;");
            writer.write("Value -> Value");
            writer.dedent();
            writer.write("end,");
            return;
        }

        String rootElement = BeamXmlBindingIndex.payloadRootElementName(member, target);
        writer.write("XmlNs = xml_namespace(),");
        writer.write("Body = case $L of", bindingVar);
        writer.indent();
        writer.write("undefined -> <<>>;");
        writer.write("PayloadValue ->");
        writer.indent();
        if (target instanceof StructureShape structure) {
            String recordName = structure.getId().getName();
            // record tag derived from shape id in generated types
            writer.write("MemberMap = $L,",
                    buildStructureXmlMap(model, structure, "PayloadValue", recordName(sp.toSymbol(structure))));
            writer.write("Payload = encode_xml(#{<<\"$L\">> => MemberMap}, XmlNs),", rootElement);
        } else {
            writer.write("Payload = encode_xml(#{<<\"$L\">> => PayloadValue}, XmlNs),", rootElement);
        }
        writer.write("Payload");
        writer.dedent();
        writer.dedent();
        writer.write("end,");
    }

    private static String buildStructureXmlMap(
            Model model, StructureShape structure, String recordVar, String recordTag) {
        List<String> entries = new ArrayList<>();
        for (MemberShape member : structure.members()) {
            if (BeamXmlBindingIndex.isXmlAttribute(member)) {
                continue;
            }
            String field = BeamNameUtils.toSnakeCase(member.getMemberName());
            String wireName = BeamXmlBindingIndex.memberElementName(member);
            entries.add("<<\"" + wireName + "\">> => " + recordVar + "#" + recordTag + "." + field);
        }
        if (entries.isEmpty()) {
            return "#{}" ;
        }
        return "#{" + String.join(", ", entries) + "}";
    }

    private static void emitXmlEncodeHelpers(ErlangWriter writer) {
        writer.write("encode_xml(RootMap, XmlNs) ->");
        writer.indent();
        writer.write("[{RootName, Content}] = maps:to_list(RootMap),");
        writer.write("Element = build_xml_element(RootName, Content, XmlNs),");
        writer.write("iolist_to_binary(xmerl:export_simple([Element], xmerl_xmlns, [], [{prolog, false}])).");
        writer.dedent();
        writer.write("");
        writer.write("build_xml_element(Name, Content, XmlNs) when is_map(Content) ->");
        writer.indent();
        writer.write("Attrs = xml_namespace_attrs(XmlNs),");
        writer.write("Children = [build_xml_child(K, V) || {K, V} <- maps:to_list(Content), V =/= undefined],");
        writer.write("{Name, Attrs, Children};");
        writer.dedent();
        writer.write("build_xml_element(Name, Content, XmlNs) ->");
        writer.indent();
        writer.write("{Name, xml_namespace_attrs(XmlNs), [{text, to_binary(Content)}]}.");
        writer.dedent();
        writer.write("");
        writer.write("build_xml_child(Name, Value) when is_map(Value) ->");
        writer.indent();
        writer.write("{Name, [], [build_xml_element(K, V, #{}) || {K, V} <- maps:to_list(Value), V =/= undefined]};");
        writer.dedent();
        writer.write("build_xml_child(Name, Values) when is_list(Values) ->");
        writer.indent();
        writer.write("{Name, [], [build_xml_element(<<\"member\">>, V, #{}) || V <- Values, V =/= undefined]};");
        writer.dedent();
        writer.write("build_xml_child(Name, Value) ->");
        writer.indent();
        writer.write("{Name, [], [{text, to_binary(Value)}]}.");
        writer.dedent();
        writer.write("");
        writer.write("xml_namespace_attrs(#{uri := Uri}) -> [{xmlns, Uri}];");
        writer.write("xml_namespace_attrs(#{uri := Uri, prefix := Prefix}) ->");
        writer.indent();
        writer.write("[{'xmlns:' ++ binary_to_list(Prefix), Uri}];");
        writer.dedent();
        writer.write("xml_namespace_attrs(_) -> [].");
        writer.write("");
        writer.write("encode_query_value(V) when is_integer(V) -> integer_to_binary(V);");
        writer.write("encode_query_value(V) when is_float(V) -> float_to_binary(V, [short]);");
        writer.write("encode_query_value(V) when is_boolean(V) -> atom_to_binary(V, utf8);");
        writer.write("encode_query_value(V) -> to_binary(V).");
        writer.write("");
        writer.write("to_binary(V) when is_binary(V) -> V;");
        writer.write("to_binary(V) when is_list(V) -> list_to_binary(V);");
        writer.write("to_binary(V) when is_atom(V) -> atom_to_binary(V, utf8);");
        writer.write("to_binary(V) when is_integer(V) -> integer_to_binary(V);");
        writer.write("to_binary(V) when is_float(V) -> float_to_binary(V, [short]);");
        writer.write("to_binary(V) when is_boolean(V) -> atom_to_binary(V, utf8).");
        writer.write("");
    }

    private static void emitBuildHostHelpers(
            ErlangWriter writer, Model model, ServiceShape service, SymbolProvider sp) {
        writer.write("split_base_url(BaseUrl) ->");
        writer.indent();
        writer.write("case uri_string:parse(BaseUrl) of");
        writer.indent();
        writer.write("#{scheme := Scheme, host := Host} = Parts ->");
        writer.indent();
        writer.write("PortSuffix = case maps:get(port, Parts, undefined) of");
        writer.indent();
        writer.write("undefined -> <<>>;");
        writer.write("Port -> <<\":\", (integer_to_binary(Port))/binary>>");
        writer.dedent();
        writer.write("end,");
        writer.write("{<< (list_to_binary(Scheme))/binary, \"://\">>,");
        writer.write(" << (list_to_binary(Host))/binary, PortSuffix/binary >>};");
        writer.dedent();
        writer.write("_ ->");
        writer.indent();
        writer.write("{<<>>, BaseUrl}");
        writer.dedent();
        writer.dedent();
        writer.write("end.");
        writer.dedent();
        writer.write("");

        BeamHostLabelIndex hostLabelIndex = BeamHostLabelIndex.of(model);
        for (OperationShape op : ErlangTopDown.containedOperationsSorted(model, service)) {
            List<MemberShape> hostLabels = hostLabelIndex.hostLabelMembers(op);
            if (hostLabels.isEmpty() || !op.hasTrait(EndpointTrait.class)) {
                continue;
            }
            StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
            String inputRecord = recordName(sp.toSymbol(input));
            SmithyPattern hostPrefix = op.expectTrait(EndpointTrait.class).getHostPrefix();
            String prefixExpr = buildHostPrefixExpression(hostPrefix);
            List<String> patternParts = hostLabels.stream()
                    .map(m -> {
                        String field = BeamNameUtils.toSnakeCase(m.getMemberName());
                        return field + " = " + toBindingVar(field);
                    })
                    .toList();
            String pattern = patternParts.isEmpty()
                    ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

            writer.write("build_host(#$L{$L}, Config) ->", inputRecord, pattern);
            writer.indent();
            writer.write("BaseUrl = maps:get(base_url, Config, <<>>),");
            writer.write("{_Scheme, Authority} = split_base_url(BaseUrl),");
            writer.write("Prefix = $L,", prefixExpr);
            writer.write("<<Prefix/binary, Authority/binary>>.");
            writer.dedent();
            writer.write("");
        }
    }

    public static boolean serviceHasHostLabelOperations(Model model, ServiceShape service) {
        BeamHostLabelIndex hostLabelIndex = BeamHostLabelIndex.of(model);
        for (OperationShape op : ErlangTopDown.containedOperationsSorted(model, service)) {
            if (!hostLabelIndex.hostLabelMembers(op).isEmpty() && op.hasTrait(EndpointTrait.class)) {
                return true;
            }
        }
        return false;
    }

    private static String recordName(Symbol symbol) {
        return symbol.getName().replace("()", "");
    }

    private static List<String> buildPatternParts(
            List<HttpBinding> labels,
            List<HttpBinding> queries,
            List<HttpBinding> queryParams,
            List<HttpBinding> headers,
            List<HttpBinding> prefixHeaders,
            List<HttpBinding> payloadMembers) {
        List<String> parts = new ArrayList<>();
        for (HttpBinding b : concat(labels, queries, queryParams, headers, prefixHeaders, payloadMembers)) {
            String field = BeamNameUtils.toSnakeCase(b.getMember().getMemberName());
            parts.add(field + " = " + toBindingVar(field));
        }
        return parts;
    }

    private static String toBindingVar(String snakeField) {
        return BeamNameUtils.toCamelCaseVariable(snakeField);
    }

    @SafeVarargs
    private static <T> List<T> concat(List<T>... lists) {
        List<T> out = new ArrayList<>();
        for (List<T> l : lists) {
            out.addAll(l);
        }
        return out;
    }

    private static String buildPathExpression(String uriTemplate, List<HttpBinding> labels) {
        if (labels.isEmpty()) {
            return "<<\"" + uriTemplate + "\">>";
        }
        StringBuilder sb = new StringBuilder("<<");
        int pos = 0;
        while (pos < uriTemplate.length()) {
            int start = uriTemplate.indexOf('{', pos);
            if (start < 0) {
                sb.append("\"").append(uriTemplate.substring(pos)).append("\"");
                break;
            }
            if (start > pos) {
                sb.append("\"").append(uriTemplate, pos, start).append("\", ");
            }
            int end = uriTemplate.indexOf('}', start);
            String labelName = uriTemplate.substring(start + 1, end);
            String fieldName = BeamNameUtils.toSnakeCase(labelName);
            sb.append("(uri_encode(to_binary(").append(toBindingVar(fieldName)).append(")))/binary");
            pos = end + 1;
            if (pos < uriTemplate.length()) {
                sb.append(", ");
            }
        }
        sb.append(">>");
        return sb.toString();
    }

    private static String buildHostPrefixExpression(SmithyPattern hostPrefix) {
        if (hostPrefix.getSegments().isEmpty()) {
            return "<<>>";
        }
        StringBuilder sb = new StringBuilder("<<");
        List<SmithyPattern.Segment> segments = hostPrefix.getSegments();
        for (int i = 0; i < segments.size(); i++) {
            SmithyPattern.Segment segment = segments.get(i);
            if (segment.isLabel()) {
                String fieldName = BeamNameUtils.toSnakeCase(segment.getContent());
                sb.append("(uri_encode(to_binary(")
                        .append(toBindingVar(fieldName))
                        .append(")))/binary");
            } else {
                sb.append("\"").append(segment.getContent()).append("\"");
            }
            if (i < segments.size() - 1) {
                sb.append(", ");
            }
        }
        sb.append(">>");
        return sb.toString();
    }

    private static String resolvedRequestContentType(
            Model model, OperationShape op, List<HttpBinding> payloadMembers) {
        if (!payloadMembers.isEmpty()) {
            MemberShape member = payloadMembers.get(0).getMember();
            Shape target = model.expectShape(member.getTarget());
            Optional<String> mediaType = member.getTrait(MediaTypeTrait.class)
                    .map(MediaTypeTrait::getValue);
            if (mediaType.isPresent()) {
                return mediaType.get();
            }
            if (target instanceof BlobShape) {
                return "application/octet-stream";
            }
            if (target instanceof StringShape) {
                return "text/plain";
            }
        }
        return BeamHttpBindings.from(model)
                .requestContentType(op, DEFAULT_CONTENT_TYPE)
                .orElse(DEFAULT_CONTENT_TYPE);
    }
}
