package io.smithy.beam.erlang;

import io.smithy.beam.ir.erlang.ErlAttribute;
import io.smithy.beam.ir.erlang.ErlCapturedBlock;
import io.smithy.beam.ir.erlang.ErlClause;
import io.smithy.beam.ir.erlang.ErlComment;
import io.smithy.beam.ir.erlang.ErlExportAttribute;
import io.smithy.beam.ir.erlang.ErlFunction;
import io.smithy.beam.ir.erlang.ErlModule;
import io.smithy.beam.ir.erlang.ErlTypeDef;
import io.smithy.beam.ir.erlang.ErlVarPattern;
import software.amazon.smithy.model.shapes.ServiceShape;

import java.util.ArrayList;
import java.util.List;

final class ErlangS3EndpointIr {
    private static final String CLIENT_CONFIG = "client_config()";

    private ErlangS3EndpointIr() {}

    static ErlModule s3EndpointModule(ServiceShape service) {
        List<ErlFunction> functions = new ArrayList<>();
        functions.add(regionHost());
        functions.add(resolveBucketUrl());
        functions.addAll(helperFunctions());
        return new ErlModule(
                "s3_endpoint",
                List.of(
                        ErlComment.comment(
                                "S3 bucket addressing helpers for " + service.getId() + " (generated)."),
                        ErlComment.comment("DO NOT EDIT -- generated by smithy-beam codegen.")),
                List.of(
                        ErlExportAttribute.export(List.of("resolve_bucket_url/3", "region_host/1")),
                        new ErlTypeDef("client_config", "#{binary() => term()}")),
                functions);
    }

    static ErlFunction regionHost() {
        return ErlFunction.functionWithSpec(
                "region_host",
                1,
                CLIENT_CONFIG,
                "binary()",
                List.of(ErlClause.blockClause(
                        List.of(ErlVarPattern.varPattern("Config")),
                        ErlCapturedBlock.capturedBlock(
                                """
                                BaseUrl = maps:get(base_url, Config, <<>>),
                                {_Scheme, Authority} = split_base_url(BaseUrl),
                                Authority"""))));
    }

    static ErlFunction resolveBucketUrl() {
        return ErlFunction.functionWithSpec(
                "resolve_bucket_url",
                3,
                CLIENT_CONFIG + ", binary(), binary()",
                "{binary(), binary()}",
                List.of(ErlClause.blockClause(
                        List.of(
                                ErlVarPattern.varPattern("Config"),
                                ErlVarPattern.varPattern("Bucket"),
                                ErlVarPattern.varPattern("Key")),
                        ErlCapturedBlock.capturedBlock(
                                """
                                Style = maps:get(s3_addressing_style, Config, virtual_host),
                                RegionHost = region_host(Config),
                                KeyPath = key_path(Key),
                                case Style of
                                    virtual_host ->
                                        Host = virtual_host(Config, Bucket, RegionHost),
                                        {Host, KeyPath};
                                    path_style ->
                                        {RegionHost, <<"/", Bucket/binary, KeyPath/binary>>};
                                    _ ->
                                        Host = virtual_host(Config, Bucket, RegionHost),
                                        {Host, KeyPath}
                                end"""))));
    }

    static List<ErlFunction> helperFunctions() {
        return List.of(
                keyPath(),
                virtualHost(),
                s3HostSuffix(),
                splitBaseUrl());
    }

    private static ErlFunction keyPath() {
        return ErlFunction.function(
                "key_path",
                1,
                List.of(
                        ErlClause.clause(
                                List.of(ErlVarPattern.varPattern("<<>>")),
                                ErlCapturedBlock.capturedBlock("<<>>")),
                        ErlClause.clause(
                                List.of(ErlVarPattern.varPattern("Key")),
                                ErlCapturedBlock.capturedBlock("<<\"/\", Key/binary>>"))));
    }

    private static ErlFunction virtualHost() {
        return ErlFunction.function(
                "virtual_host",
                3,
                List.of(ErlClause.blockClause(
                        List.of(
                                ErlVarPattern.varPattern("Config"),
                                ErlVarPattern.varPattern("Bucket"),
                                ErlVarPattern.varPattern("RegionHost")),
                        ErlCapturedBlock.capturedBlock(
                                """
                                case maps:get(s3_use_accelerate, Config, false) of
                                    true -> <<Bucket/binary, ".s3-accelerate.amazonaws.com">>;
                                    false ->
                                        Suffix = s3_host_suffix(Config),
                                        <<Bucket/binary, Suffix/binary, RegionHost/binary>>
                                end"""))));
    }

    private static ErlFunction s3HostSuffix() {
        return ErlFunction.function(
                "s3_host_suffix",
                1,
                List.of(ErlClause.blockClause(
                        List.of(ErlVarPattern.varPattern("Config")),
                        ErlCapturedBlock.capturedBlock(
                                """
                                case maps:get(s3_use_dualstack, Config, false) of
                                    true -> <<".s3.dualstack.">>;
                                    false -> <<".s3.">>
                                end"""))));
    }

    private static ErlFunction splitBaseUrl() {
        return ErlFunction.function(
                "split_base_url",
                1,
                List.of(
                        ErlClause.clause(
                                List.of(ErlVarPattern.varPattern("<<>>")),
                                ErlCapturedBlock.capturedBlock("{<<>>, <<>>}")),
                        ErlClause.blockClause(
                                List.of(ErlVarPattern.varPattern("BaseUrl")),
                                ErlCapturedBlock.capturedBlock(
                                        """
                                        case uri_string:parse(binary_to_list(BaseUrl)) of
                                            #{scheme := Scheme, host := Host} = Parts ->
                                                PortSuffix = case maps:get(port, Parts, undefined) of
                                                    undefined -> <<>>;
                                                    Port -> <<":", (integer_to_binary(Port))/binary>>
                                                end,
                                                {<< (list_to_binary(Scheme))/binary, "://">>,
                                                 << (list_to_binary(Host))/binary, PortSuffix/binary >>};
                                            _ ->
                                                {<<>>, BaseUrl}
                                        end"""))));
    }
}
