package io.smithy.beam.erlang;

import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.core.BeamRequestCompressionIndex;
import io.smithy.beam.ir.erlang.ErlAtom;
import io.smithy.beam.ir.erlang.ErlAtomPattern;
import io.smithy.beam.ir.erlang.ErlAttribute;
import io.smithy.beam.ir.erlang.ErlCallLocal;
import io.smithy.beam.ir.erlang.ErlClause;
import io.smithy.beam.ir.erlang.ErlComment;
import io.smithy.beam.ir.erlang.ErlExportAttribute;
import io.smithy.beam.ir.erlang.ErlFunction;
import io.smithy.beam.ir.erlang.ErlGuard;
import io.smithy.beam.ir.erlang.ErlListComprehension;
import io.smithy.beam.ir.erlang.ErlModule;
import io.smithy.beam.ir.erlang.ErlOp;
import io.smithy.beam.ir.erlang.ErlVar;
import io.smithy.beam.ir.erlang.ErlVarPattern;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBinding;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.shapes.EnumShape;
import software.amazon.smithy.model.shapes.IntEnumShape;
import software.amazon.smithy.model.shapes.MapShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.StructureShape;
import software.amazon.smithy.model.shapes.UnionShape;

final class ErlangRestJsonIr {
  private ErlangRestJsonIr() {}

  static String clientCodecFileName(ErlangContext ctx, ServiceShape service) {
    return layout(ctx, service).clientCodecModuleName(ctx.resolvedProtocolTraitId()) + ".erl";
  }

  static String serverCodecFileName(ErlangContext ctx, ServiceShape service) {
    return layout(ctx, service).serverCodecModuleName(ctx.resolvedProtocolTraitId()) + ".erl";
  }

  static ErlModule buildClientCodecModule(ErlangContext ctx, ServiceShape service) {
    Model model = ctx.model();
    ShapeId protocol = ctx.resolvedProtocolTraitId();
    BeamErlangLayout layout = layout(ctx, service);
    HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
    SymbolProvider sp = ctx.symbolProvider();
    List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
    boolean encodeWithConfig = ErlangRestJsonSupport.serviceHasHostLabelOperations(model, service);

    List<String> exports = new ArrayList<>();
    for (OperationShape op : operations) {
      String name = sp.toSymbol(op).getName();
      List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
      exports.add("encode_" + name + "_request/" + (encodeWithConfig ? "2" : "1"));
      exports.add("decode_" + name + "_request/" + (labels.isEmpty() ? "1" : "2"));
      exports.add("decode_" + name + "_response/1");
    }

    List<ErlFunction> functions =
        clientCodecFunctions(model, service, operations, httpIndex, sp, layout, encodeWithConfig);

    return new ErlModule(
        layout.clientCodecModuleName(protocol),
        List.of(
            ErlComment.comment("REST JSON 1 codecs for " + service.getId() + " (generated)."),
            ErlComment.comment("DO NOT EDIT -- generated by smithy-beam codegen.")),
        List.of(
            new ErlAttribute("include", "\"" + layout.typesHeaderFile() + "\""),
            new ErlAttribute("include", "\"" + layout.runtimeTypesHeaderFile() + "\""),
            ErlExportAttribute.export(exports)),
        functions);
  }

  static ErlModule buildServerCodecModule(ErlangContext ctx, ServiceShape service) {
    Model model = ctx.model();
    ShapeId protocol = ctx.resolvedProtocolTraitId();
    BeamErlangLayout layout = layout(ctx, service);
    HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
    SymbolProvider sp = ctx.symbolProvider();

    List<OperationShape> operations = ErlangTopDown.containedOperationsSorted(model, service);
    List<String> exports = new ArrayList<>();
    Set<ShapeId> errorIds = new LinkedHashSet<>();
    for (OperationShape op : operations) {
      String name = sp.toSymbol(op).getName();
      List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
      exports.add("decode_" + name + "_request/" + (labels.isEmpty() ? "1" : "2"));
      exports.add("encode_" + name + "_response/1");
      errorIds.addAll(op.getErrors());
    }
    for (ShapeId errorId : errorIds) {
      StructureShape errShape = model.expectShape(errorId, StructureShape.class);
      exports.add(
          "encode_" + ErlangRestJsonSupport.recordName(sp.toSymbol(errShape)) + "_response/1");
    }

    List<ErlFunction> functions =
        serverCodecFunctions(model, service, operations, httpIndex, sp, layout);

    return new ErlModule(
        layout.serverCodecModuleName(protocol),
        List.of(
            ErlComment.comment(
                "Server REST JSON 1 codecs for " + service.getId() + " (generated)."),
            ErlComment.comment("DO NOT EDIT -- generated by smithy-beam codegen.")),
        List.of(
            new ErlAttribute("include", "\"" + layout.typesHeaderFile() + "\""),
            new ErlAttribute("include", "\"" + layout.runtimeTypesHeaderFile() + "\""),
            ErlExportAttribute.export(exports)),
        functions);
  }

  static void emitClientCodecModule(ErlangContext ctx, ServiceShape service) {
    ErlModule module = buildClientCodecModule(ctx, service);
    ErlangCodecEmission.writeModule(ctx, clientCodecFileName(ctx, service), module);
  }

  static void emitServerCodecModule(ErlangContext ctx, ServiceShape service) {
    ErlangCodecEmission.emitRuntimeHelpersIfNeeded(ctx, service, true);
    ErlModule module = buildServerCodecModule(ctx, service);
    ErlangCodecEmission.writeModule(ctx, serverCodecFileName(ctx, service), module);
  }

  private static BeamErlangLayout layout(ErlangContext ctx, ServiceShape service) {
    return new BeamErlangLayout(ctx.settings(), service.getId().getNamespace(), service);
  }

  static ErlFunction encodeRequest(
      Model model,
      ServiceShape service,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      boolean encodeWithConfig,
      String eventStreamModule) {
    return ErlangRestJsonOperationIr.buildEncodeRequest(
        model, service, op, httpIndex, sp, encodeWithConfig, eventStreamModule);
  }

  static ErlFunction decodeRequest(
      Model model,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      String eventStreamModule) {
    return ErlangRestJsonOperationIr.buildDecodeRequest(
        model, op, httpIndex, sp, eventStreamModule);
  }

  static ErlFunction decodeResponse(
      Model model,
      ServiceShape service,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      BeamErlangLayout layout) {
    return ErlangRestJsonOperationIr.buildDecodeResponse(model, service, op, httpIndex, sp, layout);
  }

  static ErlFunction errorDispatch(
      Model model,
      ServiceShape service,
      OperationShape op,
      HttpBindingIndex httpIndex,
      SymbolProvider sp) {
    return ErlangRestJsonOperationIr.buildErrorDispatch(model, service, op, httpIndex, sp);
  }

  static List<ErlFunction> structureHelperFunctions(
      Model model, ServiceShape service, SymbolProvider sp) {
    List<ErlFunction> functions = new ArrayList<>();
    Set<StructureShape> structures = new LinkedHashSet<>();
    Set<StructureShape> listElementStructures = new LinkedHashSet<>();
    HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
    ErlangRestJsonSupport.collectStructureHelperTargets(
        model, service, httpIndex, structures, listElementStructures);
    for (StructureShape structure : structures) {
      functions.addAll(
          ErlangStructureHelperIr.structureDecodeEncode(model, httpIndex, structure, sp));
      if (listElementStructures.contains(structure)) {
        functions.addAll(buildStructureListDecodeEncodeFunctions(structure, sp));
      }
    }
    return functions;
  }

  static List<ErlFunction> buildStructureDecodeEncode(
      Model model, HttpBindingIndex httpIndex, StructureShape structure, SymbolProvider sp) {
    return ErlangStructureHelperIr.structureDecodeEncode(model, httpIndex, structure, sp);
  }

  static List<ErlFunction> buildStructureListDecodeEncodeFunctions(
      StructureShape structure, SymbolProvider sp) {
    String helperName = ErlangJsonCodecSupport.structureHelperName(sp, structure);
    return List.of(buildStructureListDecode(helperName), buildStructureListEncode(helperName));
  }

  private static ErlFunction buildStructureListDecode(String helperName) {
    return ErlFunction.function(
        "decode_" + helperName + "_list",
        1,
        List.of(
            ErlClause.clause(
                List.of(ErlAtomPattern.atomPattern("undefined")), ErlAtom.atom("undefined")),
            ErlClause.clause(
                List.of(ErlAtomPattern.atomPattern("null")), ErlAtom.atom("undefined")),
            ErlClause.clause(
                List.of(ErlVarPattern.varPattern("List")),
                List.of(ErlGuard.guard("is_list", ErlVar.var("List"))),
                ErlListComprehension.comprehensionWithFilters(
                    ErlCallLocal.callLocal("decode_" + helperName, ErlVar.var("V")),
                    ErlVarPattern.varPattern("V"),
                    ErlVar.var("List"),
                    List.of(ErlOp.op("=/=", ErlVar.var("V"), ErlAtom.atom("null")))))));
  }

  private static ErlFunction buildStructureListEncode(String helperName) {
    return ErlFunction.function(
        "encode_" + helperName + "_list",
        1,
        List.of(
            ErlClause.clause(
                List.of(ErlAtomPattern.atomPattern("undefined")), ErlAtom.atom("undefined")),
            ErlClause.clause(
                List.of(ErlVarPattern.varPattern("List")),
                List.of(ErlGuard.guard("is_list", ErlVar.var("List"))),
                ErlListComprehension.comprehensionWithFilters(
                    ErlCallLocal.callLocal("encode_" + helperName, ErlVar.var("V")),
                    ErlVarPattern.varPattern("V"),
                    ErlVar.var("List"),
                    List.of(ErlOp.op("=/=", ErlVar.var("V"), ErlAtom.atom("undefined")))))));
  }

  static List<ErlFunction> enumHelperFunctions(
      Model model, ServiceShape service, SymbolProvider sp) {
    List<ErlFunction> functions = new ArrayList<>();
    for (EnumShape enumShape : ErlangRestJsonSupport.reachableEnumShapes(model, service)) {
      functions.addAll(ErlangEnumHelperIr.enumDecodeEncode(enumShape, sp));
    }
    for (IntEnumShape intEnumShape : ErlangRestJsonSupport.reachableIntEnumShapes(model, service)) {
      functions.addAll(ErlangEnumHelperIr.intEnumDecodeEncode(intEnumShape, sp));
    }
    return functions;
  }

  static List<ErlFunction> unionHelperFunctions(
      Model model, ServiceShape service, SymbolProvider sp) {
    List<ErlFunction> functions = new ArrayList<>();
    for (UnionShape union : ErlangRestJsonSupport.reachableUnionShapes(model, service)) {
      functions.addAll(ErlangUnionHelperIr.unionDecodeEncode(union, sp));
    }
    return functions;
  }

  static List<ErlFunction> mapHelperFunctions(
      Model model, ServiceShape service, SymbolProvider sp) {
    List<ErlFunction> functions = new ArrayList<>();
    HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
    for (MapShape map : ErlangRestJsonSupport.reachableTypedMapShapes(model, service)) {
      functions.addAll(ErlangMapHelperIr.mapDecodeEncode(model, httpIndex, map, sp));
    }
    return functions;
  }

  static List<ErlFunction> privateCodecHelpers(Model model, ServiceShape service) {
    List<ErlFunction> functions = new ArrayList<>();
    functions.add(ErlangCodecHelperIr.toBinary(ErlangCodecHelperIr.ToBinaryVariant.REST_JSON));
    functions.add(ErlangCodecHelperIr.encodeQueryValueRestJson());
    functions.add(ErlangCodecHelperIr.uriEncode());
    functions.add(ErlangCodecHelperIr.uriDecode());
    functions.add(ErlangCodecHelperIr.decodeQueryParam());
    functions.add(ErlangCodecHelperIr.prefixHeadersToList());
    functions.add(ErlangCodecHelperIr.prefixHeadersFromList());
    functions.add(ErlangCodecHelperIr.decodeJsonBody());
    functions.add(ErlangCodecHelperIr.contentTypeMatches());
    functions.add(ErlangCodecHelperIr.ctBase());
    functions.add(ErlangCodecHelperIr.decodeSparseList());
    functions.add(ErlangCodecHelperIr.decodeList());
    functions.add(ErlangXmlCodecIr.decodeSparseMap());
    functions.add(ErlangCodecHelperIr.encodeSparseList());
    functions.add(ErlangCodecHelperIr.encodeSparseMap());
    functions.add(ErlangCodecHelperIr.encodeTimestampEpochSeconds());
    functions.add(ErlangCodecHelperIr.encodeTimestampDateTime());
    functions.add(ErlangCodecHelperIr.decodeTimestampEpochSeconds());
    functions.add(ErlangCodecHelperIr.decodeTimestampDateTime());
    functions.add(ErlangCodecHelperIr.generateUuid());

    boolean checksumBindings = ErlangHttpChecksumIr.serviceHasChecksumOperations(model, service);
    boolean compressionBindings = serviceHasCompressionOperations(model, service);
    if (checksumBindings) {
      functions.addAll(ErlangHttpChecksumIr.checksumHelperFunctions());
    } else if (compressionBindings) {
      functions.add(ErlangCodecHelperIr.headersSet());
    }
    return functions;
  }

  static boolean serviceHasCompressionOperations(Model model, ServiceShape service) {
    for (OperationShape op : ErlangTopDown.containedOperationsSorted(model, service)) {
      if (supportsGzipCompression(op)) {
        return true;
      }
    }
    return false;
  }

  static boolean supportsGzipCompression(OperationShape op) {
    return BeamRequestCompressionIndex.forOperation(op)
        .map(
            trait ->
                trait.getEncodings().stream()
                    .anyMatch(encoding -> encoding.equalsIgnoreCase("gzip")))
        .orElse(false);
  }

  static List<ErlFunction> clientCodecFunctions(
      Model model,
      ServiceShape service,
      List<OperationShape> operations,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      BeamErlangLayout layout,
      boolean encodeWithConfig) {
    List<ErlFunction> functions = new ArrayList<>();
    String eventStreamModule = layout.eventStreamModuleName();
    for (OperationShape op : operations) {
      functions.add(
          encodeRequest(model, service, op, httpIndex, sp, encodeWithConfig, eventStreamModule));
      functions.add(decodeRequest(model, op, httpIndex, sp, eventStreamModule));
      functions.add(decodeResponse(model, service, op, httpIndex, sp, layout));
    }
    for (OperationShape op : operations) {
      functions.add(errorDispatch(model, service, op, httpIndex, sp));
    }
    functions.addAll(structureHelperFunctions(model, service, sp));
    functions.addAll(enumHelperFunctions(model, service, sp));
    functions.addAll(unionHelperFunctions(model, service, sp));
    functions.addAll(mapHelperFunctions(model, service, sp));
    functions.addAll(privateCodecHelpers(model, service));
    if (encodeWithConfig) {
      functions.addAll(ErlangHostLabelIr.buildHostFunctions(model, service, sp));
    }
    return functions;
  }

  static List<ErlFunction> serverCodecFunctions(
      Model model,
      ServiceShape service,
      List<OperationShape> operations,
      HttpBindingIndex httpIndex,
      SymbolProvider sp,
      BeamErlangLayout layout) {
    List<ErlFunction> functions = new ArrayList<>();
    String eventStreamModule = layout.eventStreamModuleName();
    Set<ShapeId> emittedErrorEncoders = new LinkedHashSet<>();
    for (OperationShape op : operations) {
      functions.add(decodeRequest(model, op, httpIndex, sp, eventStreamModule));
      functions.add(ErlangRestJsonOperationIr.buildEncodeResponse(model, op, httpIndex, sp));
      for (ShapeId errorId : op.getErrors()) {
        if (emittedErrorEncoders.add(errorId)) {
          functions.add(ErlangRestJsonOperationIr.buildErrorResponseEncoder(model, errorId, sp));
        }
      }
    }
    functions.addAll(structureHelperFunctions(model, service, sp));
    functions.addAll(enumHelperFunctions(model, service, sp));
    functions.addAll(unionHelperFunctions(model, service, sp));
    functions.addAll(mapHelperFunctions(model, service, sp));
    functions.addAll(privateCodecHelpers(model, service));
    return functions;
  }
}
