package io.smithy.beam.ir.elixir;

public sealed interface ExExpr extends IrObject
    permits ExAtom,
        ExVar,
        ExInteger,
        ExString,
        ExNil,
        ExCall,
        ExCallLocal,
        ExDotCall,
        ExRemoteCall,
        ExMap,
        ExStruct,
        ExExprBlock,
        ExMatch,
        ExCase,
        ExIf,
        ExIfInList,
        ExPipeline,
        ExPipeCase,
        ExAnonymousFn,
        ExWith,
        ExList,
        ExTuple,
        ExKeyword,
        ExCapturedBlock,
        ExOp,
        ExFor,
        ExBinaryTemplate,
        ExStructUpdate,
        ExMapUpdate,
        ExStructAccess {}
